#pragma once
#include <wmtk/autogen/tri_mesh/autogenerated_tables.hpp>
#include <wmtk/dart/SimplexDart.hpp>

namespace wmtk::dart::utils {

int8_t
get_canonical_simplex_orientation(const SimplexDart& sd, PrimitiveType pt, int8_t simplex_index)
{
    const PrimitiveType source_pt = sd.simplex_type();

    if (source_pt == PrimitiveType::Triangle) {
        if (pt == PrimitiveType::Edge) {
            return autogen::tri_mesh::canonical_subdart_orientation[0][simplex_index];
        }
    } else if (source_pt == PrimitiveType::Tetrahedron) {
        if (pt >= PrimitiveType::Edge) {
            return autogen::tri_mesh::canonical_subdart_orientation[get_primitive_type_id(pt) - 1]
                                                                   [simplex_index];
        }
    }
    return sd.identity();
}
} // namespace wmtk::dart::utils
