#include "get_local_vertex_permutation.hpp"
#include <wmtk/autogen/edge_mesh/autogenerated_tables.hpp>
#include <wmtk/autogen/tet_mesh/autogenerated_tables.hpp>
#include <wmtk/autogen/tri_mesh/autogenerated_tables.hpp>
namespace wmtk::dart::utils {

VectorX<int8_t>::ConstMapType get_local_vertex_permutation(
    PrimitiveType pt,
    int8_t permutation_index)
{
    using CMT = VectorX<int8_t>::ConstMapType;
    const static int8_t x = 1;
    switch (pt) {
    case PrimitiveType::Edge: return CMT(autogen::edge_mesh::permutations[permutation_index], 2);
    case PrimitiveType::Triangle: return CMT(autogen::tri_mesh::permutations[permutation_index], 3);
    case PrimitiveType::Tetrahedron:
        return CMT(autogen::tet_mesh::permutations[permutation_index], 4);
    default:
    case PrimitiveType::Vertex: return CMT(&x, 1);
    }
}
} // namespace wmtk::dart::utils
