var _preserve_tagged_substructure_invariant_8hpp =
[
    [ "wmtk::components::isotropic_remeshing::invariants::PreserveTaggedSubstructureInvariant", "classwmtk_1_1components_1_1isotropic__remeshing_1_1invariants_1_1_preserve_tagged_substructure_invariant.html", "classwmtk_1_1components_1_1isotropic__remeshing_1_1invariants_1_1_preserve_tagged_substructure_invariant" ]
];