var _single_attribute_transfer_strategy_factory_8hpp =
[
    [ "wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactoryBase", "structwmtk_1_1components_1_1configurator_1_1transfer_1_1_single_attribute_transfer_strategy_factory_base.html", "structwmtk_1_1components_1_1configurator_1_1transfer_1_1_single_attribute_transfer_strategy_factory_base" ],
    [ "wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< Functor >", "structwmtk_1_1components_1_1configurator_1_1transfer_1_1_single_attribute_transfer_strategy_factory.html", "structwmtk_1_1components_1_1configurator_1_1transfer_1_1_single_attribute_transfer_strategy_factory" ]
];