Wildmeshing Toolkit: wmtk::components::envelope::invariants::EnvelopeInvariant Class Reference
wmtk::components::envelope::invariants::EnvelopeInvariant Class Reference
#include <EnvelopeInvariant.hpp>
Public Member Functions
EnvelopeInvariant (const attribute::MeshAttributeHandle &envelope_mesh_coordinate, double envelope_size, const attribute::MeshAttributeHandle &coordinate)
bool after (const std::vector< Tuple > &top_dimension_tuples_before, const std::vector< Tuple > &top_dimension_tuples_after) const override
const std::shared_ptr< SimpleBVH::BVH > & bvh () const
const attribute::MeshAttributeHandle & coordinate_handle () const
Public Member Functions inherited from wmtk::invariants::Invariant
virtual bool before (const simplex::Simplex &t) const
Invariant (const Mesh &m)
Invariant (const Mesh &m, bool use_before, bool use_old_state_in_after, bool use_new_state_in_after)
virtual ~Invariant ()
const Mesh & mesh () const
virtual bool directly_modified_after (const std::vector< simplex::Simplex > &simplices_before, const std::vector< simplex::Simplex > &simplices_after) const
bool use_before () const
bool use_after () const
bool use_old_state_in_after () const
bool use_new_state_in_after () const
virtual std::string name () const
Private Member Functions
bool has_envelope () const
Private Attributes
std::shared_ptr< fastEnvelope::FastEnvelope > m_envelope = nullptr
std::shared_ptr< SimpleBVH::BVH > m_bvh = nullptr
const attribute::MeshAttributeHandle m_coordinate_handle
const double m_envelope_size
Detailed Description
Definition at line 19 of file EnvelopeInvariant.hpp.
Constructor & Destructor Documentation
EnvelopeInvariant()
wmtk::components::envelope::invariants::EnvelopeInvariant::EnvelopeInvariant (const attribute::MeshAttributeHandle & envelope_mesh_coordinate, double envelope_size, const attribute::MeshAttributeHandle & coordinate)
Definition at line 29 of file EnvelopeInvariant.cpp.
References wmtk::attribute::MeshAttributeHandle::as(), wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::const_vector_attribute(), wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::dimension(), wmtk::Edge, wmtk::simplex::faces(), wmtk::attribute::MeshAttributeHandle::holds(), wmtk::logger(), m_bvh, m_envelope, wmtk::attribute::MeshAttributeHandle::mesh(), wmtk::PE, wmtk::PV, and wmtk::Triangle.
Member Function Documentation
after()
bool wmtk::components::envelope::invariants::EnvelopeInvariant::after (const std::vector< Tuple > & top_dimension_tuples_before, const std::vector< Tuple > & top_dimension_tuples_after) const override virtual
Reimplemented from wmtk::invariants::Invariant.
Definition at line 174 of file EnvelopeInvariant.cpp.
References wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::const_vector_attribute(), wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::dimension(), wmtk::Edge, wmtk::simplex::faces(), wmtk::simplex::faces_single_dimension_tuples(), wmtk::logger(), wmtk::PV, wmtk::Triangle, and wmtk::Vertex.
bvh()
const std::shared_ptr< SimpleBVH::BVH > & wmtk::components::envelope::invariants::EnvelopeInvariant::bvh () const inline
Definition at line 31 of file EnvelopeInvariant.hpp.
References m_bvh.
coordinate_handle()
const attribute::MeshAttributeHandle & wmtk::components::envelope::invariants::EnvelopeInvariant::coordinate_handle () const inline
Definition at line 32 of file EnvelopeInvariant.hpp.
References m_coordinate_handle.
has_envelope()
bool wmtk::components::envelope::invariants::EnvelopeInvariant::has_envelope () const private
Definition at line 169 of file EnvelopeInvariant.cpp.
Member Data Documentation
m_bvh
std::shared_ptr<SimpleBVH::BVH> wmtk::components::envelope::invariants::EnvelopeInvariant::m_bvh = nullptr private
Definition at line 38 of file EnvelopeInvariant.hpp.
Referenced by bvh(), and EnvelopeInvariant().
m_coordinate_handle
const attribute::MeshAttributeHandle wmtk::components::envelope::invariants::EnvelopeInvariant::m_coordinate_handle private
Definition at line 39 of file EnvelopeInvariant.hpp.
Referenced by coordinate_handle().
m_envelope
std::shared_ptr<fastEnvelope::FastEnvelope> wmtk::components::envelope::invariants::EnvelopeInvariant::m_envelope = nullptr private
Definition at line 37 of file EnvelopeInvariant.hpp.
Referenced by EnvelopeInvariant().
m_envelope_size
const double wmtk::components::envelope::invariants::EnvelopeInvariant::m_envelope_size private
Definition at line 41 of file EnvelopeInvariant.hpp.
The documentation for this class was generated from the following files:
components/envelope/src/wmtk/components/envelope/invariants/EnvelopeInvariant.hpp
components/envelope/src/wmtk/components/envelope/invariants/EnvelopeInvariant.cpp