Wildmeshing Toolkit: wmtk::dart::SimplexDart Class Reference
wmtk::dart::SimplexDart Class Reference abstract
#include <SimplexDart.hpp>
Public Member Functions
virtual ~SimplexDart ()
virtual int8_t product (int8_t a, int8_t b) const =0
virtual int8_t inverse (int8_t a) const =0
virtual int8_t identity () const =0
virtual int8_t opposite () const =0
virtual size_t size () const =0
virtual VectorX< int8_t >::ConstMapType permutation_indices () const =0
virtual wmtk::PrimitiveType simplex_type () const =0
virtual int8_t simplex_index (int8_t permutation_index, wmtk::PrimitiveType type) const =0
virtual int8_t permutation_index_from_primitive_switch (wmtk::PrimitiveType pt) const =0
bool is_valid (int8_t index) const
bool is_valid (const Dart &d) const
Dart act (const Dart &d, int8_t action) const
int8_t act (int8_t permutation, int8_t action) const
wmtk::Tuple as_tuple (int64_t gid, int8_t permutation_index) const
wmtk::Tuple update_tuple_from_permutation (const Tuple &t, int8_t permutation_index) const
wmtk::Tuple as_tuple (const Dart &dart) const
Dart as_dart (const wmtk::Tuple &t) const
int8_t get_permutation (const wmtk::Tuple &t) const
int8_t simplex_index (const Dart &dart, PrimitiveType simplex_type) const
wmtk::Tuple tuple_from_permutation_index (int64_t gid, int8_t permutation_index) const
wmtk::Tuple update_tuple_from_permutation_index (const Tuple &t, int8_t permutation_index) const
wmtk::Tuple tuple_from_dart (const Dart &dart) const
Dart dart_from_tuple (const wmtk::Tuple &t) const
int8_t permutation_index_from_tuple (const wmtk::Tuple &t) const
int8_t primitive_as_index (wmtk::PrimitiveType pt) const
int8_t product (const std::initializer_list< int8_t > &indices) const
int8_t convert (int8_t permutation_index, const SimplexDart &target) const
Static Public Member Functions
static const SimplexDart & get_singleton (wmtk::PrimitiveType simplex_type)
static const SimplexDart & get_singleton (int8_t dim)
Detailed Description
Definition at line 10 of file SimplexDart.hpp.
Constructor & Destructor Documentation
~SimplexDart()
wmtk::dart::SimplexDart::~SimplexDart () virtual default
Reimplemented in wmtk::autogen::edge_mesh::SimplexDart, wmtk::autogen::point_mesh::SimplexDart, wmtk::autogen::tet_mesh::SimplexDart, and wmtk::autogen::tri_mesh::SimplexDart.
Member Function Documentation
act() [1/2]
Dart wmtk::dart::SimplexDart::act (const Dart & d, int8_t action) const
Definition at line 113 of file SimplexDart.cpp.
References act(), wmtk::dart::_Dart< IndexType, OrientType >::global_id(), and wmtk::dart::_Dart< IndexType, OrientType >::permutation().
Referenced by act(), wmtk::dart::find_local_dart_action(), wmtk::operations::internal::CollapseAlternateFacetData::get_alternatives(), wmtk::dart::utils::opposite(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_dart(), and wmtk::multimesh::utils::internal::transport_tuple().
act() [2/2]
int8_t wmtk::dart::SimplexDart::act (int8_t permutation, int8_t action) const
Definition at line 98 of file SimplexDart.cpp.
References product().
as_dart()
Dart wmtk::dart::SimplexDart::as_dart (const wmtk::Tuple & t) const
as_tuple() [1/2]
wmtk::Tuple wmtk::dart::SimplexDart::as_tuple (const Dart & dart) const
as_tuple() [2/2]
wmtk::Tuple wmtk::dart::SimplexDart::as_tuple (int64_t gid, int8_t permutation_index) const
convert()
int8_t wmtk::dart::SimplexDart::convert (int8_t permutation_index, const SimplexDart & target) const
Definition at line 57 of file SimplexDart.cpp.
References wmtk::dart::subgroup::convert(), identity(), simplex_type(), and wmtk::Vertex.
Referenced by wmtk::dart::utils::apply_simplex_involution_directed(), wmtk::dart::utils::get_simplex_involution_upward(), wmtk::dart::utils::local_simplex_decomposition(), and wmtk::multimesh::utils::internal::transport_tuple().
dart_from_tuple()
Dart wmtk::dart::SimplexDart::dart_from_tuple (const wmtk::Tuple & t) const
Definition at line 76 of file SimplexDart.cpp.
References wmtk::Tuple::global_cid(), wmtk::Tuple::is_null(), wmtk::dart::utils::permutation_index_from_tuple(), and simplex_type().
Referenced by wmtk::multimesh::MultiMeshManager::can_map_to_child(), wmtk::multimesh::utils::extract_child_simplices_and_map_from_tag(), wmtk::operations::internal::CollapseAlternateFacetData::get_alternatives(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::populate(), and wmtk::multimesh::utils::internal::print_all_mapped_tuples().
get_permutation()
int8_t wmtk::dart::SimplexDart::get_permutation (const wmtk::Tuple & t) const
get_singleton() [1/2]
const SimplexDart & wmtk::dart::SimplexDart::get_singleton (int8_t dim) static
Definition at line 33 of file SimplexDart.cpp.
References simplex_type().
get_singleton() [2/2]
const SimplexDart & wmtk::dart::SimplexDart::get_singleton (wmtk::PrimitiveType simplex_type) static
Definition at line 23 of file SimplexDart.cpp.
References wmtk::Edge, simplex_type(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::operations::internal::SplitAlternateFacetData::add_facet(), wmtk::dart::utils::apply_simplex_involution(), wmtk::dart::utils::apply_simplex_involution_directed(), wmtk::operations::internal::SplitAlternateFacetOptionData::boundary_indices(), wmtk::utils::internal::boundary_manifold_decomposition(), wmtk::multimesh::MultiMeshManager::can_map_to_child(), wmtk::multimesh::utils::MapValidator::check_parent_map_attribute_valid(), wmtk::Mesh::consolidate(), wmtk::Mesh::dart_from_id(), wmtk::multimesh::utils::extract_child_simplices_and_map_from_tag(), wmtk::multimesh::utils::find_local_dart_action(), wmtk::multimesh::utils::find_local_dart_action(), wmtk::components::multimesh::from_manifold_decomposition(), wmtk::dart::utils::from_vertex_permutation(), wmtk::dart::utils::from_vertex_permutation(), wmtk::components::multimesh::from_vertex_simplices_map_(), wmtk::operations::internal::SplitAlternateFacetData::get_alternative(), wmtk::operations::internal::CollapseAlternateFacetData::get_alternatives(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::get_boundary_local_index(), wmtk::utils::internal::IndexSimplexMapper::get_internal_dart(), wmtk::utils::internal::IndexSimplexMapper::get_mesh_dart(), wmtk::operations::internal::CollapseAlternateFacetOptionData::get_neighbor_action(), wmtk::dart::utils::get_permutation(), wmtk::dart::utils::get_simplex_dart(), wmtk::dart::utils::get_simplex_involution_upward(), wmtk::utils::internal::IndexSimplexMapper::get_tuple(), wmtk::utils::internal::identity_tuple(), wmtk::dart::utils::indexed_topology_initialization(), wmtk::dart::utils::local_simplex_decomposition(), wmtk::multimesh::MultiMeshManager::mapped_tuples(), wmtk::utils::internal::ManifoldDecomposition< Dim >::mm_map(), wmtk::operations::internal::SplitAlternateFacetOptionData::new_gid(), wmtk::multimesh::MultiMeshManager::parent_local_fid(), wmtk::dart::utils::permute(), wmtk::dart::utils::permute(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::populate(), wmtk::multimesh::utils::internal::print_all_mapped_tuples(), wmtk::dart::utils::share_simplex(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_dart(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_facet(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_facet(), wmtk::multimesh::utils::internal::transport_tuple_dart(), wmtk::multimesh::MultiMeshManager::update_map_tuple_hashes(), and wmtk::utils::internal::IndexSimplexMapper::update_simplices().
identity()
virtual int8_t wmtk::dart::SimplexDart::identity () const pure virtual
Implemented in wmtk::autogen::edge_mesh::SimplexDart, wmtk::autogen::point_mesh::SimplexDart, wmtk::autogen::tet_mesh::SimplexDart, and wmtk::autogen::tri_mesh::SimplexDart.
Referenced by wmtk::dart::utils::apply_simplex_involution_directed(), convert(), wmtk::dart::utils::edge_mirror(), wmtk::dart::utils::get_canonical_simplex(), wmtk::dart::utils::get_canonical_subdart(), wmtk::dart::utils::get_canonical_supdart(), wmtk::dart::utils::local_simplex_decomposition(), and wmtk::multimesh::MultiMeshManager::update_map_tuple_hashes().
inverse()
virtual int8_t wmtk::dart::SimplexDart::inverse (int8_t a) const pure virtual
Implemented in wmtk::autogen::edge_mesh::SimplexDart, wmtk::autogen::point_mesh::SimplexDart, wmtk::autogen::tet_mesh::SimplexDart, and wmtk::autogen::tri_mesh::SimplexDart.
Referenced by wmtk::dart::utils::apply_simplex_involution_directed(), wmtk::dart::utils::edge_mirror(), wmtk::dart::utils::edge_mirror_left_action(), wmtk::dart::find_local_dart_action(), wmtk::dart::find_local_dart_left_action(), wmtk::dart::utils::get_canonical_simplex_orientation(), and wmtk::dart::utils::relative_face_index().
is_valid() [1/2]
bool wmtk::dart::SimplexDart::is_valid (const Dart & d) const
Definition at line 123 of file SimplexDart.cpp.
References is_valid(), and wmtk::dart::_Dart< IndexType, OrientType >::permutation().
is_valid() [2/2]
bool wmtk::dart::SimplexDart::is_valid (int8_t index) const
Definition at line 119 of file SimplexDart.cpp.
References size().
Referenced by is_valid().
opposite()
virtual int8_t wmtk::dart::SimplexDart::opposite () const pure virtual
Implemented in wmtk::autogen::edge_mesh::SimplexDart, wmtk::autogen::point_mesh::SimplexDart, wmtk::autogen::tet_mesh::SimplexDart, and wmtk::autogen::tri_mesh::SimplexDart.
permutation_index_from_primitive_switch()
virtual int8_t wmtk::dart::SimplexDart::permutation_index_from_primitive_switch (wmtk::PrimitiveType pt) const pure virtual
Implemented in wmtk::autogen::edge_mesh::SimplexDart, wmtk::autogen::point_mesh::SimplexDart, wmtk::autogen::tet_mesh::SimplexDart, and wmtk::autogen::tri_mesh::SimplexDart.
Referenced by primitive_as_index().
permutation_index_from_tuple()
int8_t wmtk::dart::SimplexDart::permutation_index_from_tuple (const wmtk::Tuple & t) const
Definition at line 51 of file SimplexDart.cpp.
References wmtk::dart::utils::permutation_index_from_tuple(), and simplex_type().
Referenced by wmtk::multimesh::utils::find_local_dart_action(), and wmtk::multimesh::utils::internal::transport_tuple().
permutation_indices()
virtual VectorX< int8_t >::ConstMapType wmtk::dart::SimplexDart::permutation_indices () const pure virtual
Implemented in wmtk::autogen::edge_mesh::SimplexDart, wmtk::autogen::point_mesh::SimplexDart, wmtk::autogen::tet_mesh::SimplexDart, and wmtk::autogen::tri_mesh::SimplexDart.
primitive_as_index()
int8_t wmtk::dart::SimplexDart::primitive_as_index (wmtk::PrimitiveType pt) const inline
Definition at line 52 of file SimplexDart.hpp.
References permutation_index_from_primitive_switch().
Referenced by wmtk::dart::utils::edge_mirror(), wmtk::dart::utils::edge_mirror_left_action(), and wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_dart().
product() [1/2]
int8_t wmtk::dart::SimplexDart::product (const std::initializer_list< int8_t > & indices) const
Definition at line 103 of file SimplexDart.cpp.
References product().
product() [2/2]
virtual int8_t wmtk::dart::SimplexDart::product (int8_t a, int8_t b) const pure virtual
Implemented in wmtk::autogen::edge_mesh::SimplexDart, wmtk::autogen::point_mesh::SimplexDart, wmtk::autogen::tet_mesh::SimplexDart, and wmtk::autogen::tri_mesh::SimplexDart.
Referenced by act(), wmtk::dart::utils::apply_simplex_involution(), wmtk::dart::utils::apply_simplex_involution_directed(), wmtk::dart::utils::edge_mirror(), wmtk::dart::utils::edge_mirror(), wmtk::dart::utils::edge_mirror_left_action(), wmtk::dart::find_local_dart_left_action(), wmtk::dart::utils::get_canonical_simplex_orientation(), wmtk::dart::utils::get_simplex_involution_upward(), wmtk::dart::local_dart_action(), and product().
simplex_index() [1/2]
int8_t wmtk::dart::SimplexDart::simplex_index (const Dart & dart, PrimitiveType simplex_type) const
Definition at line 87 of file SimplexDart.cpp.
References wmtk::dart::_Dart< IndexType, OrientType >::permutation(), simplex_index(), and simplex_type().
simplex_index() [2/2]
int8_t wmtk::dart::SimplexDart::simplex_index (int8_t permutation_index, wmtk::PrimitiveType type) const pure virtual
Implemented in wmtk::autogen::edge_mesh::SimplexDart, wmtk::autogen::point_mesh::SimplexDart, wmtk::autogen::tet_mesh::SimplexDart, and wmtk::autogen::tri_mesh::SimplexDart.
Definition at line 91 of file SimplexDart.cpp.
References wmtk::dart::utils::simplex_index_from_permutation_index(), and simplex_type().
Referenced by wmtk::operations::internal::CollapseAlternateFacetData::get_alternatives(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::get_boundary_local_index(), wmtk::multimesh::MultiMeshManager::parent_local_fid(), wmtk::dart::utils::relative_face_index(), wmtk::dart::utils::share_simplex(), simplex_index(), and wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_facet().
simplex_type()
virtual wmtk::PrimitiveType wmtk::dart::SimplexDart::simplex_type () const pure virtual
Implemented in wmtk::autogen::edge_mesh::SimplexDart, wmtk::autogen::point_mesh::SimplexDart, wmtk::autogen::tet_mesh::SimplexDart, and wmtk::autogen::tri_mesh::SimplexDart.
Referenced by convert(), dart_from_tuple(), wmtk::dart::utils::edge_mirror(), wmtk::dart::utils::get_canonical_simplex(), wmtk::dart::utils::get_canonical_subdart(), wmtk::dart::utils::get_canonical_supdart(), get_singleton(), get_singleton(), wmtk::dart::utils::local_simplex_decomposition(), wmtk::dart::utils::opposite(), permutation_index_from_tuple(), simplex_index(), simplex_index(), tuple_from_permutation_index(), and update_tuple_from_permutation_index().
size()
virtual size_t wmtk::dart::SimplexDart::size () const pure virtual
Implemented in wmtk::autogen::edge_mesh::SimplexDart, wmtk::autogen::point_mesh::SimplexDart, wmtk::autogen::tet_mesh::SimplexDart, and wmtk::autogen::tri_mesh::SimplexDart.
Referenced by is_valid().
tuple_from_dart()
wmtk::Tuple wmtk::dart::SimplexDart::tuple_from_dart (const Dart & dart) const
Definition at line 68 of file SimplexDart.cpp.
References wmtk::dart::_Dart< IndexType, OrientType >::global_id(), wmtk::dart::_Dart< IndexType, OrientType >::is_null(), wmtk::dart::_Dart< IndexType, OrientType >::permutation(), and tuple_from_permutation_index().
Referenced by wmtk::operations::internal::CollapseAlternateFacetData::get_alternatives(), wmtk::multimesh::MultiMeshManager::mapped_tuples(), wmtk::multimesh::utils::internal::print_all_mapped_tuples(), and wmtk::multimesh::MultiMeshManager::update_map_tuple_hashes().
tuple_from_permutation_index()
wmtk::Tuple wmtk::dart::SimplexDart::tuple_from_permutation_index (int64_t gid, int8_t permutation_index) const
Definition at line 43 of file SimplexDart.cpp.
References simplex_type(), and wmtk::dart::utils::tuple_from_permutation_index().
Referenced by tuple_from_dart().
update_tuple_from_permutation()
wmtk::Tuple wmtk::dart::SimplexDart::update_tuple_from_permutation (const Tuple & t, int8_t permutation_index) const
update_tuple_from_permutation_index()
wmtk::Tuple wmtk::dart::SimplexDart::update_tuple_from_permutation_index (const Tuple & t, int8_t permutation_index) const
Definition at line 47 of file SimplexDart.cpp.
References wmtk::Tuple::global_cid(), simplex_type(), and wmtk::dart::utils::tuple_from_permutation_index().
Referenced by wmtk::multimesh::utils::internal::transport_tuple().
The documentation for this class was generated from the following files:
src/wmtk/dart/SimplexDart.hpp
src/wmtk/dart/SimplexDart.cpp