Wildmeshing Toolkit: wmtk::components::envelope::BVHEnvelope Class Reference
wmtk::components::envelope::BVHEnvelope Class Reference
#include <BVHEnvelope.hpp>
Public Types
using Vec3dMax = Eigen::Matrix< double, Eigen::Dynamic, 1, Eigen::ColMajor, 3, 1 >
Public Member Functions
BVHEnvelope (const Eigen::MatrixXd &V, const Eigen::MatrixXi &S, double envelope_size)
~BVHEnvelope () final override
bool is_inside (const Vector3d &p) const final override
bool is_inside (const Vector3r &p) const final override
bool is_inside (const Vector3d &start, const Vector3d &b) const
std::tuple< Vec3dMax, double, int > nearest_point (const Vec3dMax &start) const
void update_nearest_point (const Vec3dMax &start, Vec3dMax &nearest_point, double &sq_dist, int &nearest_facet) const
std::tuple< Vec3d, double, int > edge_nearest_point (const Vec3dMax &start, const Vec3dMax &end) const
Public Member Functions inherited from wmtk::components::envelope::Envelope
virtual ~Envelope ()
virtual bool is_inside (const Mesh &m, const Tuple &tuple, const PrimitiveType pt) const =0
bool is_inside (const Mesh &m, const std::vector< Tuple > &simplices, const PrimitiveType pt) const
bool is_inside (const Mesh &m, const std::vector< Tuple > &simplices) const
Private Attributes
std::shared_ptr< SimpleBVH::BVH > m_bvh = nullptr
double m_envelope_size = 1e-3
Detailed Description
Definition at line 13 of file BVHEnvelope.hpp.
Member Typedef Documentation
Vec3dMax
using wmtk::components::envelope::BVHEnvelope::Vec3dMax = Eigen::Matrix<double, Eigen::Dynamic, 1, Eigen::ColMajor, 3, 1>
Definition at line 17 of file BVHEnvelope.hpp.
Constructor & Destructor Documentation
BVHEnvelope()
wmtk::components::envelope::BVHEnvelope::BVHEnvelope (const Eigen::MatrixXd & V, const Eigen::MatrixXi & S, double envelope_size)
Definition at line 6 of file BVHEnvelope.cpp.
References m_bvh.
~BVHEnvelope()
wmtk::components::envelope::BVHEnvelope::~BVHEnvelope () final override default
Member Function Documentation
edge_nearest_point()
auto wmtk::components::envelope::BVHEnvelope::edge_nearest_point (const Vec3dMax & start, const Vec3dMax & end) const
Definition at line 28 of file BVHEnvelope.cpp.
is_inside() [1/3]
bool wmtk::components::envelope::BVHEnvelope::is_inside (const Vector3d & p) const final override virtual
Implements wmtk::components::envelope::Envelope.
Definition at line 13 of file BVHEnvelope.cpp.
Referenced by is_inside().
is_inside() [2/3]
bool wmtk::components::envelope::BVHEnvelope::is_inside (const Vector3d & start, const Vector3d & b) const
Definition at line 68 of file BVHEnvelope.cpp.
References wmtk::logger(), nearest_point(), and update_nearest_point().
is_inside() [3/3]
bool wmtk::components::envelope::BVHEnvelope::is_inside (const Vector3r & p) const final override virtual
Implements wmtk::components::envelope::Envelope.
Definition at line 14 of file BVHEnvelope.cpp.
References is_inside().
nearest_point()
auto wmtk::components::envelope::BVHEnvelope::nearest_point (const Vec3dMax & start) const
Definition at line 19 of file BVHEnvelope.cpp.
Referenced by is_inside(), and update_nearest_point().
update_nearest_point()
void wmtk::components::envelope::BVHEnvelope::update_nearest_point (const Vec3dMax & start, Vec3dMax & nearest_point, double & sq_dist, int & nearest_facet) const
Definition at line 56 of file BVHEnvelope.cpp.
References m_bvh, and nearest_point().
Referenced by is_inside().
Member Data Documentation
m_bvh
std::shared_ptr<SimpleBVH::BVH> wmtk::components::envelope::BVHEnvelope::m_bvh = nullptr private
Definition at line 37 of file BVHEnvelope.hpp.
Referenced by BVHEnvelope(), and update_nearest_point().
m_envelope_size
double wmtk::components::envelope::BVHEnvelope::m_envelope_size = 1e-3 private
Definition at line 38 of file BVHEnvelope.hpp.
The documentation for this class was generated from the following files:
components/envelope/src/wmtk/components/envelope/BVHEnvelope.hpp
components/envelope/src/wmtk/components/envelope/BVHEnvelope.cpp