Wildmeshing Toolkit: wmtk::utils::DisjointSet Class Reference
wmtk::utils::DisjointSet Class Reference
#include <DisjointSet.hpp>
Public Member Functions
DisjointSet (size_t size)
void merge (size_t a, size_t b)
size_t get_root (size_t a) const
bool is_root (size_t a) const
std::vector< size_t > roots () const
size_t size () const
Private Member Functions
void merge_sorted (size_t lower, size_t higher)
size_t get_root_recursive (size_t a)
Private Attributes
std::vector< size_t > _parents
Detailed Description
Definition at line 7 of file DisjointSet.hpp.
Constructor & Destructor Documentation
DisjointSet()
wmtk::utils::DisjointSet::DisjointSet (size_t size) inline
Definition at line 28 of file DisjointSet.hpp.
References _parents.
Member Function Documentation
get_root()
size_t wmtk::utils::DisjointSet::get_root (size_t a) const inline
Definition at line 40 of file DisjointSet.hpp.
References _parents.
Referenced by wmtk::components::multimesh::axis_aligned_fusion(), wmtk::utils::internal::boundary_manifold_decomposition(), wmtk::dart::utils::indexed_topology_initialization(), and wmtk::components::multimesh::vertex_fusion().
get_root_recursive()
size_t wmtk::utils::DisjointSet::get_root_recursive (size_t a) inline private
Definition at line 49 of file DisjointSet.hpp.
References _parents, and get_root_recursive().
Referenced by get_root_recursive(), and merge().
is_root()
bool wmtk::utils::DisjointSet::is_root (size_t a) const inline
Definition at line 35 of file DisjointSet.hpp.
References _parents.
Referenced by roots().
merge()
void wmtk::utils::DisjointSet::merge (size_t a, size_t b) inline
Definition at line 58 of file DisjointSet.hpp.
References _parents, and get_root_recursive().
Referenced by wmtk::components::multimesh::axis_aligned_fusion(), wmtk::utils::internal::boundary_manifold_decomposition(), wmtk::dart::utils::indexed_topology_initialization(), and wmtk::components::multimesh::vertex_fusion().
merge_sorted()
void wmtk::utils::DisjointSet::merge_sorted (size_t lower, size_t higher) private
roots()
std::vector< size_t > wmtk::utils::DisjointSet::roots () const inline
Definition at line 68 of file DisjointSet.hpp.
References _parents, and is_root().
Referenced by wmtk::components::multimesh::axis_aligned_fusion(), wmtk::utils::internal::boundary_manifold_decomposition(), wmtk::dart::utils::indexed_topology_initialization(), and wmtk::components::multimesh::vertex_fusion().
size()
size_t wmtk::utils::DisjointSet::size () const inline
Definition at line 20 of file DisjointSet.hpp.
References _parents.
Referenced by wmtk::dart::utils::indexed_topology_initialization().
Member Data Documentation
_parents
std::vector<size_t> wmtk::utils::DisjointSet::_parents private
Definition at line 26 of file DisjointSet.hpp.
Referenced by DisjointSet(), get_root(), get_root_recursive(), is_root(), merge(), roots(), and size().
The documentation for this class was generated from the following file:
src/wmtk/utils/DisjointSet.hpp