Wildmeshing Toolkit: wmtk::dart::_Dart< IndexType, OrientType > Class Template Reference
wmtk::dart::_Dart< IndexType, OrientType > Class Template Reference
#include <Dart.hpp>
Public Types
using tuple_type = std::tuple< IndexType, OrientType >
Public Member Functions
IndexType & global_id ()
IndexType global_id () const
OrientType & permutation ()
OrientType permutation () const
bool is_null () const
operator std::string () const
const tuple_type & as_tuple () const
template<typename A , typename B >
_Dart & operator= (const _Dart< A, B > &o)
Detailed Description
template<typename IndexType, typename OrientType>
class wmtk::dart::_Dart< IndexType, OrientType >
Definition at line 13 of file Dart.hpp.
Member Typedef Documentation
tuple_type
template<typename IndexType , typename OrientType > using wmtk::dart::_Dart< IndexType, OrientType >::tuple_type = std::tuple<IndexType, OrientType>
Definition at line 16 of file Dart.hpp.
Member Function Documentation
as_tuple()
template<typename IndexType , typename OrientType > const tuple_type & wmtk::dart::_Dart< IndexType, OrientType >::as_tuple () const inline
Definition at line 32 of file Dart.hpp.
Referenced by wmtk::dart::_Dart< IndexType, OrientType >::operator=().
global_id() [1/2]
template<typename IndexType , typename OrientType > IndexType & wmtk::dart::_Dart< IndexType, OrientType >::global_id () inline
Definition at line 19 of file Dart.hpp.
Referenced by wmtk::dart::SimplexDart::act(), wmtk::dart::utils::apply_simplex_involution(), wmtk::multimesh::utils::MapValidator::check_parent_map_attribute_valid(), wmtk::Mesh::consolidate(), wmtk::dart::utils::edge_mirror(), wmtk::dart::utils::edge_mirror(), wmtk::multimesh::utils::extract_child_simplices_and_map_from_tag(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::get_neighbor(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::get_neighbor(), wmtk::dart::utils::get_simplex_involution(), wmtk::Mesh::id(), wmtk::Mesh::id(), wmtk::dart::utils::indexed_topology_initialization(), wmtk::dart::_Dart< IndexType, OrientType >::is_null(), wmtk::dart::local_dart_action(), wmtk::operations::internal::CollapseAlternateFacetOptionData::map_permutation_to_alt(), wmtk::dart::_Dart< IndexType, OrientType >::operator std::string(), wmtk::dart::operator==(), wmtk::operations::internal::operator==(), wmtk::operations::internal::operator==(), wmtk::dart::utils::opposite(), wmtk::multimesh::utils::internal::print_all_mapped_tuples(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_facet(), wmtk::dart::SimplexDart::tuple_from_dart(), and wmtk::multimesh::MultiMeshManager::update_map_tuple_hashes().
global_id() [2/2]
template<typename IndexType , typename OrientType > IndexType wmtk::dart::_Dart< IndexType, OrientType >::global_id () const inline
Definition at line 20 of file Dart.hpp.
is_null()
template<typename IndexType , typename OrientType > bool wmtk::dart::_Dart< IndexType, OrientType >::is_null () const inline
Definition at line 25 of file Dart.hpp.
References wmtk::dart::_Dart< IndexType, OrientType >::global_id().
Referenced by wmtk::multimesh::utils::MapValidator::check_parent_map_attribute_valid(), wmtk::dart::utils::indexed_topology_initialization(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::is_boundary(), wmtk::operations::internal::CollapseAlternateFacetOptionData::map_permutation_to_alt(), wmtk::operations::internal::CollapseAlternateFacetOptionData::map_permutation_to_alt(), wmtk::multimesh::utils::internal::print_all_mapped_tuples(), wmtk::dart::SimplexDart::tuple_from_dart(), and wmtk::multimesh::MultiMeshManager::update_map_tuple_hashes().
operator std::string()
template<typename IndexType , typename OrientType > wmtk::dart::_Dart< IndexType, OrientType >::operator std::string () const inline
Definition at line 27 of file Dart.hpp.
References wmtk::dart::_Dart< IndexType, OrientType >::global_id(), and wmtk::dart::_Dart< IndexType, OrientType >::permutation().
operator=()
template<typename IndexType , typename OrientType > template<typename A , typename B > _Dart & wmtk::dart::_Dart< IndexType, OrientType >::operator= (const _Dart< A, B > & o) inline
Definition at line 35 of file Dart.hpp.
References wmtk::dart::_Dart< IndexType, OrientType >::as_tuple().
permutation() [1/2]
template<typename IndexType , typename OrientType > OrientType & wmtk::dart::_Dart< IndexType, OrientType >::permutation () inline
Definition at line 22 of file Dart.hpp.
Referenced by wmtk::dart::SimplexDart::act(), wmtk::dart::utils::apply_simplex_involution(), wmtk::multimesh::utils::MapValidator::check_parent_map_attribute_valid(), wmtk::Mesh::consolidate(), wmtk::dart::utils::edge_mirror(), wmtk::dart::utils::edge_mirror(), wmtk::multimesh::utils::extract_child_simplices_and_map_from_tag(), wmtk::multimesh::utils::find_local_dart_action(), wmtk::operations::internal::CollapseAlternateFacetData::get_alternatives(), wmtk::operations::internal::CollapseAlternateFacetOptionData::get_neighbor_action(), wmtk::dart::utils::get_simplex_involution(), wmtk::Mesh::id(), wmtk::Mesh::id(), wmtk::dart::SimplexDart::is_valid(), wmtk::operations::internal::CollapseAlternateFacetOptionData::local_boundary_index(), wmtk::dart::local_dart_action(), wmtk::operations::internal::CollapseAlternateFacetOptionData::map_dart_to_alt(), wmtk::operations::internal::CollapseAlternateFacetOptionData::map_permutation_to_alt(), wmtk::dart::_Dart< IndexType, OrientType >::operator std::string(), wmtk::dart::utils::opposite(), wmtk::dart::SimplexDart::simplex_index(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_facet(), wmtk::dart::SimplexDart::tuple_from_dart(), and wmtk::multimesh::MultiMeshManager::update_map_tuple_hashes().
permutation() [2/2]
template<typename IndexType , typename OrientType > OrientType wmtk::dart::_Dart< IndexType, OrientType >::permutation () const inline
Definition at line 23 of file Dart.hpp.
The documentation for this class was generated from the following file:
src/wmtk/dart/Dart.hpp