Wildmeshing Toolkit: wmtk::multimesh::utils::internal::TupleTag Class Reference
wmtk::multimesh::utils::internal::TupleTag Class Reference
TupleTag is a util helper class for tagging facets in a triangle mesh.
#include <TupleTag.hpp>
Public Member Functions
TupleTag (Mesh &mesh, const std::set< int64_t > &critical_boundaries)
TupleTag (Mesh &mesh, PrimitiveType facet_type, const std::set< int64_t > &critical_boundaries)
const Mesh & mesh () const
Mesh & mesh ()
void initialize ()
Go through facets of the parent mesh (triangle mesh) and initialize all the boundary tags to be -1.
std::set< int64_t > run ()
bool is_critical_boundary (const Tuple &v) const
Check if a boundary is a critical point.
bool boundary_is_root (const Tuple &v) const
int64_t boundary_get_root (const Tuple &v) const
void boundary_set_root (const Tuple &v, int64_t root)
void boundary_sets_unify (const Tuple &v1, const Tuple &v2)
Given two boundary tuple, join the sets that contain them.
void run (const Tuple &e)
Given an facet, join the sets that contains the two end vertices.
int64_t get_boundary_tag (const Tuple &tuple) const
int64_t get_facet_tag (const Tuple &tuple) const
void set_boundary_tag (const Tuple &tuple, int64_t tag)
void set_facet_tag (const Tuple &tuple, int64_t tag)
int64_t vid (const Tuple &tuple) const
Tuple v_tuple (int64_t vid) const
PrimitiveType facet_type () const
PrimitiveType boundary_type () const
Static Public Member Functions
template<typename T >
static std::shared_ptr< Mesh > extract_and_register_child_mesh_from_tag_handle (Mesh &m, const wmtk::attribute::TypedAttributeHandle< T > &tag_handle, const T &tag_value, bool child_is_free, bool decompose_nonmanifold)
Public Attributes
Mesh & m_mesh
std::set< int64_t > m_critical_boundaries
wmtk::attribute::Accessor< int64_t, Mesh, wmtk::attribute::CachingAttribute< int64_t >, 1 > m_boundary_tag_acc
wmtk::attribute::Accessor< int64_t, Mesh, wmtk::attribute::CachingAttribute< int64_t >, 1 > m_facet_tag_acc
Detailed Description
TupleTag is a util helper class for tagging facets in a triangle mesh.
These tags can then be used to extract facet meshes as child mesh for multimesh.
The tagging algorithm is based on the union-find algorithm. It first tags all vertices by grouping them into disjoint sets. Then it creates facet tags based on the boundary tags. Vertex tag and facet tags are stored as mesh attributes of the parent triangle mesh, and can be accessed through "boundary_tag_handle" and "facet_tag_handle" respectively.
Definition at line 16 of file TupleTag.hpp.
Constructor & Destructor Documentation
TupleTag() [1/2]
wmtk::multimesh::utils::internal::TupleTag::TupleTag (Mesh & mesh, const std::set< int64_t > & critical_boundaries) inline
Definition at line 19 of file TupleTag.hpp.
TupleTag() [2/2]
wmtk::multimesh::utils::internal::TupleTag::TupleTag (Mesh & mesh, PrimitiveType facet_type, const std::set< int64_t > & critical_boundaries)
Definition at line 5 of file TupleTag.cpp.
References initialize().
Member Function Documentation
boundary_get_root()
int64_t wmtk::multimesh::utils::internal::TupleTag::boundary_get_root (const Tuple & v) const
Definition at line 174 of file TupleTag.cpp.
References boundary_is_root(), get_boundary_tag(), and v_tuple().
Referenced by boundary_sets_unify(), and run().
boundary_is_root()
bool wmtk::multimesh::utils::internal::TupleTag::boundary_is_root (const Tuple & v) const
Definition at line 168 of file TupleTag.cpp.
References get_boundary_tag(), and vid().
Referenced by boundary_get_root(), and boundary_set_root().
boundary_set_root()
void wmtk::multimesh::utils::internal::TupleTag::boundary_set_root (const Tuple & v, int64_t root)
Definition at line 184 of file TupleTag.cpp.
References boundary_is_root(), get_boundary_tag(), set_boundary_tag(), and v_tuple().
Referenced by boundary_sets_unify().
boundary_sets_unify()
void wmtk::multimesh::utils::internal::TupleTag::boundary_sets_unify (const Tuple & v1, const Tuple & v2)
Given two boundary tuple, join the sets that contain them.
Parameters
v1
v2
Definition at line 195 of file TupleTag.cpp.
References boundary_get_root(), boundary_set_root(), and is_critical_boundary().
Referenced by run().
boundary_type()
PrimitiveType wmtk::multimesh::utils::internal::TupleTag::boundary_type () const
Definition at line 22 of file TupleTag.cpp.
References m_boundary_tag_acc.
Referenced by initialize(), run(), run(), v_tuple(), and vid().
extract_and_register_child_mesh_from_tag_handle()
template<typename T > std::shared_ptr< Mesh > wmtk::multimesh::utils::internal::TupleTag::extract_and_register_child_mesh_from_tag_handle (Mesh & m, const wmtk::attribute::TypedAttributeHandle< T > & tag_handle, const T & tag_value, bool child_is_free, bool decompose_nonmanifold) static
Definition at line 17 of file extract_child_mesh_from_tag.cpp.
References wmtk::Edge, wmtk::multimesh::from_facet_orientations(), wmtk::Mesh::from_vertex_indices(), wmtk::utils::internal::is_manifold(), wmtk::attribute::TypedAttributeHandle< T >::primitive_type(), wmtk::Mesh::register_child_mesh(), wmtk::multimesh::utils::tagged_tuples(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::multimesh::utils::extract_and_register_child_mesh_from_tag(), and wmtk::multimesh::utils::extract_and_register_child_mesh_from_tag_handle().
facet_type()
PrimitiveType wmtk::multimesh::utils::internal::TupleTag::facet_type () const
Definition at line 18 of file TupleTag.cpp.
References m_facet_tag_acc.
Referenced by initialize(), and run().
get_boundary_tag()
int64_t wmtk::multimesh::utils::internal::TupleTag::get_boundary_tag (const Tuple & tuple) const
Definition at line 138 of file TupleTag.cpp.
References m_boundary_tag_acc.
Referenced by boundary_get_root(), boundary_is_root(), and boundary_set_root().
get_facet_tag()
int64_t wmtk::multimesh::utils::internal::TupleTag::get_facet_tag (const Tuple & tuple) const
Definition at line 142 of file TupleTag.cpp.
References m_facet_tag_acc.
initialize()
void wmtk::multimesh::utils::internal::TupleTag::initialize ()
Go through facets of the parent mesh (triangle mesh) and initialize all the boundary tags to be -1.
Definition at line 27 of file TupleTag.cpp.
References boundary_type(), facet_type(), wmtk::Mesh::get_all(), wmtk::Mesh::is_boundary(), mesh(), set_boundary_tag(), set_facet_tag(), and vid().
Referenced by TupleTag().
is_critical_boundary()
bool wmtk::multimesh::utils::internal::TupleTag::is_critical_boundary (const Tuple & v) const
Check if a boundary is a critical point.
Parameters
critical_boundaries
v The boundary tuple
Returns
true if v is a critical point
false if v is not a critival point
Definition at line 133 of file TupleTag.cpp.
References m_critical_boundaries, and vid().
Referenced by boundary_sets_unify(), run(), and run().
mesh() [1/2]
Mesh & wmtk::multimesh::utils::internal::TupleTag::mesh () inline
Definition at line 25 of file TupleTag.hpp.
References m_mesh.
mesh() [2/2]
const Mesh & wmtk::multimesh::utils::internal::TupleTag::mesh () const inline
Definition at line 24 of file TupleTag.hpp.
References m_mesh.
Referenced by initialize(), run(), run(), v_tuple(), and vid().
run() [1/2]
std::set< int64_t > wmtk::multimesh::utils::internal::TupleTag::run ()
Definition at line 45 of file TupleTag.cpp.
References boundary_get_root(), boundary_type(), wmtk::Mesh::capacity(), wmtk::simplex::faces_single_dimension_tuples(), facet_type(), wmtk::Mesh::get_all(), wmtk::Mesh::is_boundary(), is_critical_boundary(), mesh(), run(), set_facet_tag(), and wmtk::Mesh::switch_tuple().
Referenced by wmtk::multimesh::utils::create_tags(), and run().
run() [2/2]
void wmtk::multimesh::utils::internal::TupleTag::run (const Tuple & e)
Given an facet, join the sets that contains the two end vertices.
Parameters
critical_vids The sets of vertices that are the intersections of facets belong to different sets (for example T junction vertices for an facet mesh)
e
Definition at line 211 of file TupleTag.cpp.
References boundary_sets_unify(), boundary_type(), is_critical_boundary(), mesh(), wmtk::Mesh::switch_tuple(), and vid().
set_boundary_tag()
void wmtk::multimesh::utils::internal::TupleTag::set_boundary_tag (const Tuple & tuple, int64_t tag)
Definition at line 147 of file TupleTag.cpp.
References m_boundary_tag_acc.
Referenced by boundary_set_root(), and initialize().
set_facet_tag()
void wmtk::multimesh::utils::internal::TupleTag::set_facet_tag (const Tuple & tuple, int64_t tag)
Definition at line 152 of file TupleTag.cpp.
References m_facet_tag_acc.
Referenced by initialize(), and run().
v_tuple()
Tuple wmtk::multimesh::utils::internal::TupleTag::v_tuple (int64_t vid) const
Definition at line 162 of file TupleTag.cpp.
References boundary_type(), mesh(), wmtk::Mesh::tuple_from_id(), v_tuple(), and vid().
Referenced by boundary_get_root(), boundary_set_root(), and v_tuple().
vid()
int64_t wmtk::multimesh::utils::internal::TupleTag::vid (const Tuple & tuple) const
Definition at line 157 of file TupleTag.cpp.
References boundary_type(), wmtk::Mesh::id(), and mesh().
Referenced by boundary_is_root(), initialize(), is_critical_boundary(), run(), and v_tuple().
Member Data Documentation
m_boundary_tag_acc
wmtk::attribute::Accessor<int64_t, Mesh, wmtk::attribute::CachingAttribute<int64_t>, 1> wmtk::multimesh::utils::internal::TupleTag::m_boundary_tag_acc
Definition at line 71 of file TupleTag.hpp.
Referenced by boundary_type(), get_boundary_tag(), and set_boundary_tag().
m_critical_boundaries
std::set<int64_t> wmtk::multimesh::utils::internal::TupleTag::m_critical_boundaries
Definition at line 70 of file TupleTag.hpp.
Referenced by is_critical_boundary().
m_facet_tag_acc
wmtk::attribute::Accessor<int64_t, Mesh, wmtk::attribute::CachingAttribute<int64_t>, 1> wmtk::multimesh::utils::internal::TupleTag::m_facet_tag_acc
Definition at line 72 of file TupleTag.hpp.
Referenced by facet_type(), get_facet_tag(), and set_facet_tag().
m_mesh
Mesh& wmtk::multimesh::utils::internal::TupleTag::m_mesh
Definition at line 69 of file TupleTag.hpp.
Referenced by mesh(), and mesh().
The documentation for this class was generated from the following files:
src/wmtk/multimesh/utils/internal/TupleTag.hpp
src/wmtk/multimesh/utils/extract_child_mesh_from_tag.cpp
src/wmtk/multimesh/utils/internal/TupleTag.cpp