Wildmeshing Toolkit: wmtk::dart::DartIndexAccessor< Dim, MeshType > Class Template Reference
wmtk::dart::DartIndexAccessor< Dim, MeshType > Class Template Reference
#include <DartAccessor.hpp>
Public Types
using BaseAccessor = wmtk::attribute::Accessor< int64_t, MeshType, attribute::CachingAttribute< int64_t >, Dim+1 >
Public Member Functions
DartIndexAccessor (BaseAccessor acc)
DartIndexAccessor (const MeshType &mesh, const wmtk::attribute::MeshAttributeHandle &mah)
DartIndexAccessor (const MeshType &mesh, const wmtk::attribute::TypedAttributeHandle< int64_t > &h)
template<typename MeshType2 >
DartIndexAccessor (const DartIndexAccessor< Dim, MeshType2 > &o)
wmtk::attribute::MeshAttributeHandle handle () const
dart::SimplexAdjacency< Dim > & operator[] (int64_t index)
const dart::SimplexAdjacency< Dim > & operator[] (int64_t index) const
const MeshType & mesh () const
size_t size () const
Protected Attributes
BaseAccessor m_base_accessor
Detailed Description
template<int Dim, typename MeshType>
class wmtk::dart::DartIndexAccessor< Dim, MeshType >
Definition at line 23 of file DartAccessor.hpp.
Member Typedef Documentation
BaseAccessor
template<int Dim, typename MeshType > using wmtk::dart::DartIndexAccessor< Dim, MeshType >::BaseAccessor = wmtk::attribute::Accessor<int64_t, MeshType, attribute::CachingAttribute<int64_t>, Dim + 1>
Definition at line 27 of file DartAccessor.hpp.
Constructor & Destructor Documentation
DartIndexAccessor() [1/4]
template<int Dim, typename MeshType > wmtk::dart::DartIndexAccessor< Dim, MeshType >::DartIndexAccessor (BaseAccessor acc) inline
Definition at line 30 of file DartAccessor.hpp.
DartIndexAccessor() [2/4]
template<int Dim, typename MeshType > wmtk::dart::DartIndexAccessor< Dim, MeshType >::DartIndexAccessor (const MeshType & mesh, const wmtk::attribute::MeshAttributeHandle & mah) inline
Definition at line 34 of file DartAccessor.hpp.
DartIndexAccessor() [3/4]
template<int Dim, typename MeshType > wmtk::dart::DartIndexAccessor< Dim, MeshType >::DartIndexAccessor (const MeshType & mesh, const wmtk::attribute::TypedAttributeHandle< int64_t > & h) inline
Definition at line 37 of file DartAccessor.hpp.
DartIndexAccessor() [4/4]
template<int Dim, typename MeshType > template<typename MeshType2 > wmtk::dart::DartIndexAccessor< Dim, MeshType >::DartIndexAccessor (const DartIndexAccessor< Dim, MeshType2 > & o) inline
Definition at line 41 of file DartAccessor.hpp.
Member Function Documentation
handle()
template<int Dim, typename MeshType > wmtk::attribute::MeshAttributeHandle wmtk::dart::DartIndexAccessor< Dim, MeshType >::handle () const inline
Definition at line 45 of file DartAccessor.hpp.
References wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::handle(), and wmtk::dart::DartIndexAccessor< Dim, MeshType >::m_base_accessor.
mesh()
template<int Dim, typename MeshType > const MeshType & wmtk::dart::DartIndexAccessor< Dim, MeshType >::mesh () const inline
Definition at line 58 of file DartAccessor.hpp.
References wmtk::dart::DartIndexAccessor< Dim, MeshType >::m_base_accessor, and wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::mesh().
operator[]() [1/2]
template<int Dim, typename MeshType > dart::SimplexAdjacency< Dim > & wmtk::dart::DartIndexAccessor< Dim, MeshType >::operator[] (int64_t index) inline
Definition at line 47 of file DartAccessor.hpp.
References wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::attribute(), and wmtk::dart::DartIndexAccessor< Dim, MeshType >::m_base_accessor.
Referenced by wmtk::dart::DartAccessor< Dim, MeshType >::operator[](), and wmtk::dart::DartAccessor< Dim, MeshType >::operator[]().
operator[]() [2/2]
template<int Dim, typename MeshType > const dart::SimplexAdjacency< Dim > & wmtk::dart::DartIndexAccessor< Dim, MeshType >::operator[] (int64_t index) const inline
Definition at line 52 of file DartAccessor.hpp.
References wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::attribute(), and wmtk::dart::DartIndexAccessor< Dim, MeshType >::m_base_accessor.
size()
template<int Dim, typename MeshType > size_t wmtk::dart::DartIndexAccessor< Dim, MeshType >::size () const inline
Definition at line 60 of file DartAccessor.hpp.
References wmtk::dart::DartIndexAccessor< Dim, MeshType >::m_base_accessor, and wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::reserved_size().
Member Data Documentation
m_base_accessor
template<int Dim, typename MeshType > BaseAccessor wmtk::dart::DartIndexAccessor< Dim, MeshType >::m_base_accessor protected
Definition at line 64 of file DartAccessor.hpp.
Referenced by wmtk::dart::DartIndexAccessor< Dim, MeshType >::handle(), wmtk::dart::DartIndexAccessor< Dim, MeshType >::mesh(), wmtk::dart::DartIndexAccessor< Dim, MeshType >::operator[](), wmtk::dart::DartIndexAccessor< Dim, MeshType >::operator[](), and wmtk::dart::DartIndexAccessor< Dim, MeshType >::size().
The documentation for this class was generated from the following files:
src/wmtk/attribute/Accessor.hpp
src/wmtk/dart/DartAccessor.hpp