Wildmeshing Toolkit: wmtk::components::multimesh::NamedMultiMesh Class Reference
wmtk::components::multimesh::NamedMultiMesh Class Reference
#include <NamedMultiMesh.hpp>
Classes
struct Node
Public Member Functions
NamedMultiMesh ()
NamedMultiMesh (Mesh &m, const std::string_view &root_name, bool do_populate_child_names=true)
NamedMultiMesh (Mesh &m, const nlohmann::ordered_json &root_name, bool do_populate_missing_names=true)
NamedMultiMesh (Mesh &m, const std::string &root_name, bool do_populate_child_names=true)
template<size_t N>
NamedMultiMesh (Mesh &m, const char name[N])
NamedMultiMesh (const NamedMultiMesh &)
~NamedMultiMesh ()
auto operator= (const NamedMultiMesh &) -> NamedMultiMesh &
operator bool () const
void set_name (const std::string_view &root_name="")
sets just the name of the root mesh, keeping child names the same
void set_names (const nlohmann::ordered_json &js)
void populate_default_names ()
void set_root (Mesh &m, bool do_populate_unnamed=true)
void append_child_mesh_names (const Mesh &parent, const NamedMultiMesh &child_mesh)
void set_name (const Mesh &m, const std::string_view &name)
std::unique_ptr< nlohmann::ordered_json > get_names_json (const std::string_view &path="") const
std::string_view root_name () const
std::string name (const std::vector< int64_t > &id) const
std::string get_name (const std::vector< int64_t > &id) const
bool has_name (const std::vector< int64_t > &id) const
void set_mesh (Mesh &m, bool do_populate_unnamed=true)
Navigates to the root of the multimesh.
Mesh & get_mesh (const std::string_view &path) const
bool has_mesh (const std::string_view &path) const
std::vector< int64_t > get_id (const std::string_view &path) const
std::vector< int64_t > get_id (const Mesh &m) const
Mesh & root ()
const Mesh & root () const
std::map< std::string, const Mesh & > all_meshes () const
std::map< std::string, Mesh & > all_meshes ()
std::string get_name (const Mesh &m) const
bool has_name (const Mesh &m) const
std::string get_path (const wmtk::attribute::MeshAttributeHandle &m) const
bool is_valid (bool pass_exceptions=false) const
Private Member Functions
const Node & get_node (const std::vector< int64_t > &id) const
Node & get_node (const std::vector< int64_t > &id)
Private Attributes
std::shared_ptr< Mesh > m_root
std::unique_ptr< Node > m_name_root
Detailed Description
Definition at line 20 of file NamedMultiMesh.hpp.
Constructor & Destructor Documentation
NamedMultiMesh() [1/6]
wmtk::components::multimesh::NamedMultiMesh::NamedMultiMesh ()
Definition at line 387 of file NamedMultiMesh.cpp.
NamedMultiMesh() [2/6]
wmtk::components::multimesh::NamedMultiMesh::NamedMultiMesh (Mesh & m, const std::string_view & root_name, bool do_populate_child_names = true)
Definition at line 161 of file NamedMultiMesh.cpp.
References root_name(), set_mesh(), and set_name().
NamedMultiMesh() [3/6]
wmtk::components::multimesh::NamedMultiMesh::NamedMultiMesh (Mesh & m, const nlohmann::ordered_json & root_name, bool do_populate_missing_names = true) explicit
Definition at line 166 of file NamedMultiMesh.cpp.
References root_name(), set_mesh(), and set_names().
NamedMultiMesh() [4/6]
wmtk::components::multimesh::NamedMultiMesh::NamedMultiMesh (Mesh & m, const std::string & root_name, bool do_populate_child_names = true) explicit
Definition at line 156 of file NamedMultiMesh.cpp.
References root_name(), set_mesh(), and set_name().
NamedMultiMesh() [5/6]
template<size_t N> wmtk::components::multimesh::NamedMultiMesh::NamedMultiMesh (Mesh & m, const char name[N]) inline explicit
Definition at line 36 of file NamedMultiMesh.hpp.
NamedMultiMesh() [6/6]
wmtk::components::multimesh::NamedMultiMesh::NamedMultiMesh (const NamedMultiMesh & o)
Definition at line 399 of file NamedMultiMesh.cpp.
~NamedMultiMesh()
wmtk::components::multimesh::NamedMultiMesh::~NamedMultiMesh () default
Member Function Documentation
all_meshes() [1/2]
std::map< std::string, Mesh & > wmtk::components::multimesh::NamedMultiMesh::all_meshes ()
Definition at line 416 of file NamedMultiMesh.cpp.
References get_name(), and m_root.
all_meshes() [2/2]
std::map< std::string, const Mesh & > wmtk::components::multimesh::NamedMultiMesh::all_meshes () const
Definition at line 425 of file NamedMultiMesh.cpp.
References get_name(), and m_root.
append_child_mesh_names()
void wmtk::components::multimesh::NamedMultiMesh::append_child_mesh_names (const Mesh & parent, const NamedMultiMesh & child_mesh)
Definition at line 458 of file NamedMultiMesh.cpp.
References wmtk::Mesh::absolute_multi_mesh_id(), get_id(), wmtk::Mesh::get_multi_mesh_parent_mesh(), get_names_json(), wmtk::logger(), wmtk::components::multimesh::NamedMultiMesh::Node::m_children, m_name_root, populate_default_names(), wmtk::multimesh::MultiMeshManager::relative_id(), root(), and wmtk::components::multimesh::NamedMultiMesh::Node::update_child_names().
Referenced by wmtk::components::multimesh::MultimeshAxisAlignedFusionOptions::run().
get_id() [1/2]
std::vector< int64_t > wmtk::components::multimesh::NamedMultiMesh::get_id (const Mesh & m) const
Definition at line 264 of file NamedMultiMesh.cpp.
References wmtk::Mesh::absolute_multi_mesh_id(), m_root, and wmtk::multimesh::MultiMeshManager::relative_id().
get_id() [2/2]
auto wmtk::components::multimesh::NamedMultiMesh::get_id (const std::string_view & path) const
Definition at line 213 of file NamedMultiMesh.cpp.
References wmtk::logger(), wmtk::components::multimesh::NamedMultiMesh::Node::m_child_indexer, wmtk::components::multimesh::NamedMultiMesh::Node::m_children, wmtk::components::multimesh::NamedMultiMesh::Node::name, and wmtk::components::multimesh::internal::split_path().
Referenced by append_child_mesh_names(), get_mesh(), get_name(), get_names_json(), has_name(), is_valid(), set_name(), TEST_CASE(), and TEST_CASE().
get_mesh()
Mesh & wmtk::components::multimesh::NamedMultiMesh::get_mesh (const std::string_view & path) const
Definition at line 187 of file NamedMultiMesh.cpp.
References get_id(), and m_root.
Referenced by wmtk::components::multimesh::utils::create_attribute(), wmtk::components::multimesh::utils::get_attribute(), wmtk::components::multimesh::utils::get_attributes(), wmtk::components::multimesh::MeshCollection::get_mesh(), wmtk::components::multimesh::MeshCollection::get_mesh(), is_valid(), wmtk::components::output::output(), and TEST_CASE().
get_name() [1/2]
std::string wmtk::components::multimesh::NamedMultiMesh::get_name (const Mesh & m) const
Definition at line 434 of file NamedMultiMesh.cpp.
References get_id(), and m_name_root.
get_name() [2/2]
std::string wmtk::components::multimesh::NamedMultiMesh::get_name (const std::vector< int64_t > & id) const
Definition at line 358 of file NamedMultiMesh.cpp.
References wmtk::components::multimesh::NamedMultiMesh::Node::m_children, m_name_root, wmtk::components::multimesh::NamedMultiMesh::Node::name, and root_name().
Referenced by all_meshes(), all_meshes(), wmtk::components::multimesh::utils::get_attribute_handle(), get_path(), wmtk::components::input::input(), is_valid(), and name().
get_names_json()
std::unique_ptr< nlohmann::ordered_json > wmtk::components::multimesh::NamedMultiMesh::get_names_json (const std::string_view & path = "") const
Definition at line 405 of file NamedMultiMesh.cpp.
References get_id(), and get_node().
Referenced by append_child_mesh_names(), wmtk::components::output::output(), and TEST_CASE().
get_node() [1/2]
auto wmtk::components::multimesh::NamedMultiMesh::get_node (const std::vector< int64_t > & id) private
Definition at line 378 of file NamedMultiMesh.cpp.
References wmtk::components::multimesh::NamedMultiMesh::Node::m_children.
get_node() [2/2]
auto wmtk::components::multimesh::NamedMultiMesh::get_node (const std::vector< int64_t > & id) const private
Definition at line 370 of file NamedMultiMesh.cpp.
References wmtk::components::multimesh::NamedMultiMesh::Node::m_children.
Referenced by get_names_json().
get_path()
std::string wmtk::components::multimesh::NamedMultiMesh::get_path (const wmtk::attribute::MeshAttributeHandle & m) const
Definition at line 453 of file NamedMultiMesh.cpp.
References get_name(), wmtk::attribute::MeshAttributeHandle::mesh(), and wmtk::attribute::MeshAttributeHandle::name().
has_mesh()
bool wmtk::components::multimesh::NamedMultiMesh::has_mesh (const std::string_view & path) const
Definition at line 192 of file NamedMultiMesh.cpp.
References wmtk::components::multimesh::NamedMultiMesh::Node::m_child_indexer, wmtk::components::multimesh::NamedMultiMesh::Node::m_children, m_name_root, wmtk::components::multimesh::NamedMultiMesh::Node::name, and wmtk::components::multimesh::internal::split_path().
has_name() [1/2]
bool wmtk::components::multimesh::NamedMultiMesh::has_name (const Mesh & m) const
Definition at line 443 of file NamedMultiMesh.cpp.
References get_id(), and has_name().
has_name() [2/2]
bool wmtk::components::multimesh::NamedMultiMesh::has_name (const std::vector< int64_t > & id) const
Definition at line 448 of file NamedMultiMesh.cpp.
References m_name_root.
Referenced by has_name(), and wmtk::components::input::input().
is_valid()
bool wmtk::components::multimesh::NamedMultiMesh::is_valid (bool pass_exceptions = false) const
Definition at line 486 of file NamedMultiMesh.cpp.
References get_id(), get_mesh(), get_name(), wmtk::logger(), m_name_root, and m_root.
name()
std::string wmtk::components::multimesh::NamedMultiMesh::name (const std::vector< int64_t > & id) const
Definition at line 354 of file NamedMultiMesh.cpp.
References get_name().
Referenced by set_name().
operator bool()
wmtk::components::multimesh::NamedMultiMesh::operator bool () const inline
Definition at line 45 of file NamedMultiMesh.hpp.
References m_root.
operator=()
auto wmtk::components::multimesh::NamedMultiMesh::operator= (const NamedMultiMesh & o) -> NamedMultiMesh&
Definition at line 393 of file NamedMultiMesh.cpp.
References m_root, and m_root.
populate_default_names()
void wmtk::components::multimesh::NamedMultiMesh::populate_default_names ()
Definition at line 312 of file NamedMultiMesh.cpp.
References wmtk::Mesh::get_child_meshes(), wmtk::components::multimesh::NamedMultiMesh::Node::m_children, m_name_root, m_root, and wmtk::components::multimesh::NamedMultiMesh::Node::update_child_names().
Referenced by append_child_mesh_names(), set_name(), and set_root().
root() [1/2]
Mesh & wmtk::components::multimesh::NamedMultiMesh::root () inline
Definition at line 73 of file NamedMultiMesh.hpp.
References m_root.
Referenced by append_child_mesh_names(), wmtk::components::input::input(), and TEST_CASE().
root() [2/2]
const Mesh & wmtk::components::multimesh::NamedMultiMesh::root () const inline
Definition at line 74 of file NamedMultiMesh.hpp.
References m_root.
root_name()
std::string_view wmtk::components::multimesh::NamedMultiMesh::root_name () const
Definition at line 346 of file NamedMultiMesh.cpp.
References m_name_root.
Referenced by get_name(), NamedMultiMesh(), NamedMultiMesh(), NamedMultiMesh(), wmtk::components::output::output(), and set_name().
set_mesh()
void wmtk::components::multimesh::NamedMultiMesh::set_mesh (Mesh & m, bool do_populate_unnamed = true)
Navigates to the root of the multimesh.
Definition at line 180 of file NamedMultiMesh.cpp.
References set_root().
Referenced by wmtk::components::input::input(), NamedMultiMesh(), NamedMultiMesh(), NamedMultiMesh(), TEST_CASE(), and TEST_CASE().
set_name() [1/2]
void wmtk::components::multimesh::NamedMultiMesh::set_name (const Mesh & m, const std::string_view & name)
Definition at line 276 of file NamedMultiMesh.cpp.
References get_id(), wmtk::components::multimesh::NamedMultiMesh::Node::m_child_indexer, wmtk::components::multimesh::NamedMultiMesh::Node::m_children, m_name_root, wmtk::components::multimesh::NamedMultiMesh::Node::name, name(), and populate_default_names().
set_name() [2/2]
void wmtk::components::multimesh::NamedMultiMesh::set_name (const std::string_view & root_name = "")
sets just the name of the root mesh, keeping child names the same
Definition at line 272 of file NamedMultiMesh.cpp.
References root_name(), and set_names().
Referenced by NamedMultiMesh(), NamedMultiMesh(), wmtk::components::multimesh::MultimeshTagOptions::run(), and TEST_CASE().
set_names()
void wmtk::components::multimesh::NamedMultiMesh::set_names (const nlohmann::ordered_json & js)
Definition at line 293 of file NamedMultiMesh.cpp.
References m_name_root.
Referenced by wmtk::components::input::input(), NamedMultiMesh(), set_name(), TEST_CASE(), and TEST_CASE().
set_root()
void wmtk::components::multimesh::NamedMultiMesh::set_root (Mesh & m, bool do_populate_unnamed = true)
Definition at line 172 of file NamedMultiMesh.cpp.
References m_root, and populate_default_names().
Referenced by set_mesh().
Member Data Documentation
m_name_root
std::unique_ptr<Node> wmtk::components::multimesh::NamedMultiMesh::m_name_root private
Definition at line 98 of file NamedMultiMesh.hpp.
Referenced by append_child_mesh_names(), get_name(), get_name(), has_mesh(), has_name(), is_valid(), populate_default_names(), root_name(), set_name(), and set_names().
m_root
std::shared_ptr<Mesh> wmtk::components::multimesh::NamedMultiMesh::m_root private
Definition at line 97 of file NamedMultiMesh.hpp.
Referenced by all_meshes(), all_meshes(), get_id(), get_mesh(), is_valid(), operator bool(), operator=(), populate_default_names(), root(), root(), and set_root().
The documentation for this class was generated from the following files:
components/multimesh/src/wmtk/components/multimesh/NamedMultiMesh.hpp
components/multimesh/src/wmtk/components/multimesh/NamedMultiMesh.cpp