Wildmeshing Toolkit: wmtk::multimesh::MultiMeshManager Class Reference
wmtk::multimesh::MultiMeshManager Class Reference
Implementation details for how the Mesh class implements multiple meshes.
#include <MultiMeshManager.hpp>
Classes
struct ChildData
Public Types
using AccessorType = wmtk::dart::DartAccessor< 1, Mesh >
Public Member Functions
MultiMeshManager (int64_t dimension)
~MultiMeshManager ()
MultiMeshManager (const MultiMeshManager &o)
MultiMeshManager (MultiMeshManager &&o)
MultiMeshManager & operator= (const MultiMeshManager &o)
MultiMeshManager & operator= (MultiMeshManager &&o)
std::map< std::string, const wmtk::utils::Hashable * > child_hashables () const override
std::map< std::string, std::size_t > child_hashes () const override
void detach_children ()
std::vector< TypedAttributeHandle< int64_t > > map_handles () const
bool is_root () const
Specifies whether this structure is the root of a multi-mesh tree.
int64_t child_id () const
Specifies the child id of this mesh if it a child mesh in a mult-mesh tree.
std::vector< int64_t > absolute_id () const
Mesh & get_mesh (Mesh &m, const std::vector< int64_t > &absolute_id)
const Mesh & get_mesh (const Mesh &m, const std::vector< int64_t > &absolute_id) const
Mesh & get_child_mesh (Mesh &m, const std::vector< int64_t > &relative_id)
const Mesh & get_child_mesh (const Mesh &m, const std::vector< int64_t > &relative_id) const
void register_child_mesh (Mesh &my_mesh, const std::shared_ptr< Mesh > &child_mesh, const std::vector< std::array< Tuple, 2 > > &child_tuple_my_tuple_map)
register a another mesh as a child of this mesh.
void deregister_child_mesh (Mesh &my_mesh, Mesh &child_mesh)
Deregister a child mesh.
void update_child_handles (Mesh &my_mesh)
Clean up child data after deleting attributes.
std::vector< simplex::Simplex > map (const Mesh &my_mesh, const Mesh &other_mesh, const simplex::Simplex &my_simplex) const
maps a simplex from this mesh to any other mesh
std::vector< Tuple > lub_map_tuples (const Mesh &my_mesh, const Mesh &other_mesh, const simplex::Simplex &my_simplex) const
maps a simplex from this mesh to any other mesh using the LUB as the root
std::vector< simplex::Simplex > lub_map (const Mesh &my_mesh, const Mesh &other_mesh, const simplex::Simplex &my_simplex) const
maps a simplex from this mesh to any other mesh using the LUB as the root
std::vector< Tuple > map_tuples (const Mesh &my_mesh, const Mesh &other_mesh, const simplex::Simplex &my_simplex) const
maps a simplex from this mesh to any other mesh
simplex::Simplex map_to_parent (const Mesh &my_mesh, const simplex::Simplex &my_simplex) const
optimized map from a simplex from this mesh to its direct parent
Tuple map_to_parent_tuple (const Mesh &my_mesh, const simplex::Simplex &my_simplex) const
optimized map from a simplex from this mesh to its direct parent
simplex::Simplex map_to_root (const Mesh &my_mesh, const simplex::Simplex &my_simplex) const
maps a simplex from this mesh to the root mesh
Tuple map_to_root_tuple (const Mesh &my_mesh, const simplex::Simplex &my_simplex) const
maps a simplex from this mesh to the root mesh
std::vector< simplex::Simplex > map_to_child (const Mesh &my_mesh, const Mesh &child_mesh, const simplex::Simplex &my_simplex) const
optimized map fromsimplex from this mesh to one of its direct children
std::vector< Tuple > map_to_child_tuples (const Mesh &my_mesh, const Mesh &child_mesh, const simplex::Simplex &my_simplex) const
bool can_map (const Mesh &my_mesh, const Mesh &other_mesh, const simplex::Simplex &my_simplex) const
bool can_map_child (const Mesh &my_mesh, const Mesh &other_mesh, const simplex::Simplex &my_simplex) const
bool can_map_up (const Mesh &my_mesh, const Mesh &other_mesh) const
bool can_map_to_child (const Mesh &my_mesh, const simplex::Simplex &s) const
bool can_map_to_parent (const Mesh &my_mesh, const simplex::Simplex &s) const
const Mesh & get_root_mesh (const Mesh &my_mesh) const
Mesh & get_root_mesh (Mesh &my_mesh)
Mesh & get_parent_mesh (Mesh &my_mesh)
const Mesh & get_parent_mesh (const Mesh &my_mesh) const
std::vector< std::shared_ptr< Mesh > > get_child_meshes () const
void serialize (io::MeshWriter &writer, const Mesh *local_root=nullptr) const
bool has_child_mesh_in_dimension (int64_t dimension) const
bool has_child_mesh () const
std::vector< int64_t > relative_id (const Mesh &my_mesh, const Mesh &parent_mesh) const
bool is_child (const Mesh &my_mesh, const Mesh &parent_mesh) const
Public Member Functions inherited from wmtk::utils::Hashable
Hashable ()
Hashable (const Hashable &)
Hashable (Hashable &&)
Hashable & operator= (const Hashable &)
Hashable & operator= (Hashable &&)
virtual ~Hashable ()
virtual std::size_t hash () const
Static Public Member Functions
static std::vector< int64_t > least_upper_bound_id (const std::vector< int64_t > &a, const std::vector< int64_t > &b)
static std::vector< int64_t > relative_id (const std::vector< int64_t > &parent, const std::vector< int64_t > &child)
static bool is_child (const std::vector< int64_t > &child, const std::vector< int64_t > &parent)
static std::vector< std::array< Tuple, 2 > > same_simplex_dimension_surjection (const Mesh &parent, const Mesh &child, const std::vector< int64_t > &parent_simplices)
Protected Member Functions
Tuple map_tuple_to_parent_tuple (const Mesh &my_mesh, const Tuple &my_tuple) const
Tuple map_tuple_to_root_tuple (const Mesh &my_mesh, const Tuple &my_tuple) const
std::vector< Tuple > map_to_child_tuples (const Mesh &my_mesh, const ChildData &child_data, const simplex::Simplex &simplex) const
std::vector< Tuple > map_to_child_tuples (const Mesh &my_mesh, int64_t child_id, const simplex::Simplex &simplex) const
const std::vector< ChildData > & children () const
std::vector< ChildData > & children ()
std::array< AccessorType, 2 > get_map_accessors (Mesh &my_mesh, ChildData &c)
std::array< const AccessorType, 2 > get_map_const_accessors (const Mesh &my_mesh, const ChildData &c) const
std::array< AccessorType, 2 > get_map_accessors (Mesh &my_mesh, Mesh &c)
std::array< const AccessorType, 2 > get_map_const_accessors (const Mesh &my_mesh, const Mesh &c) const
void update_maps_from_edge_operation (Mesh &my_mesh, PrimitiveType primitive_type, const operations::EdgeOperationData &operation_data)
void update_maps_from_edge_operation (Mesh &my_mesh, const operations::EdgeOperationData &operation_data)
std::optional< Tuple > find_valid_tuple (Mesh &my_mesh, const simplex::Simplex &old_simplex, const int64_t old_gid, const std::vector< Tuple > &tuple_alternatives, const std::vector< std::tuple< int64_t, std::array< int64_t, 2 > > > &split_cell_maps={}) const
std::optional< Tuple > find_valid_tuple_from_alternatives (Mesh &my_mesh, PrimitiveType primitive_type, const std::vector< Tuple > &tuple_alternatives) const
std::optional< Tuple > find_valid_tuple_from_split (Mesh &my_mesh, const simplex::Simplex &old_simplex, const int64_t old_gid, const std::vector< Tuple > &tuple_alternatives, const std::vector< std::tuple< int64_t, std::array< int64_t, 2 > > > &split_cell_maps) const
std::optional< Tuple > try_updating_map_tuple_from_split (Mesh &my_mesh, const simplex::Simplex &old_simplex, const int64_t old_gid, const std::vector< Tuple > &tuple_alternatives, const std::tuple< int64_t, std::array< int64_t, 2 > > &split_cell_maps) const
std::tuple< Tuple, Tuple > mapped_tuples (const Mesh &my_mesh, const Mesh &child_mesh, int64_t index) const
std::tuple< dart::Dart, dart::Dart > mapped_darts (const Mesh &my_mesh, const Mesh &child_mesh, int64_t index) const
std::pair< const Mesh &, Tuple > map_up_to_tuples (const Mesh &my_mesh, const simplex::Simplex &simplex, int64_t depth) const
std::pair< const Mesh &, Tuple > map_up_to_tuples (const Mesh &my_mesh, const Tuple &tuple, int64_t depth) const
std::pair< const Mesh &, Tuple > map_up_to_tuples (const Mesh &my_mesh, const Mesh &other, const Tuple &tuple) const
std::vector< Tuple > map_down_relative_tuples (const Mesh &my_mesh, const simplex::Simplex &my_simplex, const std::vector< int64_t > &local_id_path) const
Static Protected Member Functions
static Tuple map_tuple_between_meshes (const AccessorType &source_to_target_map_accessor, const AccessorType &target_to_source_map_accessor, const Tuple &source_tuple)
static std::string parent_to_child_map_attribute_name (int64_t index)
static std::string child_to_parent_map_attribute_name ()
static std::optional< Tuple > find_tuple_from_gid (const Mesh &my_mesh, PrimitiveType primitive_type, const std::vector< Tuple > &tuples, int64_t gid)
static int64_t child_global_cid (const AccessorType &parent_to_child, int64_t parent_gid)
static int64_t parent_global_cid (const AccessorType &child_to_parent, int64_t child_gid)
static int64_t parent_local_fid (const AccessorType &child_to_parent, int64_t child_gid)
Protected Attributes
Mesh * m_parent = nullptr
TypedAttributeHandle< int64_t > map_to_parent_handle
int64_t m_child_id = -1
std::vector< ChildData > m_children
std::vector< bool > m_has_child_mesh_in_dimension
Friends
template<int64_t cell_dimension, typename NodeFunctor >
class multimesh::MultiMeshSimplexVisitor
class wmtk::Mesh
template<typename Visitor >
class multimesh::MultiMeshSimplexVisitorExecutor
class operations::utils::UpdateEdgeOperationMultiMeshMapFunctor
template<typename NodeFunctor >
class multimesh::MultiMeshVisitor
template<typename Visitor >
class multimesh::MultiMeshVisitorExecutor
class wmtk::HDF5Reader
class utils::MapValidator
Detailed Description
Implementation details for how the Mesh class implements multiple meshes.
Definition at line 48 of file MultiMeshManager.hpp.
Member Typedef Documentation
AccessorType
using wmtk::multimesh::MultiMeshManager::AccessorType = wmtk::dart::DartAccessor<1, Mesh>
Definition at line 51 of file MultiMeshManager.hpp.
Constructor & Destructor Documentation
MultiMeshManager() [1/3]
wmtk::multimesh::MultiMeshManager::MultiMeshManager (int64_t dimension)
Definition at line 119 of file MultiMeshManager.cpp.
~MultiMeshManager()
wmtk::multimesh::MultiMeshManager::~MultiMeshManager () default
MultiMeshManager() [2/3]
wmtk::multimesh::MultiMeshManager::MultiMeshManager (const MultiMeshManager & o) default
MultiMeshManager() [3/3]
wmtk::multimesh::MultiMeshManager::MultiMeshManager (MultiMeshManager && o) default
Member Function Documentation
absolute_id()
std::vector< int64_t > wmtk::multimesh::MultiMeshManager::absolute_id () const
Definition at line 179 of file MultiMeshManager.cpp.
References absolute_id(), is_root(), m_child_id, wmtk::Mesh::m_multi_mesh_manager, and m_parent.
Referenced by absolute_id(), wmtk::Mesh::absolute_multi_mesh_id(), can_map_child(), get_mesh(), get_mesh(), lub_map_tuples(), map_tuples(), register_child_mesh(), and wmtk::Mesh::serialize().
can_map()
bool wmtk::multimesh::MultiMeshManager::can_map (const Mesh & my_mesh, const Mesh & other_mesh, const simplex::Simplex & my_simplex) const
Definition at line 884 of file MultiMeshManager.cpp.
References wmtk::Mesh::get_multi_mesh_root(), map_to_root_tuple(), and wmtk::simplex::Simplex::primitive_type().
Referenced by wmtk::Mesh::can_map().
can_map_child()
bool wmtk::multimesh::MultiMeshManager::can_map_child (const Mesh & my_mesh, const Mesh & other_mesh, const simplex::Simplex & my_simplex) const
Definition at line 896 of file MultiMeshManager.cpp.
References absolute_id(), wmtk::Mesh::absolute_multi_mesh_id(), map_up_to_tuples(), wmtk::simplex::Simplex::primitive_type(), and wmtk::Mesh::top_simplex_type().
can_map_to_child()
bool wmtk::multimesh::MultiMeshManager::can_map_to_child (const Mesh & my_mesh, const simplex::Simplex & s) const
Definition at line 928 of file MultiMeshManager.cpp.
References wmtk::dart::SimplexDart::get_singleton(), wmtk::Mesh::id(), m_children, wmtk::simplex::Simplex::primitive_type(), wmtk::Mesh::top_simplex_type(), and wmtk::simplex::Simplex::tuple().
can_map_to_parent()
bool wmtk::multimesh::MultiMeshManager::can_map_to_parent (const Mesh & my_mesh, const simplex::Simplex & s) const
Definition at line 947 of file MultiMeshManager.cpp.
References m_parent.
can_map_up()
bool wmtk::multimesh::MultiMeshManager::can_map_up (const Mesh & my_mesh, const Mesh & other_mesh) const
Definition at line 916 of file MultiMeshManager.cpp.
References wmtk::Mesh::m_multi_mesh_manager, and m_parent.
Referenced by wmtk::Mesh::can_map_up_to(), and map_up_to_tuples().
child_global_cid()
int64_t wmtk::multimesh::MultiMeshManager::child_global_cid (const AccessorType & parent_to_child, int64_t parent_gid) static protected
Definition at line 229 of file MultiMeshManager_map_updates.cpp.
References wmtk::Mesh::get_index_access().
Referenced by wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::child_global_cid().
child_hashables()
std::map< std::string, const wmtk::utils::Hashable * > wmtk::multimesh::MultiMeshManager::child_hashables () const override virtual
Implements wmtk::utils::MerkleTreeInteriorNode.
Definition at line 130 of file MultiMeshManager.cpp.
References m_children.
child_hashes()
std::map< std::string, std::size_t > wmtk::multimesh::MultiMeshManager::child_hashes () const override virtual
Reimplemented from wmtk::utils::MerkleTreeInteriorNode.
Definition at line 141 of file MultiMeshManager.cpp.
References wmtk::Mesh::absolute_multi_mesh_id(), wmtk::utils::MerkleTreeInteriorNode::child_hashes(), m_child_id, m_children, m_parent, map_to_parent_handle, and wmtk::utils::vector_hash().
child_id()
int64_t wmtk::multimesh::MultiMeshManager::child_id () const
Specifies the child id of this mesh if it a child mesh in a mult-mesh tree.
throws if it not a child
Returns
the local index of this manager's mesh in its parent's array
Definition at line 171 of file MultiMeshManager.cpp.
References is_root(), and m_child_id.
Referenced by deregister_child_mesh(), map_to_child_tuples(), and map_to_child_tuples().
child_to_parent_map_attribute_name()
std::string wmtk::multimesh::MultiMeshManager::child_to_parent_map_attribute_name () static protected
Definition at line 819 of file MultiMeshManager.cpp.
Referenced by wmtk::HDF5Reader::read(), and register_child_mesh().
children() [1/2]
std::vector< ChildData > & wmtk::multimesh::MultiMeshManager::children () inline protected
Definition at line 417 of file MultiMeshManager.hpp.
References m_children.
children() [2/2]
const std::vector< ChildData > & wmtk::multimesh::MultiMeshManager::children () const inline protected
Definition at line 416 of file MultiMeshManager.hpp.
References m_children.
Referenced by deregister_child_mesh(), map_tuple_to_parent_tuple(), update_child_handles(), and update_maps_from_edge_operation().
deregister_child_mesh()
void wmtk::multimesh::MultiMeshManager::deregister_child_mesh (Mesh & my_mesh, Mesh & child_mesh)
Deregister a child mesh.
The child mesh is not deleted. It is only detached from the multi-mesh structure. The child mesh becomes the new root for its own children. Attribute handles for the child and parent mesh will be invalidated by deregistration.
Definition at line 282 of file MultiMeshManager.cpp.
References child_id(), children(), wmtk::attribute::AttributeManager::get(), wmtk::Mesh::m_attribute_manager, m_child_id, m_children, wmtk::Mesh::m_multi_mesh_manager, m_parent, wmtk::multimesh::MultiMeshManager::ChildData::map_handle, map_to_parent_handle, wmtk::multimesh::MultiMeshManager::ChildData::mesh, wmtk::Mesh::top_simplex_type(), and update_child_handles().
Referenced by wmtk::Mesh::deregister_child_mesh().
detach_children()
void wmtk::multimesh::MultiMeshManager::detach_children ()
Definition at line 30 of file MultiMeshManager.cpp.
References m_children.
Referenced by wmtk::Mesh::~Mesh().
find_tuple_from_gid()
static std::optional< Tuple > wmtk::multimesh::MultiMeshManager::find_tuple_from_gid (const Mesh & my_mesh, PrimitiveType primitive_type, const std::vector< Tuple > & tuples, int64_t gid) static protected
find_valid_tuple()
std::optional< Tuple > wmtk::multimesh::MultiMeshManager::find_valid_tuple (Mesh & my_mesh, const simplex::Simplex & old_simplex, const int64_t old_gid, const std::vector< Tuple > & tuple_alternatives, const std::vector< std::tuple< int64_t, std::array< int64_t, 2 > > > & split_cell_maps = {}) const protected
find_valid_tuple_from_alternatives()
std::optional< Tuple > wmtk::multimesh::MultiMeshManager::find_valid_tuple_from_alternatives (Mesh & my_mesh, PrimitiveType primitive_type, const std::vector< Tuple > & tuple_alternatives) const protected
find_valid_tuple_from_split()
std::optional< Tuple > wmtk::multimesh::MultiMeshManager::find_valid_tuple_from_split (Mesh & my_mesh, const simplex::Simplex & old_simplex, const int64_t old_gid, const std::vector< Tuple > & tuple_alternatives, const std::vector< std::tuple< int64_t, std::array< int64_t, 2 > > > & split_cell_maps) const protected
get_child_mesh() [1/2]
const Mesh & wmtk::multimesh::MultiMeshManager::get_child_mesh (const Mesh & m, const std::vector< int64_t > & relative_id) const
Definition at line 380 of file MultiMeshManager.cpp.
References m_child_id, m_children, wmtk::Mesh::m_multi_mesh_manager, wmtk::multimesh::MultiMeshManager::ChildData::mesh, and relative_id().
get_child_mesh() [2/2]
Mesh & wmtk::multimesh::MultiMeshManager::get_child_mesh (Mesh & m, const std::vector< int64_t > & relative_id)
Definition at line 401 of file MultiMeshManager.cpp.
References get_child_mesh(), and relative_id().
Referenced by get_child_mesh(), get_mesh(), get_mesh(), wmtk::Mesh::get_multi_mesh_child_mesh(), and wmtk::Mesh::get_multi_mesh_child_mesh().
get_child_meshes()
std::vector< std::shared_ptr< Mesh > > wmtk::multimesh::MultiMeshManager::get_child_meshes () const
Definition at line 417 of file MultiMeshManager.cpp.
References m_children.
Referenced by wmtk::Mesh::get_child_meshes().
get_map_accessors() [1/2]
auto wmtk::multimesh::MultiMeshManager::get_map_accessors (Mesh & my_mesh, ChildData & c) protected
Definition at line 778 of file MultiMeshManager.cpp.
References wmtk::Mesh::m_multi_mesh_manager, and map_to_parent_handle.
Referenced by wmtk::Mesh::consolidate(), wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator()(), wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator()(), wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator()(), wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator()(), wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator()(), wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator()(), wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::update_ear_replacement(), and update_maps_from_edge_operation().
get_map_accessors() [2/2]
auto wmtk::multimesh::MultiMeshManager::get_map_accessors (Mesh & my_mesh, Mesh & c) protected
Definition at line 801 of file MultiMeshManager.cpp.
get_map_const_accessors() [1/2]
auto wmtk::multimesh::MultiMeshManager::get_map_const_accessors (const Mesh & my_mesh, const ChildData & c) const protected
Definition at line 789 of file MultiMeshManager.cpp.
References wmtk::Mesh::m_multi_mesh_manager, and map_to_parent_handle.
Referenced by mapped_tuples(), and wmtk::multimesh::utils::MapValidator::print().
get_map_const_accessors() [2/2]
auto wmtk::multimesh::MultiMeshManager::get_map_const_accessors (const Mesh & my_mesh, const Mesh & c) const protected
Definition at line 810 of file MultiMeshManager.cpp.
get_mesh() [1/2]
const Mesh & wmtk::multimesh::MultiMeshManager::get_mesh (const Mesh & m, const std::vector< int64_t > & absolute_id) const
Definition at line 405 of file MultiMeshManager.cpp.
References absolute_id(), get_child_mesh(), get_root_mesh(), and wmtk::Mesh::m_multi_mesh_manager.
get_mesh() [2/2]
Mesh & wmtk::multimesh::MultiMeshManager::get_mesh (Mesh & m, const std::vector< int64_t > & absolute_id)
Definition at line 412 of file MultiMeshManager.cpp.
References absolute_id(), get_child_mesh(), get_root_mesh(), and wmtk::Mesh::m_multi_mesh_manager.
Referenced by wmtk::Mesh::get_multi_mesh_mesh(), and wmtk::Mesh::get_multi_mesh_mesh().
get_parent_mesh() [1/2]
const Mesh & wmtk::multimesh::MultiMeshManager::get_parent_mesh (const Mesh & my_mesh) const
Definition at line 352 of file MultiMeshManager.cpp.
References m_parent.
get_parent_mesh() [2/2]
Mesh & wmtk::multimesh::MultiMeshManager::get_parent_mesh (Mesh & my_mesh)
Definition at line 357 of file MultiMeshManager.cpp.
References m_parent.
Referenced by wmtk::Mesh::get_multi_mesh_parent_mesh().
get_root_mesh() [1/2]
const Mesh & wmtk::multimesh::MultiMeshManager::get_root_mesh (const Mesh & my_mesh) const
Definition at line 363 of file MultiMeshManager.cpp.
References get_root_mesh(), is_root(), wmtk::Mesh::m_multi_mesh_manager, and m_parent.
Referenced by get_mesh(), get_mesh(), wmtk::Mesh::get_multi_mesh_parent_mesh(), wmtk::Mesh::get_multi_mesh_root(), wmtk::Mesh::get_multi_mesh_root(), get_root_mesh(), get_root_mesh(), and map_to_root_tuple().
get_root_mesh() [2/2]
Mesh & wmtk::multimesh::MultiMeshManager::get_root_mesh (Mesh & my_mesh)
Definition at line 371 of file MultiMeshManager.cpp.
References get_root_mesh(), is_root(), wmtk::Mesh::m_multi_mesh_manager, and m_parent.
has_child_mesh()
bool wmtk::multimesh::MultiMeshManager::has_child_mesh () const
Definition at line 873 of file MultiMeshManager.cpp.
References m_children.
Referenced by wmtk::Mesh::has_child_mesh().
has_child_mesh_in_dimension()
bool wmtk::multimesh::MultiMeshManager::has_child_mesh_in_dimension (int64_t dimension) const inline
Definition at line 349 of file MultiMeshManager.hpp.
References m_has_child_mesh_in_dimension.
Referenced by wmtk::Mesh::has_child_mesh_in_dimension().
is_child() [1/2]
bool wmtk::multimesh::MultiMeshManager::is_child (const Mesh & my_mesh, const Mesh & parent_mesh) const
Definition at line 202 of file MultiMeshManager.cpp.
References is_child(), is_root(), wmtk::Mesh::m_multi_mesh_manager, and m_parent.
is_child() [2/2]
bool wmtk::multimesh::MultiMeshManager::is_child (const std::vector< int64_t > & child, const std::vector< int64_t > & parent) static
Definition at line 851 of file MultiMeshManager.cpp.
Referenced by is_child(), lub_map_tuples(), relative_id(), and relative_id().
is_root()
bool wmtk::multimesh::MultiMeshManager::is_root () const
Specifies whether this structure is the root of a multi-mesh tree.
Returns
true if this is the root, false otherwise
Definition at line 166 of file MultiMeshManager.cpp.
References m_parent.
Referenced by absolute_id(), child_id(), get_root_mesh(), get_root_mesh(), is_child(), wmtk::Mesh::is_multi_mesh_root(), map_tuple_to_parent_tuple(), map_tuple_to_root_tuple(), register_child_mesh(), and relative_id().
least_upper_bound_id()
std::vector< int64_t > wmtk::multimesh::MultiMeshManager::least_upper_bound_id (const std::vector< int64_t > & a, const std::vector< int64_t > & b) static
Definition at line 827 of file MultiMeshManager.cpp.
Referenced by lub_map_tuples().
lub_map()
std::vector< simplex::Simplex > wmtk::multimesh::MultiMeshManager::lub_map (const Mesh & my_mesh, const Mesh & other_mesh, const simplex::Simplex & my_simplex) const
maps a simplex from this mesh to any other mesh using the LUB as the root
Satisfies the same properties of standard map, but uses a the LUB as the root
Parameters
my_mesh the mesh that this structure is owned by
the mesh a simplex should be mapped to
the simplex being mapped to the child mesh
Returns
every simplex that could correspond to this simplex, without the dimension encoded
Definition at line 438 of file MultiMeshManager.cpp.
References lub_map_tuples(), wmtk::simplex::Simplex::primitive_type(), and wmtk::simplex::utils::tuple_vector_to_homogeneous_simplex_vector().
Referenced by wmtk::Mesh::lub_map().
lub_map_tuples()
std::vector< Tuple > wmtk::multimesh::MultiMeshManager::lub_map_tuples (const Mesh & my_mesh, const Mesh & other_mesh, const simplex::Simplex & my_simplex) const
maps a simplex from this mesh to any other mesh using the LUB as the root
Satisfies the same properties of standard map, but uses a the LUB as the root
Parameters
my_mesh the mesh that this structure is owned by
the mesh a simplex should be mapped to
the simplex being mapped to the child mesh
Returns
every simplex that could correspond to this simplex, without the dimension encoded
Definition at line 567 of file MultiMeshManager.cpp.
References absolute_id(), wmtk::Mesh::absolute_multi_mesh_id(), is_child(), least_upper_bound_id(), wmtk::Mesh::m_multi_mesh_manager, map_up_to_tuples(), wmtk::simplex::Simplex::primitive_type(), relative_id(), and wmtk::simplex::Simplex::tuple().
Referenced by lub_map(), and wmtk::Mesh::lub_map_tuples().
map()
std::vector< simplex::Simplex > wmtk::multimesh::MultiMeshManager::map (const Mesh & my_mesh, const Mesh & other_mesh, const simplex::Simplex & my_simplex) const
maps a simplex from this mesh to any other mesh
Generic interface for mapping between two arbitrary meshes in a multi-mesh structure Note that this finds ALL versions of a simplex, potentially crossing over topological features above the pairs of simplices being mapped. For instance, if we map a trimesh seam edge to itself using this interface it will find the edge on the other side of the seam. If more granular mappings are required consider manually navigating the tree with map_to_parent and map_to_child, which of course require a more particular understanding on how a simplex is mapped. throws if two meshes are not part of the same multi-mesh structure
Parameters
my_mesh the mesh that this structure is owned by
the mesh a simplex should be mapped to
the simplex being mapped to the child mesh
Returns
every simplex that could correspond to this simplex
Definition at line 427 of file MultiMeshManager.cpp.
References map_tuples(), wmtk::simplex::Simplex::primitive_type(), and wmtk::simplex::utils::tuple_vector_to_homogeneous_simplex_vector().
Referenced by wmtk::Mesh::map().
map_down_relative_tuples()
std::vector< Tuple > wmtk::multimesh::MultiMeshManager::map_down_relative_tuples (const Mesh & my_mesh, const simplex::Simplex & my_simplex, const std::vector< int64_t > & local_id_path) const protected
Definition at line 506 of file MultiMeshManager.cpp.
References wmtk::Mesh::is_valid(), m_child_id, m_children, wmtk::Mesh::m_multi_mesh_manager, map_to_child_tuples(), wmtk::multimesh::MultiMeshManager::ChildData::mesh, wmtk::simplex::Simplex::primitive_type(), relative_id(), and wmtk::simplex::Simplex::tuple().
map_handles()
std::vector< wmtk::attribute::TypedAttributeHandle< int64_t > > wmtk::multimesh::MultiMeshManager::map_handles () const
Definition at line 320 of file MultiMeshManager.cpp.
References wmtk::attribute::TypedAttributeHandle< T >::is_valid(), m_children, and map_to_parent_handle.
Referenced by wmtk::Mesh::builtin_attributes().
map_to_child()
std::vector< simplex::Simplex > wmtk::multimesh::MultiMeshManager::map_to_child (const Mesh & my_mesh, const Mesh & child_mesh, const simplex::Simplex & my_simplex) const
optimized map fromsimplex from this mesh to one of its direct children
Cannot be used outside of applications with guaranteed multi-mesh structures
Parameters
my_mesh the mesh that this structure is owned by
child mesh the simplex shoudl be mapped to
the simplex being mapped to the child mesh
the set of child mesh's simplices that are equivalent to the input simplex
Definition at line 724 of file MultiMeshManager.cpp.
References map_to_child_tuples(), wmtk::simplex::Simplex::primitive_type(), and wmtk::simplex::utils::tuple_vector_to_homogeneous_simplex_vector().
Referenced by wmtk::Mesh::map_to_child().
map_to_child_tuples() [1/3]
std::vector< Tuple > wmtk::multimesh::MultiMeshManager::map_to_child_tuples (const Mesh & my_mesh, const ChildData & child_data, const simplex::Simplex & simplex) const protected
Definition at line 660 of file MultiMeshManager.cpp.
References wmtk::simplex::cofaces_single_dimension_tuples(), wmtk::Mesh::is_valid(), wmtk::Mesh::m_multi_mesh_manager, wmtk::simplex::utils::make_unique_tuples(), wmtk::multimesh::MultiMeshManager::ChildData::map_handle, map_to_parent_handle, map_tuple_between_meshes(), wmtk::multimesh::MultiMeshManager::ChildData::mesh, wmtk::simplex::Simplex::primitive_type(), and wmtk::Mesh::top_simplex_type().
map_to_child_tuples() [2/3]
std::vector< Tuple > wmtk::multimesh::MultiMeshManager::map_to_child_tuples (const Mesh & my_mesh, const Mesh & child_mesh, const simplex::Simplex & my_simplex) const
Definition at line 706 of file MultiMeshManager.cpp.
References child_id(), wmtk::Mesh::m_multi_mesh_manager, and map_to_child_tuples().
Referenced by map_down_relative_tuples(), map_to_child(), wmtk::Mesh::map_to_child_tuples(), map_to_child_tuples(), and map_to_child_tuples().
map_to_child_tuples() [3/3]
std::vector< Tuple > wmtk::multimesh::MultiMeshManager::map_to_child_tuples (const Mesh & my_mesh, int64_t child_id, const simplex::Simplex & simplex) const protected
Definition at line 714 of file MultiMeshManager.cpp.
References child_id(), m_children, and map_to_child_tuples().
map_to_parent()
simplex::Simplex wmtk::multimesh::MultiMeshManager::map_to_parent (const Mesh & my_mesh, const simplex::Simplex & my_simplex) const
optimized map from a simplex from this mesh to its direct parent
Maps a simplex to its direct parent in the multi-mesh structure. Cannot be used outside of applications with guaranteed multi-mesh structures
throws if this is the root
Parameters
my_mesh the mesh that this structure is owned by
the simplex being mapped to the parent mesh
Returns
the unique parent mesh's simplex that is parent to the input one
Definition at line 625 of file MultiMeshManager.cpp.
References map_tuple_to_parent_tuple(), wmtk::simplex::Simplex::primitive_type(), and wmtk::simplex::Simplex::tuple().
Referenced by wmtk::Mesh::map_to_parent().
map_to_parent_tuple()
Tuple wmtk::multimesh::MultiMeshManager::map_to_parent_tuple (const Mesh & my_mesh, const simplex::Simplex & my_simplex) const
optimized map from a simplex from this mesh to its direct parent
Maps a simplex to its direct parent in the multi-mesh structure. Cannot be used outside of applications with guaranteed multi-mesh structures
throws if this is the root
Parameters
my_mesh the mesh that this structure is owned by
the simplex being mapped to the parent mesh
Returns
the unique parent mesh's simplex that is parent to the input one, without the dimension encoded
Definition at line 633 of file MultiMeshManager.cpp.
References map_tuple_to_parent_tuple(), and wmtk::simplex::Simplex::tuple().
Referenced by wmtk::Mesh::map_to_parent_tuple().
map_to_root()
simplex::Simplex wmtk::multimesh::MultiMeshManager::map_to_root (const Mesh & my_mesh, const simplex::Simplex & my_simplex) const
maps a simplex from this mesh to the root mesh
Cannot be used outside of applications with guaranteed multi-mesh structures
Parameters
my_mesh the mesh that this structure is owned by
the simplex being mapped to the parent mesh
Returns
the unique root mesh's simplex that is the root to the input one
Definition at line 596 of file MultiMeshManager.cpp.
References map_to_root_tuple(), and wmtk::simplex::Simplex::primitive_type().
Referenced by wmtk::Mesh::map_to_root().
map_to_root_tuple()
Tuple wmtk::multimesh::MultiMeshManager::map_to_root_tuple (const Mesh & my_mesh, const simplex::Simplex & my_simplex) const
maps a simplex from this mesh to the root mesh
Cannot be used outside of applications with guaranteed multi-mesh structures
Parameters
my_mesh the mesh that this structure is owned by
the simplex being mapped to the parent mesh
Returns
the unique root mesh's simplex that is the root to the input one, without the dimension encoded
Definition at line 603 of file MultiMeshManager.cpp.
References get_root_mesh(), map_tuple_to_root_tuple(), and wmtk::simplex::Simplex::tuple().
Referenced by can_map(), map_to_root(), and wmtk::Mesh::map_to_root_tuple().
map_tuple_between_meshes()
Tuple wmtk::multimesh::MultiMeshManager::map_tuple_between_meshes (const AccessorType & source_to_target_map_accessor, const AccessorType & target_to_source_map_accessor, const Tuple & source_tuple) static protected
Definition at line 43 of file MultiMeshManager.cpp.
References wmtk::dart::utils::apply_simplex_involution(), wmtk::dart::SimplexDart::dart_from_tuple(), wmtk::dart::SimplexDart::get_singleton(), wmtk::Tuple::global_cid(), wmtk::dart::SimplexDart::is_valid(), wmtk::logger(), wmtk::dart::DartAccessor< Dim, MeshType >::mesh(), wmtk::simplex::top_dimension_cofaces_tuples(), and wmtk::dart::SimplexDart::tuple_from_dart().
Referenced by map_to_child_tuples(), and map_tuple_to_parent_tuple().
map_tuple_to_parent_tuple()
Tuple wmtk::multimesh::MultiMeshManager::map_tuple_to_parent_tuple (const Mesh & my_mesh, const Tuple & my_tuple) const protected
Definition at line 639 of file MultiMeshManager.cpp.
References children(), is_root(), m_child_id, wmtk::Mesh::m_multi_mesh_manager, m_parent, map_to_parent_handle, and map_tuple_between_meshes().
Referenced by map_to_parent(), map_to_parent_tuple(), map_tuple_to_root_tuple(), map_up_to_tuples(), and map_up_to_tuples().
map_tuple_to_root_tuple()
Tuple wmtk::multimesh::MultiMeshManager::map_tuple_to_root_tuple (const Mesh & my_mesh, const Tuple & my_tuple) const protected
Definition at line 610 of file MultiMeshManager.cpp.
References wmtk::Tuple::is_null(), is_root(), wmtk::Mesh::is_valid(), wmtk::Mesh::m_multi_mesh_manager, m_parent, map_tuple_to_parent_tuple(), and map_tuple_to_root_tuple().
Referenced by map_to_root_tuple(), and map_tuple_to_root_tuple().
map_tuples()
std::vector< Tuple > wmtk::multimesh::MultiMeshManager::map_tuples (const Mesh & my_mesh, const Mesh & other_mesh, const simplex::Simplex & my_simplex) const
maps a simplex from this mesh to any other mesh
Generic interface for mapping between two arbitrary meshes in a multi-mesh structure Note that this finds ALL versions of a simplex, potentially crossing over topological features above the pairs of simplices being mapped. For instance, if we map a trimesh seam edge to itself using this interface it will find the edge on the other side of the seam. If more granular mappings are required consider manually navigating the tree with map_to_parent and map_to_child, which of course require a more particular understanding on how a simplex is mapped. throws if two meshes are not part of the same multi-mesh structure
Parameters
my_mesh the mesh that this structure is owned by
the mesh a simplex should be mapped to
the simplex being mapped to the child mesh
Returns
every simplex that could correspond to this simplex, without the dimension encoded
Definition at line 550 of file MultiMeshManager.cpp.
References absolute_id(), wmtk::Mesh::absolute_multi_mesh_id(), map_up_to_tuples(), wmtk::simplex::Simplex::primitive_type(), and wmtk::simplex::Simplex::tuple().
Referenced by map(), and wmtk::Mesh::map_tuples().
map_up_to_tuples() [1/3]
std::pair< const Mesh &, Tuple > wmtk::multimesh::MultiMeshManager::map_up_to_tuples (const Mesh & my_mesh, const Mesh & other, const Tuple & tuple) const protected
Definition at line 462 of file MultiMeshManager.cpp.
References can_map_up(), wmtk::Mesh::is_from_same_multi_mesh_structure(), wmtk::Tuple::is_null(), wmtk::Mesh::is_valid(), wmtk::Mesh::m_multi_mesh_manager, m_parent, and map_tuple_to_parent_tuple().
map_up_to_tuples() [2/3]
std::pair< const Mesh &, Tuple > wmtk::multimesh::MultiMeshManager::map_up_to_tuples (const Mesh & my_mesh, const simplex::Simplex & simplex, int64_t depth) const protected
Definition at line 453 of file MultiMeshManager.cpp.
References map_up_to_tuples(), and wmtk::simplex::Simplex::tuple().
Referenced by can_map_child(), lub_map_tuples(), map_tuples(), map_up_to_tuples(), and wmtk::Mesh::map_up_to_tuples().
map_up_to_tuples() [3/3]
std::pair< const Mesh &, Tuple > wmtk::multimesh::MultiMeshManager::map_up_to_tuples (const Mesh & my_mesh, const Tuple & tuple, int64_t depth) const protected
Definition at line 483 of file MultiMeshManager.cpp.
References wmtk::Tuple::is_null(), wmtk::Mesh::is_valid(), wmtk::Mesh::m_multi_mesh_manager, m_parent, and map_tuple_to_parent_tuple().
mapped_darts()
std::tuple< dart::Dart, dart::Dart > wmtk::multimesh::MultiMeshManager::mapped_darts (const Mesh & my_mesh, const Mesh & child_mesh, int64_t index) const protected
Referenced by mapped_tuples().
mapped_tuples()
std::tuple< Tuple, Tuple > wmtk::multimesh::MultiMeshManager::mapped_tuples (const Mesh & my_mesh, const Mesh & child_mesh, int64_t index) const protected
Definition at line 81 of file MultiMeshManager_map_updates.cpp.
References wmtk::Mesh::get_index_access(), get_map_const_accessors(), wmtk::dart::SimplexDart::get_singleton(), wmtk::Mesh::m_multi_mesh_manager, mapped_darts(), wmtk::Mesh::top_simplex_type(), wmtk::dart::SimplexDart::tuple_from_dart(), and wmtk::multimesh::utils::vectors_to_tuples().
Referenced by update_maps_from_edge_operation().
operator=() [1/2]
MultiMeshManager & wmtk::multimesh::MultiMeshManager::operator= (const MultiMeshManager & o) default
operator=() [2/2]
MultiMeshManager & wmtk::multimesh::MultiMeshManager::operator= (MultiMeshManager && o) default
parent_global_cid()
int64_t wmtk::multimesh::MultiMeshManager::parent_global_cid (const AccessorType & child_to_parent, int64_t child_gid) static protected
Definition at line 242 of file MultiMeshManager_map_updates.cpp.
References wmtk::Mesh::get_index_access().
Referenced by wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::parent_global_cid().
parent_local_fid()
int64_t wmtk::multimesh::MultiMeshManager::parent_local_fid (const AccessorType & child_to_parent, int64_t child_gid) static protected
Definition at line 256 of file MultiMeshManager_map_updates.cpp.
References wmtk::Mesh::get_index_access(), wmtk::dart::SimplexDart::get_singleton(), wmtk::dart::SimplexDart::simplex_index(), wmtk::Tetrahedron, and wmtk::Triangle.
Referenced by wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::parent_local_fid().
parent_to_child_map_attribute_name()
std::string wmtk::multimesh::MultiMeshManager::parent_to_child_map_attribute_name (int64_t index) static protected
Definition at line 774 of file MultiMeshManager.cpp.
Referenced by wmtk::HDF5Reader::read(), register_child_mesh(), and update_child_handles().
register_child_mesh()
void wmtk::multimesh::MultiMeshManager::register_child_mesh (Mesh & my_mesh, const std::shared_ptr< Mesh > & child_mesh, const std::vector< std::array< Tuple, 2 > > & child_tuple_my_tuple_map)
register a another mesh as a child of this mesh.
Parameters
my_mesh the mesh that this structure is owned by
child_mesh the mesh that will be added a child of this mesh
the set of tuples {A,B} where A is from "this mesh" and B represents a top-dimension simplex in the child_mesh. Every top dimension tuple of the child mesh must be represented here
Definition at line 216 of file MultiMeshManager.cpp.
References absolute_id(), child_to_parent_map_attribute_name(), wmtk::Mesh::has_attribute(), is_root(), wmtk::Mesh::is_valid(), wmtk::logger(), m_child_id, m_children, m_has_child_mesh_in_dimension, wmtk::Mesh::m_multi_mesh_manager, m_parent, map_to_parent_handle, parent_to_child_map_attribute_name(), wmtk::multimesh::utils::symmetric_write_tuple_map_attributes(), wmtk::Mesh::top_cell_dimension(), and wmtk::Mesh::top_simplex_type().
Referenced by wmtk::Mesh::register_child_mesh().
relative_id() [1/2]
std::vector< int64_t > wmtk::multimesh::MultiMeshManager::relative_id (const Mesh & my_mesh, const Mesh & parent_mesh) const
Definition at line 189 of file MultiMeshManager.cpp.
References is_child(), is_root(), m_child_id, wmtk::Mesh::m_multi_mesh_manager, m_parent, and relative_id().
relative_id() [2/2]
std::vector< int64_t > wmtk::multimesh::MultiMeshManager::relative_id (const std::vector< int64_t > & parent, const std::vector< int64_t > & child) static
Definition at line 842 of file MultiMeshManager.cpp.
References is_child().
Referenced by wmtk::components::multimesh::NamedMultiMesh::append_child_mesh_names(), get_child_mesh(), get_child_mesh(), wmtk::components::multimesh::NamedMultiMesh::get_id(), lub_map_tuples(), map_down_relative_tuples(), relative_id(), and wmtk::Mesh::serialize().
same_simplex_dimension_surjection()
std::vector< std::array< Tuple, 2 > > wmtk::multimesh::MultiMeshManager::same_simplex_dimension_surjection (const Mesh & parent, const Mesh & child, const std::vector< int64_t > & parent_simplices) static
Definition at line 738 of file MultiMeshManager.cpp.
References wmtk::Mesh::capacity(), wmtk::Mesh::get_const_flag_accessor(), wmtk::Mesh::top_simplex_type(), and wmtk::Mesh::tuple_from_id().
Referenced by wmtk::multimesh::same_simplex_dimension_surjection().
serialize()
void wmtk::multimesh::MultiMeshManager::serialize (io::MeshWriter & writer, const Mesh * local_root = nullptr) const
Definition at line 866 of file MultiMeshManager.cpp.
References m_children.
Referenced by wmtk::Mesh::serialize().
try_updating_map_tuple_from_split()
std::optional< Tuple > wmtk::multimesh::MultiMeshManager::try_updating_map_tuple_from_split (Mesh & my_mesh, const simplex::Simplex & old_simplex, const int64_t old_gid, const std::vector< Tuple > & tuple_alternatives, const std::tuple< int64_t, std::array< int64_t, 2 > > & split_cell_maps) const protected
update_child_handles()
void wmtk::multimesh::MultiMeshManager::update_child_handles (Mesh & my_mesh)
Clean up child data after deleting attributes.
When attributes are deleted, all attribute handles are invalidated. This method goes through all child data and updates the handles.
Definition at line 107 of file MultiMeshManager_map_updates.cpp.
References children(), wmtk::Mesh::get_attribute_handle_typed(), wmtk::Mesh::m_attribute_manager, m_children, wmtk::Mesh::m_multi_mesh_manager, wmtk::multimesh::MultiMeshManager::ChildData::mesh, parent_to_child_map_attribute_name(), and wmtk::attribute::AttributeManager::set_name().
Referenced by deregister_child_mesh(), and wmtk::Mesh::update_child_handles().
update_maps_from_edge_operation() [1/2]
void wmtk::multimesh::MultiMeshManager::update_maps_from_edge_operation (Mesh & my_mesh, const operations::EdgeOperationData & operation_data) protected
Definition at line 128 of file MultiMeshManager_map_updates.cpp.
References wmtk::get_primitive_type_from_id(), m_has_child_mesh_in_dimension, and update_maps_from_edge_operation().
update_maps_from_edge_operation() [2/2]
void wmtk::multimesh::MultiMeshManager::update_maps_from_edge_operation (Mesh & my_mesh, PrimitiveType primitive_type, const operations::EdgeOperationData & operation_data) protected
Definition at line 139 of file MultiMeshManager_map_updates.cpp.
References children(), get_map_accessors(), wmtk::get_primitive_type_id(), wmtk::operations::EdgeOperationData::global_ids_to_update, wmtk::Mesh::is_removed(), wmtk::logger(), mapped_tuples(), and wmtk::multimesh::utils::symmetric_write_tuple_map_attributes().
Referenced by wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::update_all_maps(), and update_maps_from_edge_operation().
Friends And Related Symbol Documentation
multimesh::MultiMeshSimplexVisitor
template<int64_t cell_dimension, typename NodeFunctor > friend class multimesh::MultiMeshSimplexVisitor friend
Definition at line 56 of file MultiMeshManager.hpp.
multimesh::MultiMeshSimplexVisitorExecutor
template<typename Visitor > friend class multimesh::MultiMeshSimplexVisitorExecutor friend
Definition at line 59 of file MultiMeshManager.hpp.
multimesh::MultiMeshVisitor
template<typename NodeFunctor > friend class multimesh::MultiMeshVisitor friend
Definition at line 63 of file MultiMeshManager.hpp.
multimesh::MultiMeshVisitorExecutor
template<typename Visitor > friend class multimesh::MultiMeshVisitorExecutor friend
Definition at line 65 of file MultiMeshManager.hpp.
operations::utils::UpdateEdgeOperationMultiMeshMapFunctor
friend class operations::utils::UpdateEdgeOperationMultiMeshMapFunctor friend
Definition at line 60 of file MultiMeshManager.hpp.
utils::MapValidator
friend class utils::MapValidator friend
Definition at line 68 of file MultiMeshManager.hpp.
wmtk::HDF5Reader
friend class wmtk::HDF5Reader friend
Definition at line 66 of file MultiMeshManager.hpp.
wmtk::Mesh
friend class wmtk::Mesh friend
Definition at line 57 of file MultiMeshManager.hpp.
Member Data Documentation
m_child_id
int64_t wmtk::multimesh::MultiMeshManager::m_child_id = -1 protected
Definition at line 375 of file MultiMeshManager.hpp.
Referenced by absolute_id(), child_hashes(), child_id(), wmtk::Mesh::consolidate(), deregister_child_mesh(), get_child_mesh(), map_down_relative_tuples(), map_tuple_to_parent_tuple(), register_child_mesh(), and relative_id().
m_children
std::vector<ChildData> wmtk::multimesh::MultiMeshManager::m_children protected
Definition at line 379 of file MultiMeshManager.hpp.
Referenced by can_map_to_child(), wmtk::multimesh::utils::MapValidator::check_child_map_attributes_valid(), child_hashables(), child_hashes(), children(), children(), wmtk::Mesh::consolidate(), deregister_child_mesh(), detach_children(), get_child_mesh(), get_child_meshes(), has_child_mesh(), wmtk::Mesh::map_all_children(), map_down_relative_tuples(), map_handles(), map_to_child_tuples(), wmtk::Mesh::mappable_child_meshes(), wmtk::multimesh::utils::MapValidator::print(), register_child_mesh(), serialize(), and update_child_handles().
m_has_child_mesh_in_dimension
std::vector<bool> wmtk::multimesh::MultiMeshManager::m_has_child_mesh_in_dimension protected
Definition at line 382 of file MultiMeshManager.hpp.
Referenced by has_child_mesh_in_dimension(), register_child_mesh(), and update_maps_from_edge_operation().
m_parent
Mesh* wmtk::multimesh::MultiMeshManager::m_parent = nullptr protected
Definition at line 369 of file MultiMeshManager.hpp.
Referenced by absolute_id(), can_map_to_parent(), can_map_up(), wmtk::multimesh::utils::MapValidator::check_child_facet_uniqueness(), wmtk::multimesh::utils::MapValidator::check_child_switch_homomorphism(), wmtk::multimesh::utils::MapValidator::check_parent_map_attribute_valid(), child_hashes(), wmtk::Mesh::consolidate(), deregister_child_mesh(), get_parent_mesh(), get_parent_mesh(), get_root_mesh(), get_root_mesh(), is_child(), is_root(), wmtk::Mesh::map_all(), map_tuple_to_parent_tuple(), map_tuple_to_root_tuple(), map_up_to_tuples(), map_up_to_tuples(), wmtk::Mesh::mappable_meshes(), register_child_mesh(), and relative_id().
map_to_parent_handle
TypedAttributeHandle<int64_t> wmtk::multimesh::MultiMeshManager::map_to_parent_handle protected
Definition at line 372 of file MultiMeshManager.hpp.
Referenced by wmtk::multimesh::utils::MapValidator::check_parent_map_attribute_valid(), child_hashes(), wmtk::Mesh::consolidate(), deregister_child_mesh(), get_map_accessors(), get_map_const_accessors(), map_handles(), map_to_child_tuples(), map_tuple_to_parent_tuple(), and register_child_mesh().
The documentation for this class was generated from the following files:
src/wmtk/multimesh/MultiMeshManager.hpp
src/wmtk/multimesh/MultiMeshManager.cpp
src/wmtk/multimesh/MultiMeshManager_map_updates.cpp