Wildmeshing Toolkit: wmtk::dart::SimplexAdjacency< Dim > Class Template Reference
wmtk::dart::SimplexAdjacency< Dim > Class Template Reference
#include <SimplexAdjacency.hpp>
Classes
class Iterator
Public Types
using iterator_type = Iterator< false >
using const_iterator_type = Iterator< true >
Public Member Functions
DartWrap operator[] (int64_t index)
ConstDartWrap operator[] (int64_t index) const
template<typename IT , typename OT >
requires (Dim == 1)
DartWrap operator= (const _Dart< IT, OT > &d)
operator DartWrap ()
operator ConstDartWrap () const
operator Dart () const
const_iterator_type begin () const
const_iterator_type end () const
const_iterator_type cbegin () const
const_iterator_type cend () const
iterator_type begin ()
iterator_type end ()
Private Member Functions
ConstDartWrap dart_as_tuple (int64_t index) const
DartWrap dart_as_tuple (int64_t index)
Private Attributes
std::array< int64_t, Dim > m_global_ids
std::array< int8_t, Dim > m_permutations
Detailed Description
template<int64_t Dim>
class wmtk::dart::SimplexAdjacency< Dim >
Definition at line 11 of file SimplexAdjacency.hpp.
Member Typedef Documentation
const_iterator_type
template<int64_t Dim> using wmtk::dart::SimplexAdjacency< Dim >::const_iterator_type = Iterator<true>
Definition at line 78 of file SimplexAdjacency.hpp.
iterator_type
template<int64_t Dim> using wmtk::dart::SimplexAdjacency< Dim >::iterator_type = Iterator<false>
Definition at line 77 of file SimplexAdjacency.hpp.
Member Function Documentation
begin() [1/2]
template<int64_t Dim> iterator_type wmtk::dart::SimplexAdjacency< Dim >::begin () inline
Definition at line 85 of file SimplexAdjacency.hpp.
begin() [2/2]
template<int64_t Dim> const_iterator_type wmtk::dart::SimplexAdjacency< Dim >::begin () const inline
Definition at line 81 of file SimplexAdjacency.hpp.
cbegin()
template<int64_t Dim> const_iterator_type wmtk::dart::SimplexAdjacency< Dim >::cbegin () const inline
Definition at line 83 of file SimplexAdjacency.hpp.
cend()
template<int64_t Dim> const_iterator_type wmtk::dart::SimplexAdjacency< Dim >::cend () const inline
Definition at line 84 of file SimplexAdjacency.hpp.
dart_as_tuple() [1/2]
template<int64_t Dim> DartWrap wmtk::dart::SimplexAdjacency< Dim >::dart_as_tuple (int64_t index) inline private
Definition at line 94 of file SimplexAdjacency.hpp.
References wmtk::dart::SimplexAdjacency< Dim >::m_global_ids, and wmtk::dart::SimplexAdjacency< Dim >::m_permutations.
dart_as_tuple() [2/2]
template<int64_t Dim> ConstDartWrap wmtk::dart::SimplexAdjacency< Dim >::dart_as_tuple (int64_t index) const inline private
Definition at line 90 of file SimplexAdjacency.hpp.
References wmtk::dart::SimplexAdjacency< Dim >::m_global_ids, and wmtk::dart::SimplexAdjacency< Dim >::m_permutations.
Referenced by wmtk::dart::SimplexAdjacency< Dim >::operator ConstDartWrap(), wmtk::dart::SimplexAdjacency< Dim >::operator Dart(), wmtk::dart::SimplexAdjacency< Dim >::operator DartWrap(), wmtk::dart::SimplexAdjacency< Dim >::operator=(), wmtk::dart::SimplexAdjacency< Dim >::operator[](), and wmtk::dart::SimplexAdjacency< Dim >::operator[]().
end() [1/2]
template<int64_t Dim> iterator_type wmtk::dart::SimplexAdjacency< Dim >::end () inline
Definition at line 86 of file SimplexAdjacency.hpp.
end() [2/2]
template<int64_t Dim> const_iterator_type wmtk::dart::SimplexAdjacency< Dim >::end () const inline
Definition at line 82 of file SimplexAdjacency.hpp.
operator ConstDartWrap()
template<int64_t Dim> wmtk::dart::SimplexAdjacency< Dim >::operator ConstDartWrap () const inline
Definition at line 30 of file SimplexAdjacency.hpp.
References wmtk::dart::SimplexAdjacency< Dim >::dart_as_tuple().
operator Dart()
template<int64_t Dim> wmtk::dart::SimplexAdjacency< Dim >::operator Dart () const inline
Definition at line 35 of file SimplexAdjacency.hpp.
References wmtk::dart::SimplexAdjacency< Dim >::dart_as_tuple().
operator DartWrap()
template<int64_t Dim> wmtk::dart::SimplexAdjacency< Dim >::operator DartWrap () inline
Definition at line 25 of file SimplexAdjacency.hpp.
References wmtk::dart::SimplexAdjacency< Dim >::dart_as_tuple().
operator=()
template<int64_t Dim> template<typename IT , typename OT > requires (Dim == 1) DartWrap wmtk::dart::SimplexAdjacency< Dim >::operator= (const _Dart< IT, OT > & d) inline
Definition at line 19 of file SimplexAdjacency.hpp.
References wmtk::dart::SimplexAdjacency< Dim >::dart_as_tuple().
operator[]() [1/2]
template<int64_t Dim> DartWrap wmtk::dart::SimplexAdjacency< Dim >::operator[] (int64_t index) inline
Definition at line 15 of file SimplexAdjacency.hpp.
References wmtk::dart::SimplexAdjacency< Dim >::dart_as_tuple().
operator[]() [2/2]
template<int64_t Dim> ConstDartWrap wmtk::dart::SimplexAdjacency< Dim >::operator[] (int64_t index) const inline
Definition at line 16 of file SimplexAdjacency.hpp.
References wmtk::dart::SimplexAdjacency< Dim >::dart_as_tuple().
Member Data Documentation
m_global_ids
template<int64_t Dim> std::array<int64_t, Dim> wmtk::dart::SimplexAdjacency< Dim >::m_global_ids private
Definition at line 98 of file SimplexAdjacency.hpp.
Referenced by wmtk::dart::SimplexAdjacency< Dim >::dart_as_tuple(), and wmtk::dart::SimplexAdjacency< Dim >::dart_as_tuple().
m_permutations
template<int64_t Dim> std::array<int8_t, Dim> wmtk::dart::SimplexAdjacency< Dim >::m_permutations private
Definition at line 99 of file SimplexAdjacency.hpp.
Referenced by wmtk::dart::SimplexAdjacency< Dim >::dart_as_tuple(), and wmtk::dart::SimplexAdjacency< Dim >::dart_as_tuple().
The documentation for this class was generated from the following files:
src/wmtk/dart/Dart.hpp
src/wmtk/dart/SimplexAdjacency.hpp