Wildmeshing Toolkit: wmtk::dart::DartTopologyAccessor< Dim, MeshType > Class Template Reference
wmtk::dart::DartTopologyAccessor< Dim, MeshType > Class Template Reference
#include <DartTopologyAccessor.hpp>
Public Types
using BaseType = DartAccessor< Dim+1, MeshType >
using IndexBaseType = typename BaseType::IndexBaseType
Public Types inherited from wmtk::dart::DartAccessor< Dim+1, MeshType >
using IndexBaseType = DartIndexAccessor< Dim, MeshType >
Public Types inherited from wmtk::dart::DartIndexAccessor< Dim, MeshType >
using BaseAccessor = wmtk::attribute::Accessor< int64_t, MeshType, attribute::CachingAttribute< int64_t >, Dim+1 >
Public Member Functions
template<typename IT , typename OT >
dart::Dart switch_facet (const dart::_Dart< IT, OT > &d) const
template<typename IT , typename OT >
dart::Dart switch_dart (const dart::_Dart< IT, OT > &d, PrimitiveType pt) const
template<typename IT , typename OT >
bool is_boundary (const dart::_Dart< IT, OT > &d) const
template<typename IT , typename OT >
int8_t get_boundary_local_index (const dart::_Dart< IT, OT > &d) const
template<typename IT , typename OT >
dart::Dart get_neighbor (const dart::_Dart< IT, OT > &d) const
template<typename IT , typename OT >
dart::DartWrap get_neighbor (const dart::_Dart< IT, OT > &d)
void fuse (const dart::Dart &d, const dart::Dart &od)
void populate ()
Public Member Functions inherited from wmtk::dart::DartAccessor< Dim+1, MeshType >
dart::SimplexAdjacency< Dim > & operator[] (const dart::_Dart< IT, OT > &t)
const dart::SimplexAdjacency< Dim > & operator[] (const dart::_Dart< IT, OT > &t) const
size_t size () const
const MeshType & mesh () const
Public Member Functions inherited from wmtk::dart::DartIndexAccessor< Dim, MeshType >
DartIndexAccessor (BaseAccessor acc)
DartIndexAccessor (const MeshType &mesh, const wmtk::attribute::MeshAttributeHandle &mah)
DartIndexAccessor (const MeshType &mesh, const wmtk::attribute::TypedAttributeHandle< int64_t > &h)
template<typename MeshType2 >
DartIndexAccessor (const DartIndexAccessor< Dim, MeshType2 > &o)
dart::SimplexAdjacency< Dim > & operator[] (int64_t index)
const dart::SimplexAdjacency< Dim > & operator[] (int64_t index) const
const MeshType & mesh () const
size_t size () const
Static Public Member Functions
static wmtk::attribute::TypedAttributeHandle< int64_t > register_boundary_topology_attribute (MeshType &m, const std::string_view &name, bool do_populate=false)
Static Public Member Functions inherited from wmtk::dart::DartAccessor< Dim+1, MeshType >
static wmtk::attribute::TypedAttributeHandle< int64_t > register_attribute (MeshType &m, const std::string_view &name, PrimitiveType pt)
Private Member Functions
dart::Dart switch_facet (int64_t global_id, int8_t permutation) const
Additional Inherited Members
Protected Attributes inherited from wmtk::dart::DartAccessor< Dim+1, MeshType >
BaseAccessor m_base_accessor
Protected Attributes inherited from wmtk::dart::DartIndexAccessor< Dim, MeshType >
BaseAccessor m_base_accessor
Detailed Description
template<int Dim, typename MeshType>
class wmtk::dart::DartTopologyAccessor< Dim, MeshType >
Definition at line 11 of file DartTopologyAccessor.hpp.
Member Typedef Documentation
BaseType
template<int Dim, typename MeshType > using wmtk::dart::DartTopologyAccessor< Dim, MeshType >::BaseType = DartAccessor<Dim + 1, MeshType>
Definition at line 14 of file DartTopologyAccessor.hpp.
IndexBaseType
template<int Dim, typename MeshType > using wmtk::dart::DartTopologyAccessor< Dim, MeshType >::IndexBaseType = typename BaseType::IndexBaseType
Definition at line 15 of file DartTopologyAccessor.hpp.
Member Function Documentation
fuse()
template<int Dim, typename MeshType > void wmtk::dart::DartTopologyAccessor< Dim, MeshType >::fuse (const dart::Dart & d, const dart::Dart & od) inline
Definition at line 82 of file DartTopologyAccessor.hpp.
References wmtk::dart::DartTopologyAccessor< Dim, MeshType >::get_neighbor(), wmtk::dart::utils::get_simplex_involution(), wmtk::dart::utils::get_simplex_involution_pair(), and wmtk::dart::DartAccessor< Dim+1, MeshType >::mesh().
Referenced by wmtk::dart::DartTopologyAccessor< Dim, MeshType >::populate().
get_boundary_local_index()
template<int Dim, typename MeshType > template<typename IT , typename OT > int8_t wmtk::dart::DartTopologyAccessor< Dim, MeshType >::get_boundary_local_index (const dart::_Dart< IT, OT > & d) const inline
Definition at line 63 of file DartTopologyAccessor.hpp.
References wmtk::dart::SimplexDart::get_singleton(), wmtk::dart::DartAccessor< Dim+1, MeshType >::mesh(), and wmtk::dart::SimplexDart::simplex_index().
Referenced by wmtk::dart::DartTopologyAccessor< Dim, MeshType >::get_neighbor(), and wmtk::dart::DartTopologyAccessor< Dim, MeshType >::get_neighbor().
get_neighbor() [1/2]
template<int Dim, typename MeshType > template<typename IT , typename OT > dart::DartWrap wmtk::dart::DartTopologyAccessor< Dim, MeshType >::get_neighbor (const dart::_Dart< IT, OT > & d) inline
Definition at line 77 of file DartTopologyAccessor.hpp.
References wmtk::dart::DartTopologyAccessor< Dim, MeshType >::get_boundary_local_index(), and wmtk::dart::_Dart< IndexType, OrientType >::global_id().
get_neighbor() [2/2]
template<int Dim, typename MeshType > template<typename IT , typename OT > dart::Dart wmtk::dart::DartTopologyAccessor< Dim, MeshType >::get_neighbor (const dart::_Dart< IT, OT > & d) const inline
Definition at line 71 of file DartTopologyAccessor.hpp.
References wmtk::dart::DartTopologyAccessor< Dim, MeshType >::get_boundary_local_index(), and wmtk::dart::_Dart< IndexType, OrientType >::global_id().
Referenced by wmtk::dart::DartTopologyAccessor< Dim, MeshType >::fuse(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::is_boundary(), and wmtk::dart::DartTopologyAccessor< Dim, MeshType >::populate().
is_boundary()
template<int Dim, typename MeshType > template<typename IT , typename OT > bool wmtk::dart::DartTopologyAccessor< Dim, MeshType >::is_boundary (const dart::_Dart< IT, OT > & d) const inline
Definition at line 57 of file DartTopologyAccessor.hpp.
References wmtk::dart::DartTopologyAccessor< Dim, MeshType >::get_neighbor(), and wmtk::dart::_Dart< IndexType, OrientType >::is_null().
populate()
template<int Dim, typename MeshType > void wmtk::dart::DartTopologyAccessor< Dim, MeshType >::populate () inline
Definition at line 95 of file DartTopologyAccessor.hpp.
References wmtk::dart::SimplexDart::dart_from_tuple(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::fuse(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::get_neighbor(), wmtk::dart::SimplexDart::get_singleton(), and wmtk::dart::DartAccessor< Dim+1, MeshType >::mesh().
Referenced by wmtk::dart::DartTopologyAccessor< Dim, MeshType >::register_boundary_topology_attribute().
register_boundary_topology_attribute()
template<int Dim, typename MeshType > static wmtk::attribute::TypedAttributeHandle< int64_t > wmtk::dart::DartTopologyAccessor< Dim, MeshType >::register_boundary_topology_attribute (MeshType & m, const std::string_view & name, bool do_populate = false) inline static
Definition at line 26 of file DartTopologyAccessor.hpp.
References wmtk::dart::DartTopologyAccessor< Dim, MeshType >::populate(), and wmtk::dart::DartAccessor< Dim+1, MeshType >::register_attribute().
switch_dart()
template<int Dim, typename MeshType > template<typename IT , typename OT > dart::Dart wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_dart (const dart::_Dart< IT, OT > & d, PrimitiveType pt) const inline
Definition at line 45 of file DartTopologyAccessor.hpp.
References wmtk::dart::SimplexDart::act(), wmtk::dart::SimplexDart::get_singleton(), wmtk::dart::DartAccessor< Dim+1, MeshType >::mesh(), wmtk::dart::SimplexDart::primitive_as_index(), and wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_facet().
Referenced by wmtk::dart::utils::indexed_topology_initialization().
switch_facet() [1/2]
template<int Dim, typename MeshType > template<typename IT , typename OT > dart::Dart wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_facet (const dart::_Dart< IT, OT > & d) const inline
Definition at line 39 of file DartTopologyAccessor.hpp.
References wmtk::dart::_Dart< IndexType, OrientType >::global_id(), wmtk::dart::_Dart< IndexType, OrientType >::permutation(), and wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_facet().
Referenced by wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_dart(), and wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_facet().
switch_facet() [2/2]
template<int Dim, typename MeshType > dart::Dart wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_facet (int64_t global_id, int8_t permutation) const inline private
Definition at line 114 of file DartTopologyAccessor.hpp.
References wmtk::dart::utils::apply_simplex_involution(), wmtk::dart::SimplexDart::get_singleton(), wmtk::dart::DartAccessor< Dim+1, MeshType >::mesh(), and wmtk::dart::SimplexDart::simplex_index().
The documentation for this class was generated from the following file:
src/wmtk/dart/DartTopologyAccessor.hpp