Wildmeshing Toolkit: wmtk::components::isotropic_remeshing::IsotropicRemeshing Class Reference
wmtk::components::isotropic_remeshing::IsotropicRemeshing Class Reference
#include <IsotropicRemeshing.hpp>
Public Member Functions
IsotropicRemeshing (const IsotropicRemeshingOptions &opts)
~IsotropicRemeshing ()
void run ()
void run (const Pass &pass, size_t pass_index)
Private Member Functions
std::vector< wmtk::attribute::MeshAttributeHandle > all_envelope_positions () const
void make_envelopes ()
void make_envelope_invariants ()
void make_interior_invariants ()
void configure_split ()
void configure_collapse ()
void configure_swap ()
void configure_smooth ()
Static Private Member Functions
static bool is_envelope_position (const wmtk::attribute::MeshAttributeHandle &position)
Private Attributes
IsotropicRemeshingOptions m_options
std::shared_ptr< operations::EdgeSplit > m_split
std::shared_ptr< operations::EdgeCollapse > m_collapse
std::shared_ptr< operations::composite::EdgeSwap > m_swap
std::shared_ptr< operations::Operation > m_smooth
std::vector< std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > > m_operation_transfers
std::map< std::string, std::shared_ptr< operations::Operation > > m_operations
std::shared_ptr< wmtk::invariants::InvariantCollection > m_envelope_invariants
std::shared_ptr< wmtk::invariants::InvariantCollection > m_interior_position_invariants
std::shared_ptr< wmtk::invariants::InvariantCollection > m_interior_edge_invariants
std::shared_ptr< wmtk::invariants::InvariantCollection > m_universal_invariants
Detailed Description
Definition at line 24 of file IsotropicRemeshing.hpp.
Constructor & Destructor Documentation
IsotropicRemeshing()
wmtk::components::isotropic_remeshing::IsotropicRemeshing::IsotropicRemeshing (const IsotropicRemeshingOptions & opts)
Definition at line 44 of file IsotropicRemeshing.cpp.
References wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::collapse, configure_collapse(), configure_smooth(), configure_split(), configure_swap(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::copied_attributes, wmtk::components::isotropic_remeshing::OperationOptions::enabled, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::envelope_size, wmtk::components::multimesh::MeshCollection::get_mesh_path(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::improvement_attributes, wmtk::attribute::MeshAttributeHandle::is_valid(), wmtk::logger(), m_collapse, m_operation_transfers, m_operations, m_options, m_smooth, m_split, m_swap, m_universal_invariants, wmtk::operations::attribute_update::make_cast_attribute_transfer_strategy(), make_envelopes(), make_interior_invariants(), wmtk::attribute::MeshAttributeHandle::mesh(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::mesh_collection, wmtk::components::isotropic_remeshing::EdgeSwapOptions::mode, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::passes, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::position_attribute, wmtk::components::isotropic_remeshing::Skip, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::smooth, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::split, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::swap, and wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::utility_attributes.
~IsotropicRemeshing()
wmtk::components::isotropic_remeshing::IsotropicRemeshing::~IsotropicRemeshing () default
Member Function Documentation
all_envelope_positions()
std::vector< wmtk::attribute::MeshAttributeHandle > wmtk::components::isotropic_remeshing::IsotropicRemeshing::all_envelope_positions () const private
Definition at line 143 of file IsotropicRemeshing.cpp.
References wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::all_positions(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::envelope_size, is_envelope_position(), and m_options.
Referenced by make_envelopes().
configure_collapse()
void wmtk::components::isotropic_remeshing::IsotropicRemeshing::configure_collapse () private
Definition at line 22 of file IsotropicRemeshing_collapse.cpp.
References wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::collapse, wmtk::components::isotropic_remeshing::internal::configure_collapse(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::copied_attributes, wmtk::logger(), m_collapse, m_envelope_invariants, m_operation_transfers, m_options, m_universal_invariants, wmtk::operations::attribute_update::make_cast_attribute_transfer_strategy(), wmtk::attribute::MeshAttributeHandle::mesh(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::mesh_collection, wmtk::operations::None, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::position_attribute, and wmtk::components::isotropic_remeshing::OperationOptions::priority.
Referenced by IsotropicRemeshing().
configure_smooth()
void wmtk::components::isotropic_remeshing::IsotropicRemeshing::configure_smooth () private
Definition at line 21 of file IsotropicRemeshing_smooth.cpp.
References wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::fix_uv_seam, wmtk::components::multimesh::MeshCollection::get_mesh(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::inversion_position_attribute, wmtk::Mesh::is_connectivity_valid(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::lock_boundary, m_envelope_invariants, m_interior_position_invariants, m_operation_transfers, m_options, m_smooth, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::mesh_collection, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::other_position_attributes, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::pass_through_attributes, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::position_attribute, wmtk::components::isotropic_remeshing::OperationOptions::priority, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::smooth, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::static_meshes, wmtk::Mesh::top_simplex_type(), wmtk::Triangle, and wmtk::Vertex.
Referenced by IsotropicRemeshing().
configure_split()
void wmtk::components::isotropic_remeshing::IsotropicRemeshing::configure_split () private
Definition at line 19 of file IsotropicRemeshing_split.cpp.
References wmtk::components::isotropic_remeshing::internal::configure_split(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::copied_attributes, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::lock_boundary, wmtk::logger(), m_envelope_invariants, m_interior_position_invariants, m_operation_transfers, m_options, m_split, wmtk::operations::attribute_update::make_cast_attribute_transfer_strategy(), wmtk::attribute::MeshAttributeHandle::mesh(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::mesh_collection, wmtk::operations::None, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::position_attribute, wmtk::components::isotropic_remeshing::OperationOptions::priority, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::split, and wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::use_for_periodic.
Referenced by IsotropicRemeshing().
configure_swap()
void wmtk::components::isotropic_remeshing::IsotropicRemeshing::configure_swap () private
Definition at line 48 of file IsotropicRemeshing_swap.cpp.
References wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::all_positions(), wmtk::components::isotropic_remeshing::AMIPS, wmtk::components::isotropic_remeshing::internal::collapse_core_invariants(), wmtk::components::isotropic_remeshing::internal::configure_swap_transfer(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::copied_attributes, wmtk::Edge, wmtk::Mesh::get_all_child_meshes(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::inversion_position_attribute, wmtk::logger(), m_envelope_invariants, m_operation_transfers, m_options, m_swap, m_universal_invariants, wmtk::operations::attribute_update::make_cast_attribute_transfer_strategy(), wmtk::attribute::MeshAttributeHandle::mesh(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::mesh_collection, wmtk::components::isotropic_remeshing::EdgeSwapOptions::mode, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::pass_through_attributes, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::position_attribute, wmtk::components::isotropic_remeshing::OperationOptions::priority, wmtk::components::isotropic_remeshing::Skip, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::static_meshes, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::swap, wmtk::Tetrahedron, wmtk::Mesh::top_simplex_type(), wmtk::Triangle, wmtk::components::isotropic_remeshing::Valence, and wmtk::Vertex.
Referenced by IsotropicRemeshing().
is_envelope_position()
bool wmtk::components::isotropic_remeshing::IsotropicRemeshing::is_envelope_position (const wmtk::attribute::MeshAttributeHandle & position) static private
Definition at line 160 of file IsotropicRemeshing.cpp.
References wmtk::attribute::MeshAttributeHandle::dimension(), wmtk::attribute::MeshAttributeHandle::mesh(), and wmtk::Mesh::top_cell_dimension().
Referenced by all_envelope_positions().
make_envelope_invariants()
void wmtk::components::isotropic_remeshing::IsotropicRemeshing::make_envelope_invariants () private
Definition at line 367 of file IsotropicRemeshing.cpp.
References make_envelopes().
make_envelopes()
void wmtk::components::isotropic_remeshing::IsotropicRemeshing::make_envelopes () private
Definition at line 372 of file IsotropicRemeshing.cpp.
References all_envelope_positions(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::envelope_size, wmtk::Mesh::get_multi_mesh_root(), m_envelope_invariants, m_options, wmtk::attribute::MeshAttributeHandle::mesh(), and wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::position_attribute.
Referenced by IsotropicRemeshing(), and make_envelope_invariants().
make_interior_invariants()
void wmtk::components::isotropic_remeshing::IsotropicRemeshing::make_interior_invariants () private
Definition at line 166 of file IsotropicRemeshing.cpp.
References wmtk::Edge, wmtk::multimesh::MultiMeshVisitor< NodeFunctor_ >::execute_from_root(), m_interior_edge_invariants, m_interior_position_invariants, m_options, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::position_attribute, and wmtk::Vertex.
Referenced by IsotropicRemeshing().
run() [1/2]
void wmtk::components::isotropic_remeshing::IsotropicRemeshing::run ()
Definition at line 188 of file IsotropicRemeshing.cpp.
References wmtk::components::multimesh::MeshCollection::all_meshes(), wmtk::components::output::utils::format(), wmtk::components::multimesh::MeshCollection::get_mesh(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::intermediate_output_format, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::iterations, wmtk::components::isotropic_remeshing::Pass::iterations, wmtk::logger(), m_collapse, m_options, m_smooth, m_split, m_swap, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::mesh_collection, wmtk::components::isotropic_remeshing::Pass::mesh_path, wmtk::components::output::output(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::passes, and run().
Referenced by wmtk::components::isotropic_remeshing::isotropic_remeshing(), and run().
run() [2/2]
void wmtk::components::isotropic_remeshing::IsotropicRemeshing::run (const Pass & pass, size_t pass_index)
Definition at line 260 of file IsotropicRemeshing.cpp.
References wmtk::multimesh::utils::check_maps_valid(), wmtk::SchedulerStats::collecting_time, wmtk::multimesh::consolidate(), wmtk::SchedulerStats::executing_time, wmtk::Mesh::get_all_meshes(), wmtk::components::multimesh::MeshCollection::get_mesh(), wmtk::Mesh::get_multi_mesh_root(), wmtk::components::isotropic_remeshing::Pass::iterations, wmtk::logger(), m_collapse, m_operations, m_options, m_swap, wmtk::operations::Operation::mesh(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::mesh_collection, wmtk::components::isotropic_remeshing::Pass::mesh_path, wmtk::SchedulerStats::number_of_failed_operations(), wmtk::SchedulerStats::number_of_performed_operations(), wmtk::SchedulerStats::number_of_successful_operations(), wmtk::components::isotropic_remeshing::Pass::operations, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::position_attribute, wmtk::Scheduler::run_operation_on_all(), wmtk::SchedulerStats::sorting_time, and wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::start_with_collapse.
Member Data Documentation
m_collapse
std::shared_ptr<operations::EdgeCollapse> wmtk::components::isotropic_remeshing::IsotropicRemeshing::m_collapse private
Definition at line 46 of file IsotropicRemeshing.hpp.
Referenced by configure_collapse(), IsotropicRemeshing(), run(), and run().
m_envelope_invariants
std::shared_ptr<wmtk::invariants::InvariantCollection> wmtk::components::isotropic_remeshing::IsotropicRemeshing::m_envelope_invariants private
Definition at line 55 of file IsotropicRemeshing.hpp.
Referenced by configure_collapse(), configure_smooth(), configure_split(), configure_swap(), and make_envelopes().
m_interior_edge_invariants
std::shared_ptr<wmtk::invariants::InvariantCollection> wmtk::components::isotropic_remeshing::IsotropicRemeshing::m_interior_edge_invariants private
Definition at line 58 of file IsotropicRemeshing.hpp.
Referenced by make_interior_invariants().
m_interior_position_invariants
std::shared_ptr<wmtk::invariants::InvariantCollection> wmtk::components::isotropic_remeshing::IsotropicRemeshing::m_interior_position_invariants private
Definition at line 57 of file IsotropicRemeshing.hpp.
Referenced by configure_smooth(), configure_split(), and make_interior_invariants().
m_operation_transfers
std::vector<std::shared_ptr<wmtk::operations::AttributeTransferStrategyBase> > wmtk::components::isotropic_remeshing::IsotropicRemeshing::m_operation_transfers private
Definition at line 51 of file IsotropicRemeshing.hpp.
Referenced by configure_collapse(), configure_smooth(), configure_split(), configure_swap(), and IsotropicRemeshing().
m_operations
std::map<std::string, std::shared_ptr<operations::Operation> > wmtk::components::isotropic_remeshing::IsotropicRemeshing::m_operations private
Definition at line 53 of file IsotropicRemeshing.hpp.
Referenced by IsotropicRemeshing(), and run().
m_options
IsotropicRemeshingOptions wmtk::components::isotropic_remeshing::IsotropicRemeshing::m_options private
Definition at line 42 of file IsotropicRemeshing.hpp.
Referenced by all_envelope_positions(), configure_collapse(), configure_smooth(), configure_split(), configure_swap(), IsotropicRemeshing(), make_envelopes(), make_interior_invariants(), run(), and run().
m_smooth
std::shared_ptr<operations::Operation> wmtk::components::isotropic_remeshing::IsotropicRemeshing::m_smooth private
Definition at line 48 of file IsotropicRemeshing.hpp.
Referenced by configure_smooth(), IsotropicRemeshing(), and run().
m_split
std::shared_ptr<operations::EdgeSplit> wmtk::components::isotropic_remeshing::IsotropicRemeshing::m_split private
Definition at line 45 of file IsotropicRemeshing.hpp.
Referenced by configure_split(), IsotropicRemeshing(), and run().
m_swap
std::shared_ptr<operations::composite::EdgeSwap> wmtk::components::isotropic_remeshing::IsotropicRemeshing::m_swap private
Definition at line 47 of file IsotropicRemeshing.hpp.
Referenced by configure_swap(), IsotropicRemeshing(), run(), and run().
m_universal_invariants
std::shared_ptr<wmtk::invariants::InvariantCollection> wmtk::components::isotropic_remeshing::IsotropicRemeshing::m_universal_invariants private
Definition at line 59 of file IsotropicRemeshing.hpp.
Referenced by configure_collapse(), configure_swap(), and IsotropicRemeshing().
The documentation for this class was generated from the following files:
components/isotropic_remeshing/wmtk/components/isotropic_remeshing/IsotropicRemeshing.hpp
components/isotropic_remeshing/wmtk/components/isotropic_remeshing/IsotropicRemeshing.cpp
components/isotropic_remeshing/wmtk/components/isotropic_remeshing/IsotropicRemeshing_collapse.cpp
components/isotropic_remeshing/wmtk/components/isotropic_remeshing/IsotropicRemeshing_smooth.cpp
components/isotropic_remeshing/wmtk/components/isotropic_remeshing/IsotropicRemeshing_split.cpp
components/isotropic_remeshing/wmtk/components/isotropic_remeshing/IsotropicRemeshing_swap.cpp