Wildmeshing Toolkit: wmtk::operations::composite::CollapseAndUpdateVertex Class Reference
wmtk::operations::composite::CollapseAndUpdateVertex Class Reference
#include <CollapseAndUpdateVertex.hpp>
Public Member Functions
CollapseAndUpdateVertex (Mesh &m)
CollapseAndUpdateVertex (Mesh &m, std::shared_ptr< EdgeCollapse > collapse, std::shared_ptr< Operation > vertex_op={})
PrimitiveType primitive_type () const override
EdgeCollapse & collapse ()
Operation & vertex_update ()
const EdgeCollapse & collapse () const
const Operation & vertex_update () const
void set_vertex_update (std::shared_ptr< Operation > op)
std::vector< simplex::Simplex > unmodified_primitives (const simplex::Simplex &simplex) const override
Returns all simplices that will be potentially affected by the operation.
std::vector< simplex::Simplex > execute (const simplex::Simplex &simplex) override
returns an empty vector in case of failure
Public Member Functions inherited from wmtk::operations::Operation
Operation (Mesh &mesh)
virtual ~Operation ()
virtual std::vector< simplex::Simplex > operator() (const simplex::Simplex &simplex)
virtual double priority (const simplex::Simplex &simplex) const
virtual bool use_random_priority () const
virtual bool & use_random_priority ()
const Mesh & mesh () const
Mesh & mesh ()
void add_invariant (std::shared_ptr< Invariant > invariant)
void set_priority (const std::function< double(const simplex::Simplex &)> &func)
std::shared_ptr< const operations::AttributeTransferStrategyBase > get_transfer_strategy (const attribute::MeshAttributeHandle &attribute)
void add_transfer_strategy (const std::shared_ptr< const operations::AttributeTransferStrategyBase > &other)
void set_transfer_strategy (const attribute::MeshAttributeHandle &attribute, const std::shared_ptr< const operations::AttributeTransferStrategyBase > &other)
void clear_attribute_transfer_strategies ()
virtual void reserve_enough_simplices ()
Protected Attributes
std::shared_ptr< EdgeCollapse > m_collapse
std::shared_ptr< Operation > m_vertex_update
Protected Attributes inherited from wmtk::operations::Operation
std::function< double(const simplex::Simplex &)> m_priority = nullptr
invariants::InvariantCollection m_invariants
std::vector< std::shared_ptr< const operations::AttributeTransferStrategyBase > > m_attr_transfer_strategies
Additional Inherited Members
Protected Member Functions inherited from wmtk::operations::Operation
virtual bool before (const simplex::Simplex &simplex) const
virtual bool after (const std::vector< simplex::Simplex > &unmods, const std::vector< simplex::Simplex > &mods) const
void apply_attribute_transfer (const std::vector< simplex::Simplex > &direct_mods)
Detailed Description
Definition at line 9 of file CollapseAndUpdateVertex.hpp.
Constructor & Destructor Documentation
CollapseAndUpdateVertex() [1/2]
wmtk::operations::composite::CollapseAndUpdateVertex::CollapseAndUpdateVertex (Mesh & m)
Definition at line 7 of file CollapseAndUpdateVertex.cpp.
CollapseAndUpdateVertex() [2/2]
wmtk::operations::composite::CollapseAndUpdateVertex::CollapseAndUpdateVertex (Mesh & m, std::shared_ptr< EdgeCollapse > collapse, std::shared_ptr< Operation > vertex_op = {})
Definition at line 10 of file CollapseAndUpdateVertex.cpp.
References m_vertex_update, and wmtk::Vertex.
Member Function Documentation
collapse() [1/2]
EdgeCollapse & wmtk::operations::composite::CollapseAndUpdateVertex::collapse () inline
Definition at line 19 of file CollapseAndUpdateVertex.hpp.
References m_collapse.
Referenced by execute().
collapse() [2/2]
const EdgeCollapse & wmtk::operations::composite::CollapseAndUpdateVertex::collapse () const inline
Definition at line 21 of file CollapseAndUpdateVertex.hpp.
References m_collapse.
execute()
std::vector< simplex::Simplex > wmtk::operations::composite::CollapseAndUpdateVertex::execute (const simplex::Simplex & simplex) override virtual
returns an empty vector in case of failure
Implements wmtk::operations::Operation.
Definition at line 29 of file CollapseAndUpdateVertex.cpp.
References collapse(), wmtk::Edge, m_vertex_update, wmtk::operations::Operation::mesh(), wmtk::simplex::Simplex::primitive_type(), wmtk::simplex::Simplex::vertex(), and vertex_update().
primitive_type()
PrimitiveType wmtk::operations::composite::CollapseAndUpdateVertex::primitive_type () const inline override virtual
Implements wmtk::operations::Operation.
Definition at line 18 of file CollapseAndUpdateVertex.hpp.
References wmtk::Edge.
set_vertex_update()
void wmtk::operations::composite::CollapseAndUpdateVertex::set_vertex_update (std::shared_ptr< Operation > op)
Definition at line 23 of file CollapseAndUpdateVertex.cpp.
References m_vertex_update, and wmtk::Vertex.
unmodified_primitives()
std::vector< simplex::Simplex > wmtk::operations::composite::CollapseAndUpdateVertex::unmodified_primitives (const simplex::Simplex & simplex) const override virtual
Returns all simplices that will be potentially affected by the operation.
Implements wmtk::operations::Operation.
Definition at line 54 of file CollapseAndUpdateVertex.cpp.
vertex_update() [1/2]
Operation & wmtk::operations::composite::CollapseAndUpdateVertex::vertex_update () inline
Definition at line 20 of file CollapseAndUpdateVertex.hpp.
References m_vertex_update.
Referenced by execute().
vertex_update() [2/2]
const Operation & wmtk::operations::composite::CollapseAndUpdateVertex::vertex_update () const inline
Definition at line 22 of file CollapseAndUpdateVertex.hpp.
References m_vertex_update.
Member Data Documentation
m_collapse
std::shared_ptr<EdgeCollapse> wmtk::operations::composite::CollapseAndUpdateVertex::m_collapse protected
Definition at line 31 of file CollapseAndUpdateVertex.hpp.
Referenced by collapse(), and collapse().
m_vertex_update
std::shared_ptr<Operation> wmtk::operations::composite::CollapseAndUpdateVertex::m_vertex_update protected
Definition at line 32 of file CollapseAndUpdateVertex.hpp.
Referenced by CollapseAndUpdateVertex(), execute(), set_vertex_update(), vertex_update(), and vertex_update().
The documentation for this class was generated from the following files:
src/wmtk/operations/composite/CollapseAndUpdateVertex.hpp
src/wmtk/operations/composite/CollapseAndUpdateVertex.cpp