Wildmeshing Toolkit: wmtk::utils::internal::IndexSimplexMapper Class Reference
wmtk::utils::internal::IndexSimplexMapper Class Reference
#include <IndexSimplexMapper.hpp>
Public Member Functions
IndexSimplexMapper (Eigen::Ref< const MatrixXl > S)
IndexSimplexMapper (const Mesh &mesh)
template<int Dim, int ChildDim>
std::vector< int64_t > faces (size_t index) const
std::vector< int64_t > faces (size_t index, int8_t dim, int8_t child_dim) const
template<int D>
const std::map< std::array< int64_t, D+1 >, wmtk::dart::Dart > & simplex_dart_map () const
template<int D>
std::map< std::array< int64_t, D+1 >, int64_t > simplex_map () const
template<int D>
const std::vector< std::array< int64_t, D+1 > > & simplices () const
template<size_t Dim>
int64_t get_index (const std::array< int64_t, Dim > &s) const
template<size_t Dim>
dart::Dart get_internal_dart (const std::array< int64_t, Dim > &s) const
template<size_t Dim>
dart::Dart get_dart (const std::array< int64_t, Dim > &s) const
template<size_t Dim>
dart::Dart get_mesh_dart (const std::array< int64_t, Dim > &s) const
template<size_t Dim>
wmtk::Tuple get_tuple (const std::array< int64_t, Dim > &s) const
template<int Dim>
auto get_input_dart (const std::array< int64_t, Dim > &s, const std::map< std::array< int64_t, Dim >, dart::Dart > &mp) -> const dart::Dart &
template<size_t Dim>
auto get_internal_dart (const std::array< int64_t, Dim > &s) const -> dart::Dart
template<size_t Dim>
auto get_dart (const std::array< int64_t, Dim > &s) const -> dart::Dart
template<size_t Dim>
auto get_mesh_dart (const std::array< int64_t, Dim > &s) const -> dart::Dart
template<size_t Dim>
Tuple get_tuple (const std::array< int64_t, Dim > &s) const
Static Public Member Functions
static int64_t id (const simplex::IdSimplex &s)
Private Member Functions
void initialize_edge_mesh (Eigen::Ref< const RowVectors2l > S)
void initialize_tri_mesh (Eigen::Ref< const RowVectors3l > S)
void initialize_tet_mesh (Eigen::Ref< const RowVectors4l > S)
template<int Dim>
void initialize (Eigen::Ref< const RowVectors< int64_t, Dim > > S)
template<int Dim, int ChildDim>
std::map< std::array< int64_t, ChildDim >, wmtk::dart::Dart > make_child_map (std::vector< std::array< int64_t, Dim > > S) const
void update_simplices ()
template<>
void initialize (Eigen::Ref< const RowVectors2l > S)
template<>
void initialize (Eigen::Ref< const RowVectors3l > S)
template<>
void initialize (Eigen::Ref< const RowVectors4l > S)
Static Private Member Functions
template<int Dim>
static auto get_input_dart (const std::array< int64_t, Dim > &s, const std::map< std::array< int64_t, Dim >, wmtk::dart::Dart > &mp) -> const dart::Dart &
template<int Dim>
static auto get_input_dart (Eigen::Ref< const RowVector< int64_t, Dim > > S, const std::map< std::array< int64_t, Dim >, wmtk::dart::Dart > &mp) -> const dart::Dart &
template<int Dim>
static std::map< std::array< int64_t, Dim >, wmtk::dart::Dart > make_map (std::vector< std::array< int64_t, Dim > > S)
Private Attributes
int8_t m_simplex_dimension
std::map< std::array< int64_t, 1 >, wmtk::dart::Dart > m_V_map
std::map< std::array< int64_t, 2 >, wmtk::dart::Dart > m_E_map
std::map< std::array< int64_t, 3 >, wmtk::dart::Dart > m_F_map
std::map< std::array< int64_t, 4 >, wmtk::dart::Dart > m_T_map
std::vector< std::array< int64_t, 1 > > m_V
std::vector< std::array< int64_t, 2 > > m_E
std::vector< std::array< int64_t, 3 > > m_F
std::vector< std::array< int64_t, 4 > > m_T
Mesh const * m_mesh = nullptr
Detailed Description
Definition at line 24 of file IndexSimplexMapper.hpp.
Constructor & Destructor Documentation
IndexSimplexMapper() [1/2]
wmtk::utils::internal::IndexSimplexMapper::IndexSimplexMapper (Eigen::Ref< const MatrixXl > S)
Definition at line 211 of file IndexSimplexMapper.cpp.
References initialize_edge_mesh(), initialize_tet_mesh(), initialize_tri_mesh(), and m_simplex_dimension.
IndexSimplexMapper() [2/2]
wmtk::utils::internal::IndexSimplexMapper::IndexSimplexMapper (const Mesh & mesh)
Definition at line 199 of file IndexSimplexMapper.cpp.
References initialize_edge_mesh(), initialize_tet_mesh(), initialize_tri_mesh(), and m_simplex_dimension.
Member Function Documentation
faces() [1/2]
template<int Dim, int ChildDim> std::vector< int64_t > wmtk::utils::internal::IndexSimplexMapper::faces (size_t index) const
Definition at line 484 of file IndexSimplexMapper.cpp.
References faces().
Referenced by faces().
faces() [2/2]
std::vector< int64_t > wmtk::utils::internal::IndexSimplexMapper::faces (size_t index, int8_t dim, int8_t child_dim) const
Definition at line 506 of file IndexSimplexMapper.cpp.
get_dart() [1/2]
template<size_t Dim> dart::Dart wmtk::utils::internal::IndexSimplexMapper::get_dart (const std::array< int64_t, Dim > & s) const
get_dart() [2/2]
template<size_t Dim> auto wmtk::utils::internal::IndexSimplexMapper::get_dart (const std::array< int64_t, Dim > & s) const -> dart::Dart
Definition at line 451 of file IndexSimplexMapper.cpp.
get_index()
template<size_t Dim> template int64_t wmtk::utils::internal::IndexSimplexMapper::get_index< 4 > (const std::array< int64_t, Dim > & s) const
Definition at line 405 of file IndexSimplexMapper.cpp.
References wmtk::Mesh::get_id_simplex(), wmtk::get_primitive_type_from_id(), get_tuple(), wmtk::simplex::IdSimplex::index(), and m_mesh.
Referenced by wmtk::utils::internal::cofacets().
get_input_dart() [1/3]
template<int Dim> auto wmtk::utils::internal::IndexSimplexMapper::get_input_dart (const std::array< int64_t, Dim > & s, const std::map< std::array< int64_t, Dim >, dart::Dart > & mp) -> const dart::Dart&
Definition at line 385 of file IndexSimplexMapper.cpp.
get_input_dart() [2/3]
template<int Dim> static auto wmtk::utils::internal::IndexSimplexMapper::get_input_dart (const std::array< int64_t, Dim > & s, const std::map< std::array< int64_t, Dim >, wmtk::dart::Dart > & mp) -> const dart::Dart & static private
get_input_dart() [3/3]
template<int Dim> static auto wmtk::utils::internal::IndexSimplexMapper::get_input_dart (Eigen::Ref< const RowVector< int64_t, Dim > > S, const std::map< std::array< int64_t, Dim >, wmtk::dart::Dart > & mp) -> const dart::Dart & static private
get_internal_dart() [1/2]
template<size_t Dim> dart::Dart wmtk::utils::internal::IndexSimplexMapper::get_internal_dart (const std::array< int64_t, Dim > & s) const
get_internal_dart() [2/2]
template<size_t Dim> auto wmtk::utils::internal::IndexSimplexMapper::get_internal_dart (const std::array< int64_t, Dim > & s) const -> dart::Dart
Definition at line 428 of file IndexSimplexMapper.cpp.
References wmtk::dart::utils::from_vertex_permutation(), wmtk::get_primitive_type_from_id(), and wmtk::dart::SimplexDart::get_singleton().
get_mesh_dart() [1/2]
template<size_t Dim> dart::Dart wmtk::utils::internal::IndexSimplexMapper::get_mesh_dart (const std::array< int64_t, Dim > & s) const
Referenced by get_tuple().
get_mesh_dart() [2/2]
template<size_t Dim> auto wmtk::utils::internal::IndexSimplexMapper::get_mesh_dart (const std::array< int64_t, Dim > & s) const -> dart::Dart
Definition at line 459 of file IndexSimplexMapper.cpp.
References wmtk::dart::utils::from_vertex_permutation(), wmtk::get_primitive_type_from_id(), and wmtk::dart::SimplexDart::get_singleton().
get_tuple() [1/2]
template<size_t Dim> Tuple wmtk::utils::internal::IndexSimplexMapper::get_tuple (const std::array< int64_t, Dim > & s) const
Definition at line 476 of file IndexSimplexMapper.cpp.
References get_mesh_dart(), wmtk::get_primitive_type_from_id(), wmtk::dart::SimplexDart::get_singleton(), and m_simplex_dimension.
get_tuple() [2/2]
template<size_t Dim> wmtk::Tuple wmtk::utils::internal::IndexSimplexMapper::get_tuple (const std::array< int64_t, Dim > & s) const
Referenced by wmtk::components::multimesh::from_vertex_simplices_map_(), and get_index().
id()
int64_t wmtk::utils::internal::IndexSimplexMapper::id (const simplex::IdSimplex & s) static
Definition at line 222 of file IndexSimplexMapper.cpp.
initialize() [1/4]
template<> void wmtk::utils::internal::IndexSimplexMapper::initialize (Eigen::Ref< const RowVectors2l > S) private
Definition at line 227 of file IndexSimplexMapper.cpp.
References m_E, m_E_map, m_V_map, and update_simplices().
initialize() [2/4]
template<> void wmtk::utils::internal::IndexSimplexMapper::initialize (Eigen::Ref< const RowVectors3l > S) private
Definition at line 239 of file IndexSimplexMapper.cpp.
References m_E_map, m_F, m_F_map, m_V_map, and update_simplices().
initialize() [3/4]
template<> void wmtk::utils::internal::IndexSimplexMapper::initialize (Eigen::Ref< const RowVectors4l > S) private
Definition at line 252 of file IndexSimplexMapper.cpp.
References m_E_map, m_F_map, m_T, m_T_map, m_V_map, and update_simplices().
initialize() [4/4]
template<int Dim> void wmtk::utils::internal::IndexSimplexMapper::initialize (Eigen::Ref< const RowVectors< int64_t, Dim > > S) private
initialize_edge_mesh()
void wmtk::utils::internal::IndexSimplexMapper::initialize_edge_mesh (Eigen::Ref< const RowVectors2l > S) private
Definition at line 234 of file IndexSimplexMapper.cpp.
Referenced by IndexSimplexMapper(), and IndexSimplexMapper().
initialize_tet_mesh()
void wmtk::utils::internal::IndexSimplexMapper::initialize_tet_mesh (Eigen::Ref< const RowVectors4l > S) private
Definition at line 262 of file IndexSimplexMapper.cpp.
Referenced by IndexSimplexMapper(), and IndexSimplexMapper().
initialize_tri_mesh()
void wmtk::utils::internal::IndexSimplexMapper::initialize_tri_mesh (Eigen::Ref< const RowVectors3l > S) private
Definition at line 247 of file IndexSimplexMapper.cpp.
Referenced by IndexSimplexMapper(), and IndexSimplexMapper().
make_child_map()
template<int Dim, int ChildDim> std::map< std::array< int64_t, ChildDim >, wmtk::dart::Dart > wmtk::utils::internal::IndexSimplexMapper::make_child_map (std::vector< std::array< int64_t, Dim > > S) const private
Definition at line 268 of file IndexSimplexMapper.cpp.
References m_mesh.
make_map()
template<int Dim> std::map< std::array< int64_t, Dim >, wmtk::dart::Dart > wmtk::utils::internal::IndexSimplexMapper::make_map (std::vector< std::array< int64_t, Dim > > S) static private
Definition at line 280 of file IndexSimplexMapper.cpp.
References wmtk::dart::utils::from_vertex_permutation(), and wmtk::get_primitive_type_from_id().
simplex_dart_map()
template<int D> template const std::map< std::array< int64_t, 3+1 >, dart::Dart > & wmtk::utils::internal::IndexSimplexMapper::simplex_dart_map< 3 > () const
Definition at line 530 of file IndexSimplexMapper.cpp.
References m_E_map, m_F_map, m_T_map, and m_V_map.
simplex_map()
template<int D> std::map< std::array< int64_t, D+1 >, int64_t > wmtk::utils::internal::IndexSimplexMapper::simplex_map () const
Definition at line 125 of file IndexSimplexMapper.hpp.
simplices()
template<int D> template const std::vector< std::array< int64_t, 3+1 > > & wmtk::utils::internal::IndexSimplexMapper::simplices< 3 > () const
Definition at line 544 of file IndexSimplexMapper.cpp.
References m_E, m_F, m_T, and m_V.
Referenced by wmtk::utils::internal::boundary_manifold_decomposition().
update_simplices()
void wmtk::utils::internal::IndexSimplexMapper::update_simplices () private
Definition at line 300 of file IndexSimplexMapper.cpp.
References wmtk::Mesh::get_all(), wmtk::get_primitive_type_from_id(), wmtk::dart::SimplexDart::get_singleton(), m_E, m_E_map, m_F, m_F_map, m_mesh, m_T, m_T_map, m_V, m_V_map, and wmtk::Mesh::top_simplex_type().
Referenced by initialize(), initialize(), and initialize().
Member Data Documentation
m_E
std::vector<std::array<int64_t, 2> > wmtk::utils::internal::IndexSimplexMapper::m_E private
Definition at line 80 of file IndexSimplexMapper.hpp.
Referenced by initialize(), simplices(), and update_simplices().
m_E_map
std::map<std::array<int64_t, 2>, wmtk::dart::Dart> wmtk::utils::internal::IndexSimplexMapper::m_E_map private
Definition at line 73 of file IndexSimplexMapper.hpp.
Referenced by initialize(), initialize(), initialize(), simplex_dart_map(), and update_simplices().
m_F
std::vector<std::array<int64_t, 3> > wmtk::utils::internal::IndexSimplexMapper::m_F private
Definition at line 81 of file IndexSimplexMapper.hpp.
Referenced by initialize(), simplices(), and update_simplices().
m_F_map
std::map<std::array<int64_t, 3>, wmtk::dart::Dart> wmtk::utils::internal::IndexSimplexMapper::m_F_map private
Definition at line 74 of file IndexSimplexMapper.hpp.
Referenced by initialize(), initialize(), simplex_dart_map(), and update_simplices().
m_mesh
Mesh const* wmtk::utils::internal::IndexSimplexMapper::m_mesh = nullptr private
Definition at line 84 of file IndexSimplexMapper.hpp.
Referenced by get_index(), make_child_map(), and update_simplices().
m_simplex_dimension
int8_t wmtk::utils::internal::IndexSimplexMapper::m_simplex_dimension private
Definition at line 70 of file IndexSimplexMapper.hpp.
Referenced by get_tuple(), IndexSimplexMapper(), and IndexSimplexMapper().
m_T
std::vector<std::array<int64_t, 4> > wmtk::utils::internal::IndexSimplexMapper::m_T private
Definition at line 82 of file IndexSimplexMapper.hpp.
Referenced by initialize(), simplices(), and update_simplices().
m_T_map
std::map<std::array<int64_t, 4>, wmtk::dart::Dart> wmtk::utils::internal::IndexSimplexMapper::m_T_map private
Definition at line 75 of file IndexSimplexMapper.hpp.
Referenced by initialize(), simplex_dart_map(), and update_simplices().
m_V
std::vector<std::array<int64_t, 1> > wmtk::utils::internal::IndexSimplexMapper::m_V private
Definition at line 79 of file IndexSimplexMapper.hpp.
Referenced by simplices(), and update_simplices().
m_V_map
std::map<std::array<int64_t, 1>, wmtk::dart::Dart> wmtk::utils::internal::IndexSimplexMapper::m_V_map private
Definition at line 72 of file IndexSimplexMapper.hpp.
Referenced by initialize(), initialize(), initialize(), simplex_dart_map(), and update_simplices().
The documentation for this class was generated from the following files:
src/wmtk/utils/internal/IndexSimplexMapper.hpp
src/wmtk/utils/internal/IndexSimplexMapper.cpp