Wildmeshing Toolkit: wmtk::dart::DartAccessor< Dim, MeshType > Class Template Reference
wmtk::dart::DartAccessor< Dim, MeshType > Class Template Reference
#include <DartAccessor.hpp>
Public Types
using IndexBaseType = DartIndexAccessor< Dim, MeshType >
Public Types inherited from wmtk::dart::DartIndexAccessor< Dim, MeshType >
using BaseAccessor = wmtk::attribute::Accessor< int64_t, MeshType, attribute::CachingAttribute< int64_t >, Dim+1 >
Public Member Functions
template<typename IT , typename OT >
dart::SimplexAdjacency< Dim > & operator[] (const dart::_Dart< IT, OT > &t)
template<typename IT , typename OT >
const dart::SimplexAdjacency< Dim > & operator[] (const dart::_Dart< IT, OT > &t) const
size_t size () const
wmtk::attribute::MeshAttributeHandle handle () const
const MeshType & mesh () const
Public Member Functions inherited from wmtk::dart::DartIndexAccessor< Dim, MeshType >
DartIndexAccessor (BaseAccessor acc)
DartIndexAccessor (const MeshType &mesh, const wmtk::attribute::MeshAttributeHandle &mah)
DartIndexAccessor (const MeshType &mesh, const wmtk::attribute::TypedAttributeHandle< int64_t > &h)
template<typename MeshType2 >
DartIndexAccessor (const DartIndexAccessor< Dim, MeshType2 > &o)
wmtk::attribute::MeshAttributeHandle handle () const
dart::SimplexAdjacency< Dim > & operator[] (int64_t index)
const dart::SimplexAdjacency< Dim > & operator[] (int64_t index) const
const MeshType & mesh () const
size_t size () const
Static Public Member Functions
static wmtk::attribute::TypedAttributeHandle< int64_t > register_attribute (MeshType &m, const std::string_view &name, PrimitiveType pt)
Protected Attributes
BaseAccessor m_base_accessor
Protected Attributes inherited from wmtk::dart::DartIndexAccessor< Dim, MeshType >
BaseAccessor m_base_accessor
Friends
class wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor
Detailed Description
template<int Dim, typename MeshType>
class wmtk::dart::DartAccessor< Dim, MeshType >
Definition at line 68 of file DartAccessor.hpp.
Member Typedef Documentation
IndexBaseType
template<int Dim, typename MeshType > using wmtk::dart::DartAccessor< Dim, MeshType >::IndexBaseType = DartIndexAccessor<Dim, MeshType>
Definition at line 71 of file DartAccessor.hpp.
Member Function Documentation
handle()
template<int Dim, typename MeshType > wmtk::attribute::MeshAttributeHandle wmtk::dart::DartIndexAccessor< Dim, MeshType >::handle () const inline
Definition at line 45 of file DartAccessor.hpp.
Referenced by wmtk::dart::DartAccessor< Dim, MeshType >::register_attribute().
mesh()
template<int Dim, typename MeshType > const MeshType & wmtk::dart::DartIndexAccessor< Dim, MeshType >::mesh () const inline
Definition at line 58 of file DartAccessor.hpp.
Referenced by wmtk::multimesh::MultiMeshManager::map_tuple_between_meshes(), wmtk::multimesh::utils::internal::print_all_mapped_tuples(), wmtk::multimesh::utils::symmetric_write_tuple_map_attributes(), and wmtk::multimesh::utils::symmetric_write_tuple_map_attributes().
operator[]() [1/2]
template<int Dim, typename MeshType > template<typename IT , typename OT > dart::SimplexAdjacency< Dim > & wmtk::dart::DartAccessor< Dim, MeshType >::operator[] (const dart::_Dart< IT, OT > & t) inline
Definition at line 96 of file DartAccessor.hpp.
References wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::index(), wmtk::dart::DartAccessor< Dim, MeshType >::m_base_accessor, and wmtk::dart::DartIndexAccessor< Dim, MeshType >::operator[]().
operator[]() [2/2]
template<int Dim, typename MeshType > template<typename IT , typename OT > const dart::SimplexAdjacency< Dim > & wmtk::dart::DartAccessor< Dim, MeshType >::operator[] (const dart::_Dart< IT, OT > & t) const inline
Definition at line 101 of file DartAccessor.hpp.
References wmtk::attribute::Accessor< T, MeshType, AttributeType_, Dim >::index(), wmtk::dart::DartAccessor< Dim, MeshType >::m_base_accessor, and wmtk::dart::DartIndexAccessor< Dim, MeshType >::operator[]().
register_attribute()
template<int Dim, typename MeshType > static wmtk::attribute::TypedAttributeHandle< int64_t > wmtk::dart::DartAccessor< Dim, MeshType >::register_attribute (MeshType & m, const std::string_view & name, PrimitiveType pt) inline static
Definition at line 87 of file DartAccessor.hpp.
References wmtk::dart::DartAccessor< Dim, MeshType >::handle().
Referenced by wmtk::dart::register_dart_attribute().
size()
template<int Dim, typename MeshType > size_t wmtk::dart::DartIndexAccessor< Dim, MeshType >::size () const inline
Definition at line 60 of file DartAccessor.hpp.
Referenced by wmtk::dart::utils::indexed_topology_initialization().
Friends And Related Symbol Documentation
wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor
template<int Dim, typename MeshType > friend class wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor friend
Definition at line 83 of file DartAccessor.hpp.
Member Data Documentation
m_base_accessor
template<int Dim, typename MeshType > BaseAccessor wmtk::dart::DartIndexAccessor< Dim, MeshType >::m_base_accessor protected
Definition at line 64 of file DartAccessor.hpp.
Referenced by wmtk::dart::DartAccessor< Dim, MeshType >::operator[](), and wmtk::dart::DartAccessor< Dim, MeshType >::operator[]().
The documentation for this class was generated from the following files:
src/wmtk/attribute/Accessor.hpp
src/wmtk/dart/DartAccessor.hpp