Wildmeshing Toolkit: wmtk::components::envelope::Envelope Class Reference
wmtk::components::envelope::Envelope Class Reference abstract
#include <Envelope.hpp>
Public Member Functions
virtual ~Envelope ()
virtual bool is_inside (const Vector3d &p) const =0
virtual bool is_inside (const Vector3r &p) const =0
virtual bool is_inside (const Mesh &m, const Tuple &tuple, const PrimitiveType pt) const =0
bool is_inside (const Mesh &m, const std::vector< Tuple > &simplices, const PrimitiveType pt) const
bool is_inside (const Mesh &m, const std::vector< Tuple > &simplices) const
Detailed Description
Definition at line 12 of file Envelope.hpp.
Constructor & Destructor Documentation
~Envelope()
wmtk::components::envelope::Envelope::~Envelope () virtual default
Member Function Documentation
is_inside() [1/5]
bool wmtk::components::envelope::Envelope::is_inside (const Mesh & m, const std::vector< Tuple > & simplices) const
Definition at line 6 of file Envelope.cpp.
References is_inside(), and wmtk::Mesh::top_simplex_type().
is_inside() [2/5]
bool wmtk::components::envelope::Envelope::is_inside (const Mesh & m, const std::vector< Tuple > & simplices, const PrimitiveType pt) const
Definition at line 10 of file Envelope.cpp.
References is_inside().
is_inside() [3/5]
virtual bool wmtk::components::envelope::Envelope::is_inside (const Mesh & m, const Tuple & tuple, const PrimitiveType pt) const pure virtual
is_inside() [4/5]
virtual bool wmtk::components::envelope::Envelope::is_inside (const Vector3d & p) const pure virtual
Implemented in wmtk::components::envelope::BVHEnvelope, and wmtk::components::envelope::FastEnvelope.
Referenced by is_inside(), and is_inside().
is_inside() [5/5]
virtual bool wmtk::components::envelope::Envelope::is_inside (const Vector3r & p) const pure virtual
Implemented in wmtk::components::envelope::BVHEnvelope, and wmtk::components::envelope::FastEnvelope.
The documentation for this class was generated from the following files:
components/envelope/src/wmtk/components/envelope/Envelope.hpp
components/envelope/src/wmtk/components/envelope/Envelope.cpp