Wildmeshing Toolkit: wmtk::operations::EdgeOperationData Class Reference
wmtk::operations::EdgeOperationData Class Reference
#include <EdgeOperationData.hpp>
Public Member Functions
EdgeOperationData (Mesh &m, const Tuple &operating_tuple)
~EdgeOperationData ()
EdgeOperationData (EdgeOperationData &&)
int64_t operating_edge_id () const
const std::array< int64_t, 2 > & incident_vids () const
void delete_simplices ()
void set_split ()
void set_collapse ()
void set_split (const Mesh &m, const Tuple &t)
void set_collapse (const Mesh &m, const Tuple &t)
void set_split (const Mesh &m, const Tuple &t, const std::vector< Tuple > &ts)
void set_collapse (const Mesh &m, const Tuple &t, const std::vector< Tuple > &ts)
const internal::SplitAlternateFacetData & const_split_facet_data () const
Returns facet data held if the edge operation was a split - throws if data does not exist.
const internal::CollapseAlternateFacetData & const_collapse_facet_data () const
Returns facet data held if the edge operation was a collapse- throws if data does not exist.
Tuple get_alternative (const PrimitiveType mesh_pt, const Tuple &t) const
Public Attributes
Mesh & m_mesh
Tuple m_operating_tuple
int64_t m_input_edge_gid
Tuple m_output_tuple
std::array< int64_t, 2 > m_spine_vids
std::vector< std::vector< Tuple > > split_boundary_complex
std::vector< std::vector< int64_t > > global_ids_to_update
std::array< std::vector< int64_t >, 4 > simplex_ids_to_delete
std::variant< std::unique_ptr< internal::SplitAlternateFacetData >, std::unique_ptr< internal::CollapseAlternateFacetData > > m_op_data
Protected Member Functions
internal::SplitAlternateFacetData & split_facet_data ()
Returns facet data held if the edge operation was a split - throws if data does not exist.
internal::CollapseAlternateFacetData & collapse_facet_data ()
Returns facet data held if the edge operation was a collapse- throws if data does not exist.
Static Protected Member Functions
static Tuple tuple_from_id (const Mesh &m, const PrimitiveType type, const int64_t gid)
static simplex::Simplex simplex_from_id (const Mesh &m, const PrimitiveType type, const int64_t gid)
static std::vector< int64_t > request_simplex_indices (Mesh &mesh, const PrimitiveType type, int64_t count)
Friends
class internal::SplitAlternateFacetData
class internal::CollapseAlternateFacetData
Detailed Description
Definition at line 19 of file EdgeOperationData.hpp.
Constructor & Destructor Documentation
EdgeOperationData() [1/2]
wmtk::operations::EdgeOperationData::EdgeOperationData (Mesh & m, const Tuple & operating_tuple)
Definition at line 13 of file EdgeOperationData.cpp.
References wmtk::Mesh::id(), m_mesh, m_operating_tuple, wmtk::Mesh::switch_tuple(), and wmtk::Vertex.
~EdgeOperationData()
wmtk::operations::EdgeOperationData::~EdgeOperationData () default
EdgeOperationData() [2/2]
wmtk::operations::EdgeOperationData::EdgeOperationData (EdgeOperationData &&) default
Member Function Documentation
collapse_facet_data()
internal::CollapseAlternateFacetData & wmtk::operations::EdgeOperationData::collapse_facet_data () protected
Returns facet data held if the edge operation was a collapse- throws if data does not exist.
Definition at line 91 of file EdgeOperationData.cpp.
References m_op_data.
const_collapse_facet_data()
const internal::CollapseAlternateFacetData & wmtk::operations::EdgeOperationData::const_collapse_facet_data () const
Returns facet data held if the edge operation was a collapse- throws if data does not exist.
Definition at line 73 of file EdgeOperationData.cpp.
References m_op_data.
const_split_facet_data()
const internal::SplitAlternateFacetData & wmtk::operations::EdgeOperationData::const_split_facet_data () const
Returns facet data held if the edge operation was a split - throws if data does not exist.
Definition at line 64 of file EdgeOperationData.cpp.
References m_op_data.
delete_simplices()
void wmtk::operations::EdgeOperationData::delete_simplices ()
Definition at line 115 of file EdgeOperationData.cpp.
References wmtk::Mesh::get_flag_accessor(), wmtk::get_primitive_type_from_id(), wmtk::logger(), m_mesh, simplex_ids_to_delete, and wmtk::Mesh::top_simplex_type().
get_alternative()
Tuple wmtk::operations::EdgeOperationData::get_alternative (const PrimitiveType mesh_pt, const Tuple & t) const
Definition at line 110 of file EdgeOperationData.cpp.
References m_op_data.
incident_vids()
const std::array< int64_t, 2 > & wmtk::operations::EdgeOperationData::incident_vids () const inline
Definition at line 31 of file EdgeOperationData.hpp.
References m_spine_vids.
operating_edge_id()
int64_t wmtk::operations::EdgeOperationData::operating_edge_id () const inline
Definition at line 30 of file EdgeOperationData.hpp.
References m_input_edge_gid.
Referenced by wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator()(), and wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator()().
request_simplex_indices()
std::vector< int64_t > wmtk::operations::EdgeOperationData::request_simplex_indices (Mesh & mesh, const PrimitiveType type, int64_t count) static protected
Definition at line 101 of file EdgeOperationData.cpp.
References wmtk::Mesh::guarantee_more_attributes(), and wmtk::Mesh::request_simplex_indices().
Referenced by wmtk::operations::internal::SplitAlternateFacetData::add_facet().
set_collapse() [1/3]
void wmtk::operations::EdgeOperationData::set_collapse ()
Definition at line 41 of file EdgeOperationData.cpp.
References m_op_data.
set_collapse() [2/3]
void wmtk::operations::EdgeOperationData::set_collapse (const Mesh & m, const Tuple & t)
Definition at line 50 of file EdgeOperationData.cpp.
References m_op_data.
set_collapse() [3/3]
void wmtk::operations::EdgeOperationData::set_collapse (const Mesh & m, const Tuple & t, const std::vector< Tuple > & ts)
Definition at line 59 of file EdgeOperationData.cpp.
References m_op_data.
set_split() [1/3]
void wmtk::operations::EdgeOperationData::set_split ()
Definition at line 37 of file EdgeOperationData.cpp.
References m_op_data.
set_split() [2/3]
void wmtk::operations::EdgeOperationData::set_split (const Mesh & m, const Tuple & t)
Definition at line 46 of file EdgeOperationData.cpp.
References m_op_data.
set_split() [3/3]
void wmtk::operations::EdgeOperationData::set_split (const Mesh & m, const Tuple & t, const std::vector< Tuple > & ts)
Definition at line 55 of file EdgeOperationData.cpp.
References m_op_data.
simplex_from_id()
simplex::Simplex wmtk::operations::EdgeOperationData::simplex_from_id (const Mesh & m, const PrimitiveType type, const int64_t gid) static protected
Definition at line 33 of file EdgeOperationData.cpp.
References wmtk::Mesh::simplex_from_id().
Referenced by wmtk::operations::tet_mesh::EdgeOperationData::new_vertices(), wmtk::operations::tri_mesh::EdgeOperationData::new_vertices(), and wmtk::operations::edge_mesh::EdgeOperationData::new_vertices().
split_facet_data()
internal::SplitAlternateFacetData & wmtk::operations::EdgeOperationData::split_facet_data () protected
Returns facet data held if the edge operation was a split - throws if data does not exist.
Definition at line 82 of file EdgeOperationData.cpp.
References m_op_data.
tuple_from_id()
auto wmtk::operations::EdgeOperationData::tuple_from_id (const Mesh & m, const PrimitiveType type, const int64_t gid) static protected
Definition at line 27 of file EdgeOperationData.cpp.
Referenced by wmtk::operations::tet_mesh::EdgeOperationData::collapse_merged_ear_edges(), wmtk::operations::tri_mesh::EdgeOperationData::collapse_merged_ear_edges(), wmtk::operations::tet_mesh::EdgeOperationData::collapse_merged_ear_faces(), wmtk::operations::tet_mesh::EdgeOperationData::ear_edges(), wmtk::operations::tri_mesh::EdgeOperationData::ear_edges(), wmtk::operations::tet_mesh::EdgeOperationData::ear_faces(), wmtk::operations::tet_mesh::EdgeOperationData::split_new_rib_edges(), wmtk::operations::tri_mesh::EdgeOperationData::split_new_rib_edges(), wmtk::operations::tet_mesh::EdgeOperationData::split_new_rib_faces(), wmtk::operations::edge_mesh::EdgeOperationData::split_output_edges(), wmtk::operations::tet_mesh::EdgeOperationData::split_output_edges(), wmtk::operations::tri_mesh::EdgeOperationData::split_output_edges(), wmtk::operations::tet_mesh::EdgeOperationData::split_output_faces(), wmtk::operations::tri_mesh::EdgeOperationData::split_output_faces(), and wmtk::operations::tet_mesh::EdgeOperationData::split_output_tets().
Friends And Related Symbol Documentation
internal::CollapseAlternateFacetData
friend class internal::CollapseAlternateFacetData friend
Definition at line 23 of file EdgeOperationData.hpp.
internal::SplitAlternateFacetData
friend class internal::SplitAlternateFacetData friend
Definition at line 22 of file EdgeOperationData.hpp.
Member Data Documentation
global_ids_to_update
std::vector<std::vector<int64_t> > wmtk::operations::EdgeOperationData::global_ids_to_update
Definition at line 43 of file EdgeOperationData.hpp.
Referenced by wmtk::multimesh::MultiMeshManager::update_maps_from_edge_operation().
m_input_edge_gid
int64_t wmtk::operations::EdgeOperationData::m_input_edge_gid
Definition at line 29 of file EdgeOperationData.hpp.
Referenced by operating_edge_id(), and wmtk::multimesh::MultiMeshManager::update_maps_from_edge_operation().
m_mesh
Mesh& wmtk::operations::EdgeOperationData::m_mesh
Definition at line 27 of file EdgeOperationData.hpp.
Referenced by delete_simplices(), EdgeOperationData(), wmtk::EdgeMesh::EdgeMeshOperationExecutor::mesh(), and wmtk::EdgeMesh::EdgeMeshOperationExecutor::mesh().
m_op_data
std::variant< std::unique_ptr<internal::SplitAlternateFacetData>, std::unique_ptr<internal::CollapseAlternateFacetData> > wmtk::operations::EdgeOperationData::m_op_data
Definition at line 53 of file EdgeOperationData.hpp.
Referenced by collapse_facet_data(), const_collapse_facet_data(), const_split_facet_data(), get_alternative(), set_collapse(), set_collapse(), set_collapse(), set_split(), set_split(), set_split(), and split_facet_data().
m_operating_tuple
Tuple wmtk::operations::EdgeOperationData::m_operating_tuple
Definition at line 28 of file EdgeOperationData.hpp.
Referenced by EdgeOperationData(), wmtk::operations::edge_mesh::EdgeOperationData::input_endpoints(), wmtk::operations::tet_mesh::EdgeOperationData::input_endpoints(), and wmtk::operations::tri_mesh::EdgeOperationData::input_endpoints().
m_output_tuple
Tuple wmtk::operations::EdgeOperationData::m_output_tuple
Definition at line 33 of file EdgeOperationData.hpp.
m_spine_vids
std::array<int64_t, 2> wmtk::operations::EdgeOperationData::m_spine_vids
Definition at line 34 of file EdgeOperationData.hpp.
Referenced by incident_vids(), wmtk::operations::tet_mesh::EdgeOperationData::incident_vids(), wmtk::operations::tri_mesh::EdgeOperationData::incident_vids(), wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator()(), wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator()(), and wmtk::operations::utils::UpdateEdgeOperationMultiMeshMapFunctor::operator()().
simplex_ids_to_delete
std::array<std::vector<int64_t>, 4> wmtk::operations::EdgeOperationData::simplex_ids_to_delete
Definition at line 45 of file EdgeOperationData.hpp.
Referenced by delete_simplices().
split_boundary_complex
std::vector<std::vector<Tuple> > wmtk::operations::EdgeOperationData::split_boundary_complex
Definition at line 37 of file EdgeOperationData.hpp.
The documentation for this class was generated from the following files:
src/wmtk/operations/EdgeOperationData.hpp
src/wmtk/operations/EdgeOperationData.cpp