var dir_5ed31316642ba9bde544467a58fa3c0f =
[
    [ "fusion", "dir_a67446017ebefa442fcfc3bbfd1aa59e.html", "dir_a67446017ebefa442fcfc3bbfd1aa59e" ],
    [ "internal", "dir_26901374d6e0c8c0d0a2ff3d49830812.html", "dir_26901374d6e0c8c0d0a2ff3d49830812" ],
    [ "utils", "dir_509654218d7fdb27ac23ff0fdd0c2206.html", "dir_509654218d7fdb27ac23ff0fdd0c2206" ],
    [ "axis_aligned_fusion.cpp", "axis__aligned__fusion_8cpp.html", "axis__aligned__fusion_8cpp" ],
    [ "axis_aligned_fusion.hpp", "axis__aligned__fusion_8hpp.html", "axis__aligned__fusion_8hpp" ],
    [ "from_boundary.cpp", "from__boundary_8cpp.html", "from__boundary_8cpp" ],
    [ "from_boundary.hpp", "from__boundary_8hpp.html", "from__boundary_8hpp" ],
    [ "from_facet_bijection.cpp", "from__facet__bijection_8cpp.html", "from__facet__bijection_8cpp" ],
    [ "from_facet_bijection.hpp", "from__facet__bijection_8hpp.html", "from__facet__bijection_8hpp" ],
    [ "from_facet_surjection.cpp", "from__facet__surjection_8cpp.html", "from__facet__surjection_8cpp" ],
    [ "from_facet_surjection.hpp", "from__facet__surjection_8hpp.html", "from__facet__surjection_8hpp" ],
    [ "from_manifold_decomposition.cpp", "src_2wmtk_2components_2multimesh_2from__manifold__decomposition_8cpp.html", "src_2wmtk_2components_2multimesh_2from__manifold__decomposition_8cpp" ],
    [ "from_manifold_decomposition.hpp", "from__manifold__decomposition_8hpp.html", "from__manifold__decomposition_8hpp" ],
    [ "from_tag.cpp", "from__tag_8cpp.html", "from__tag_8cpp" ],
    [ "from_tag.hpp", "from__tag_8hpp.html", "from__tag_8hpp" ],
    [ "from_vertex_simplices.cpp", "from__vertex__simplices_8cpp.html", "from__vertex__simplices_8cpp" ],
    [ "from_vertex_simplices.hpp", "from__vertex__simplices_8hpp.html", "from__vertex__simplices_8hpp" ],
    [ "MeshCollection.cpp", "_mesh_collection_8cpp.html", null ],
    [ "MeshCollection.hpp", "_mesh_collection_8hpp.html", "_mesh_collection_8hpp" ],
    [ "multimesh.cpp", "multimesh_8cpp.html", "multimesh_8cpp" ],
    [ "multimesh.hpp", "multimesh_8hpp.html", "multimesh_8hpp" ],
    [ "MultimeshOptions.cpp", "_multimesh_options_8cpp.html", "_multimesh_options_8cpp" ],
    [ "MultimeshOptions.hpp", "_multimesh_options_8hpp.html", "_multimesh_options_8hpp" ],
    [ "MultimeshRunnableOptions.cpp", "_multimesh_runnable_options_8cpp.html", null ],
    [ "MultimeshRunnableOptions.hpp", "_multimesh_runnable_options_8hpp.html", "_multimesh_runnable_options_8hpp" ],
    [ "NamedMultiMesh.cpp", "_named_multi_mesh_8cpp.html", "_named_multi_mesh_8cpp" ],
    [ "NamedMultiMesh.hpp", "_named_multi_mesh_8hpp.html", "_named_multi_mesh_8hpp" ],
    [ "vertex_fusion.cpp", "src_2wmtk_2components_2multimesh_2vertex__fusion_8cpp.html", "src_2wmtk_2components_2multimesh_2vertex__fusion_8cpp" ],
    [ "vertex_fusion.hpp", "vertex__fusion_8hpp.html", "vertex__fusion_8hpp" ]
];