Wildmeshing Toolkit: components/multimesh/tests/json.cpp File Reference
json.cpp File Reference
#include <fmt/ranges.h>
#include <catch2/catch_test_macros.hpp>
#include <nlohmann/json.hpp>
#include <wmtk/Mesh.hpp>
#include <wmtk/components/input/input.hpp>
#include <wmtk/components/multimesh/utils/get_attribute.hpp>
#include <wmtk/io/read_mesh.hpp>
#include "tools/TriMesh_examples.hpp"
#include "wmtk/components/multimesh/MeshCollection.hpp"
#include "wmtk/components/multimesh/MultimeshOptions.hpp"
#include "wmtk/components/multimesh/from_tag.hpp"
#include "utils.hpp"
Typedefs
using json = nlohmann::json
using AT = wmtk::attribute::AttributeType
using AD = wmtk::components::multimesh::utils::AttributeDescription
Functions
TEST_CASE ("multimesh_tag_json", "[components][multimesh]")
TEST_CASE ("multimesh_tag_creation_json", "[components][multimesh]")
TEST_CASE ("multimesh_boundary_json", "[components][multimesh]")
TEST_CASE ("multimesh_bijection_json", "[components][multimesh]")
TEST_CASE ("multimesh_fusion_json", "[components][multimesh]")
Variables
const fs::path wmtk_data_dir = WMTK_DATA_DIR
Typedef Documentation
AD
using AD = wmtk::components::multimesh::utils::AttributeDescription
Definition at line 20 of file json.cpp.
AT
using AT = wmtk::attribute::AttributeType
Definition at line 18 of file json.cpp.
json
using json = nlohmann::json
Definition at line 17 of file json.cpp.
Function Documentation
TEST_CASE() [1/5]
TEST_CASE ("multimesh_bijection_json" , "" [components][multimesh])
Definition at line 182 of file json.cpp.
References wmtk::Edge, wmtk::simplex::Simplex::edge(), wmtk::components::multimesh::MeshCollection::emplace_mesh(), wmtk::components::multimesh::MeshCollection::get_mesh(), wmtk::components::multimesh::MeshCollection::get_named_multimesh(), wmtk::components::multimesh::MultimeshOptions::options, and wmtk::components::multimesh::MultimeshOptions::run().
TEST_CASE() [2/5]
TEST_CASE ("multimesh_boundary_json" , "" [components][multimesh])
Definition at line 123 of file json.cpp.
References wmtk::attribute::Char, wmtk::Edge, wmtk::simplex::Simplex::edge(), wmtk::components::multimesh::MeshCollection::emplace_mesh(), wmtk::components::multimesh::utils::get_attribute(), wmtk::components::multimesh::MeshCollection::get_mesh(), wmtk::components::multimesh::MeshCollection::get_named_multimesh(), wmtk::components::multimesh::MultimeshOptions::options, wmtk::components::multimesh::MultimeshOptions::run(), and wmtk::Vertex.
TEST_CASE() [3/5]
TEST_CASE ("multimesh_fusion_json" , "" [components][multimesh])
Definition at line 212 of file json.cpp.
References wmtk::Edge, wmtk::simplex::Simplex::edge(), wmtk::components::multimesh::MeshCollection::emplace_mesh(), wmtk::components::multimesh::MeshCollection::get_mesh(), wmtk::components::multimesh::MeshCollection::get_named_multimesh(), wmtk::components::multimesh::MultimeshOptions::options, wmtk::components::multimesh::MultimeshOptions::run(), wmtk::Triangle, and wmtk::Vertex.
TEST_CASE() [4/5]
TEST_CASE ("multimesh_tag_creation_json" , "" [components][multimesh])
Definition at line 85 of file json.cpp.
References wmtk::components::multimesh::MeshCollection::emplace_mesh(), wmtk::components::multimesh::MultimeshOptions::options, and wmtk::io::read_mesh().
TEST_CASE() [5/5]
TEST_CASE ("multimesh_tag_json" , "" [components][multimesh])
Definition at line 29 of file json.cpp.
References wmtk::Edge, wmtk::simplex::Simplex::edge(), wmtk::components::multimesh::MeshCollection::emplace_mesh(), wmtk::components::multimesh::MeshCollection::get_mesh(), wmtk::components::multimesh::MeshCollection::get_named_multimesh(), wmtk::components::multimesh::MultimeshOptions::options, wmtk::components::multimesh::MultimeshOptions::run(), and wmtk::Vertex.
Variable Documentation
wmtk_data_dir
const fs::path wmtk_data_dir = WMTK_DATA_DIR
Definition at line 15 of file json.cpp.