Wildmeshing Toolkit: wmtk::components::mesh_info::simplex Namespace Reference
wmtk::components::mesh_info::simplex Namespace Reference
Namespaces
namespace operators
Functions
std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > dihedral_angles (const attribute::MeshAttributeHandle &pos, const attribute::MeshAttributeHandle &vol, bool run)
template<typename T >
std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > dihedral_angles (const attribute::MeshAttributeHandle &mah, const std::string_view &name, bool run)
template<typename T >
std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > dihedral_angles (const attribute::MeshAttributeHandle &mah, Mesh &mesh, const std::string_view &name, bool run)
template std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > dihedral_angles< double > (const attribute::MeshAttributeHandle &m, Mesh &, const std::string_view &name, bool run)
template std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > dihedral_angles< wmtk::Rational > (const attribute::MeshAttributeHandle &m, Mesh &, const std::string_view &name, bool run)
template std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > dihedral_angles< double > (const attribute::MeshAttributeHandle &m, const std::string_view &name, bool run)
template std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > dihedral_angles< wmtk::Rational > (const attribute::MeshAttributeHandle &m, const std::string_view &name, bool run)
std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > volumes (const attribute::MeshAttributeHandle &pos, const attribute::MeshAttributeHandle &vol, bool run)
template<typename T >
std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > volumes (const attribute::MeshAttributeHandle &mah, wmtk::PrimitiveType primitive_type, const std::string_view &name, bool run)
template<typename T >
std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > volumes (const attribute::MeshAttributeHandle &mah, Mesh &mesh, wmtk::PrimitiveType primitive_type, const std::string_view &name, bool run)
template std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > volumes< double > (const attribute::MeshAttributeHandle &m, Mesh &, wmtk::PrimitiveType primitive_type, const std::string_view &name, bool run)
template std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > volumes< wmtk::Rational > (const attribute::MeshAttributeHandle &m, Mesh &, wmtk::PrimitiveType primitive_type, const std::string_view &name, bool run)
template std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > volumes< double > (const attribute::MeshAttributeHandle &m, wmtk::PrimitiveType primitive_type, const std::string_view &name, bool run)
template std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > volumes< wmtk::Rational > (const attribute::MeshAttributeHandle &m, wmtk::PrimitiveType primitive_type, const std::string_view &name, bool run)
Function Documentation
dihedral_angles() [1/3]
template<typename T > std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::mesh_info::simplex::dihedral_angles (const attribute::MeshAttributeHandle & mah, const std::string_view & name, bool run)
Definition at line 29 of file dihedral_angles.cpp.
References wmtk::attribute::MeshAttributeHandle::mesh().
dihedral_angles() [2/3]
template<typename T > std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::mesh_info::simplex::dihedral_angles (const attribute::MeshAttributeHandle & mah, Mesh & mesh, const std::string_view & name, bool run)
Definition at line 35 of file dihedral_angles.cpp.
References dihedral_angles(), wmtk::Edge, and wmtk::Mesh::register_attribute().
dihedral_angles() [3/3]
std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::mesh_info::simplex::dihedral_angles (const attribute::MeshAttributeHandle & pos, const attribute::MeshAttributeHandle & vol, bool run)
Definition at line 8 of file dihedral_angles.cpp.
References wmtk::attribute::MeshAttributeHandle::handle(), and PT.
Referenced by dihedral_angles().
dihedral_angles< double >() [1/2]
template std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::mesh_info::simplex::dihedral_angles< double > (const attribute::MeshAttributeHandle & m, const std::string_view & name, bool run)
dihedral_angles< double >() [2/2]
template std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::mesh_info::simplex::dihedral_angles< double > (const attribute::MeshAttributeHandle & m, Mesh & , const std::string_view & name, bool run)
Referenced by TEST_CASE().
dihedral_angles< wmtk::Rational >() [1/2]
template std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::mesh_info::simplex::dihedral_angles< wmtk::Rational > (const attribute::MeshAttributeHandle & m, const std::string_view & name, bool run)
dihedral_angles< wmtk::Rational >() [2/2]
template std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::mesh_info::simplex::dihedral_angles< wmtk::Rational > (const attribute::MeshAttributeHandle & m, Mesh & , const std::string_view & name, bool run)
volumes() [1/3]
template<typename T > std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::mesh_info::simplex::volumes (const attribute::MeshAttributeHandle & mah, Mesh & mesh, wmtk::PrimitiveType primitive_type, const std::string_view & name, bool run)
Definition at line 38 of file volumes.cpp.
References wmtk::Mesh::register_attribute(), and volumes().
volumes() [2/3]
template<typename T > std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::mesh_info::simplex::volumes (const attribute::MeshAttributeHandle & mah, wmtk::PrimitiveType primitive_type, const std::string_view & name, bool run)
Definition at line 28 of file volumes.cpp.
References wmtk::attribute::MeshAttributeHandle::mesh().
volumes() [3/3]
std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::mesh_info::simplex::volumes (const attribute::MeshAttributeHandle & pos, const attribute::MeshAttributeHandle & vol, bool run)
Definition at line 7 of file volumes.cpp.
References wmtk::attribute::MeshAttributeHandle::handle(), and PT.
Referenced by volumes().
volumes< double >() [1/2]
template std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::mesh_info::simplex::volumes< double > (const attribute::MeshAttributeHandle & m, Mesh & , wmtk::PrimitiveType primitive_type, const std::string_view & name, bool run)
Referenced by TEST_CASE(), and TEST_CASE().
volumes< double >() [2/2]
template std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::mesh_info::simplex::volumes< double > (const attribute::MeshAttributeHandle & m, wmtk::PrimitiveType primitive_type, const std::string_view & name, bool run)
volumes< wmtk::Rational >() [1/2]
template std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::mesh_info::simplex::volumes< wmtk::Rational > (const attribute::MeshAttributeHandle & m, Mesh & , wmtk::PrimitiveType primitive_type, const std::string_view & name, bool run)
volumes< wmtk::Rational >() [2/2]
template std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::mesh_info::simplex::volumes< wmtk::Rational > (const attribute::MeshAttributeHandle & m, wmtk::PrimitiveType primitive_type, const std::string_view & name, bool run)