Wildmeshing Toolkit: wmtk::components::isotropic_remeshing Namespace Reference
wmtk::components::isotropic_remeshing Namespace Reference
Namespaces
namespace internal
namespace invariants
Classes
struct AliasInvariantParameters
struct AttributeInvariantParameters
struct EdgeCollapseOptions
struct EdgeSplitOptions
struct EdgeSwapOptions
struct EnvelopeInvariantParameters
struct InvariantCollectionParameters
struct InvariantOptions
struct InvariantParameters
class IsotropicRemeshing
struct IsotropicRemeshingOptions
struct OperationOptions
struct Pass
struct PriorityOptions
struct VertexSmoothOptions
Enumerations
enum class EdgeSwapMode { AMIPS , Valence , Skip }
Functions
void isotropic_remeshing (Mesh &m, const IsotropicRemeshingOptions &options)
void isotropic_remeshing (multimesh::MeshCollection &mc, const IsotropicRemeshingOptions &options)
void to_json (nlohmann::json &nlohmann_json_j, const IsotropicRemeshingOptions &nlohmann_json_t)
void from_json (const nlohmann::json &nlohmann_json_j, IsotropicRemeshingOptions &nlohmann_json_t)
void fill_operation_parameters ()
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (PriorityOptions)
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (PriorityOptions)
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (InvariantOptions)
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (InvariantOptions)
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (InvariantParameters)
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (InvariantParameters)
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (AttributeInvariantParameters)
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (AttributeInvariantParameters)
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (AliasInvariantParameters)
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (AliasInvariantParameters)
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (InvariantCollectionParameters)
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (InvariantCollectionParameters)
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (EnvelopeInvariantParameters)
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (EnvelopeInvariantParameters)
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (OperationOptions)
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (OperationOptions)
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (EdgeSplitOptions)
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (EdgeSplitOptions)
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (EdgeCollapseOptions)
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (EdgeCollapseOptions)
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (EdgeSwapOptions)
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (EdgeSwapOptions)
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (VertexSmoothOptions)
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (VertexSmoothOptions)
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (Pass)
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (Pass)
Enumeration Type Documentation
EdgeSwapMode
enum class wmtk::components::isotropic_remeshing::EdgeSwapMode strong
Enumerator
AMIPS
Valence
Skip
Definition at line 4 of file EdgeSwapMode.hpp.
Function Documentation
fill_operation_parameters()
void wmtk::components::isotropic_remeshing::fill_operation_parameters ()
Definition at line 140 of file IsotropicRemeshingOptions.cpp.
from_json()
void wmtk::components::isotropic_remeshing::from_json (const nlohmann::json & nlohmann_json_j, IsotropicRemeshingOptions & nlohmann_json_t)
Definition at line 101 of file IsotropicRemeshingOptions.cpp.
Referenced by WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE(), WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE(), WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE(), WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE(), WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE(), WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE(), WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE(), and WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE().
isotropic_remeshing() [1/2]
void wmtk::components::isotropic_remeshing::isotropic_remeshing (Mesh & m, const IsotropicRemeshingOptions & options)
Definition at line 9 of file isotropic_remeshing.cpp.
References wmtk::components::multimesh::MeshCollection::emplace_mesh(), and isotropic_remeshing().
Referenced by isotropic_remeshing(), and isotropic_remeshing().
isotropic_remeshing() [2/2]
void wmtk::components::isotropic_remeshing::isotropic_remeshing (multimesh::MeshCollection & mc, const IsotropicRemeshingOptions & options)
Definition at line 16 of file isotropic_remeshing.cpp.
References isotropic_remeshing(), and wmtk::components::isotropic_remeshing::IsotropicRemeshing::run().
to_json()
void wmtk::components::isotropic_remeshing::to_json (nlohmann::json & nlohmann_json_j, const IsotropicRemeshingOptions & nlohmann_json_t)
Definition at line 76 of file IsotropicRemeshingOptions.cpp.
Referenced by wmtk::components::isotropic_remeshing::AttributeInvariantParameters::to_json(), wmtk::components::isotropic_remeshing::EnvelopeInvariantParameters::to_json(), wmtk::components::isotropic_remeshing::InvariantCollectionParameters::to_json(), wmtk::components::isotropic_remeshing::AliasInvariantParameters::to_json(), WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE(), WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE(), WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE(), WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE(), WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE(), WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE(), WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE(), and WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE().
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE() [1/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (AliasInvariantParameters)
Definition at line 116 of file OperationOptions.cpp.
References from_json(), and WMTK_NLOHMANN_ASSIGN_TYPE_FROM_JSON.
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE() [2/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (AttributeInvariantParameters)
Definition at line 103 of file OperationOptions.cpp.
References from_json(), and WMTK_NLOHMANN_ASSIGN_TYPE_FROM_JSON.
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE() [3/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (EdgeCollapseOptions)
Definition at line 200 of file OperationOptions.cpp.
References from_json().
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE() [4/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (EdgeSplitOptions)
Definition at line 192 of file OperationOptions.cpp.
References from_json().
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE() [5/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (EdgeSwapOptions)
Definition at line 216 of file OperationOptions.cpp.
References AMIPS, from_json(), Skip, and Valence.
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE() [6/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (EnvelopeInvariantParameters)
Definition at line 158 of file OperationOptions.cpp.
References from_json(), and WMTK_NLOHMANN_ASSIGN_TYPE_FROM_JSON.
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE() [7/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (InvariantCollectionParameters)
Definition at line 144 of file OperationOptions.cpp.
References from_json(), and WMTK_NLOHMANN_ASSIGN_TYPE_FROM_JSON.
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE() [8/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (InvariantOptions)
Definition at line 74 of file OperationOptions.cpp.
References WMTK_NLOHMANN_ASSIGN_TYPE_FROM_JSON.
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE() [9/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (InvariantParameters)
Definition at line 94 of file OperationOptions.cpp.
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE() [10/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (OperationOptions)
Definition at line 173 of file OperationOptions.cpp.
References WMTK_NLOHMANN_ASSIGN_TYPE_FROM_JSON_WITH_DEFAULT, and WMTK_NLOHMANN_JSON_DECLARE_DEFAULT_OBJECT.
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE() [11/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (Pass)
Definition at line 250 of file OperationOptions.cpp.
References WMTK_NLOHMANN_ASSIGN_TYPE_FROM_JSON_WITH_DEFAULT, and WMTK_NLOHMANN_JSON_DECLARE_DEFAULT_OBJECT.
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE() [12/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (PriorityOptions)
Definition at line 18 of file OperationOptions.cpp.
References WMTK_NLOHMANN_ASSIGN_TYPE_FROM_JSON_WITH_DEFAULT, and WMTK_NLOHMANN_JSON_DECLARE_DEFAULT_OBJECT.
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE() [13/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (VertexSmoothOptions)
Definition at line 238 of file OperationOptions.cpp.
References from_json().
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE() [1/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (AliasInvariantParameters)
Definition at line 109 of file OperationOptions.cpp.
References to_json(), and WMTK_NLOHMANN_ASSIGN_TYPE_TO_JSON.
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE() [2/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (AttributeInvariantParameters)
Definition at line 96 of file OperationOptions.cpp.
References to_json(), and WMTK_NLOHMANN_ASSIGN_TYPE_TO_JSON.
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE() [3/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (EdgeCollapseOptions)
Definition at line 196 of file OperationOptions.cpp.
References to_json().
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE() [4/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (EdgeSplitOptions)
Definition at line 188 of file OperationOptions.cpp.
References to_json().
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE() [5/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (EdgeSwapOptions)
Definition at line 204 of file OperationOptions.cpp.
References AMIPS, Skip, to_json(), and Valence.
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE() [6/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (EnvelopeInvariantParameters)
Definition at line 151 of file OperationOptions.cpp.
References to_json(), and WMTK_NLOHMANN_ASSIGN_TYPE_TO_JSON.
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE() [7/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (InvariantCollectionParameters)
Definition at line 138 of file OperationOptions.cpp.
References to_json(), and WMTK_NLOHMANN_ASSIGN_TYPE_TO_JSON.
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE() [8/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (InvariantOptions)
Definition at line 63 of file OperationOptions.cpp.
References WMTK_NLOHMANN_ASSIGN_TYPE_TO_JSON.
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE() [9/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (InvariantParameters)
Definition at line 92 of file OperationOptions.cpp.
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE() [10/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (OperationOptions)
Definition at line 164 of file OperationOptions.cpp.
References WMTK_NLOHMANN_ASSIGN_TYPE_TO_JSON.
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE() [11/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (Pass)
Definition at line 244 of file OperationOptions.cpp.
References WMTK_NLOHMANN_ASSIGN_TYPE_TO_JSON.
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE() [12/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (PriorityOptions)
Definition at line 13 of file OperationOptions.cpp.
References WMTK_NLOHMANN_ASSIGN_TYPE_TO_JSON.
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE() [13/13]
wmtk::components::isotropic_remeshing::WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (VertexSmoothOptions)
Definition at line 234 of file OperationOptions.cpp.
References to_json().