Wildmeshing Toolkit: wmtk::dart::utils Namespace Reference
wmtk::dart::utils Namespace Reference
Namespaces
namespace detail
namespace internal
Functions
int8_t apply_simplex_involution_directed (PrimitiveType pt, PrimitiveType opt, int8_t action, int8_t source, bool upward)
int8_t apply_simplex_involution (PrimitiveType pt, PrimitiveType opt, int8_t action, int8_t source)
wmtk::dart::Dart apply_simplex_involution (PrimitiveType pt, PrimitiveType opt, const dart::Dart &action, const dart::Dart &source)
int8_t edge_mirror_left_action (const SimplexDart &sd, int8_t edge_permutation_index)
dart::Dart edge_mirror (const SimplexDart &sd, const dart::Dart &dart)
int8_t edge_mirror (const SimplexDart &sd, int8_t pi)
int8_t edge_mirror (const SimplexDart &sd, int8_t edge_permutation_index, int8_t permutation_index)
dart::Dart edge_mirror (const SimplexDart &sd, const dart::Dart &edge_dart, const dart::Dart &dart)
int8_t from_local_vertex_permutation (Eigen::Ref< const VectorX< int8_t > > permutation)
int8_t from_local_vertex_permutation (PrimitiveType pt, Eigen::Ref< const VectorX< int8_t > > permutation)
int8_t from_vertex_permutation (Eigen::Ref< const VectorX< int64_t > > indices)
int8_t from_vertex_permutation (PrimitiveType pt, Eigen::Ref< const VectorX< int64_t > > permutation)
template<size_t N>
int8_t from_local_vertex_permutation (const std::array< int8_t, N > &indices)
template<>
int8_t from_local_vertex_permutation< 1 > (const std::array< int8_t, 1 > &indices)
template int8_t from_local_vertex_permutation< 2 > (const std::array< int8_t, 2 > &indices)
template int8_t from_local_vertex_permutation< 3 > (const std::array< int8_t, 3 > &indices)
template int8_t from_local_vertex_permutation< 4 > (const std::array< int8_t, 4 > &indices)
template<typename IntLike , size_t N>
int8_t from_vertex_permutation (const std::array< IntLike, N > &indices)
std::vector< std::vector< int8_t > > get_canonical_cofaces (const SimplexDart &sd, PrimitiveType pt, PrimitiveType coface_pt)
std::span< const int8_t > get_canonical_faces (const SimplexDart &sd, PrimitiveType pt)
int8_t get_canonical_simplex (const SimplexDart &sd, PrimitiveType pt, int8_t simplex_index)
int8_t get_canonical_simplex_orientation (const SimplexDart &sd, PrimitiveType pt, int8_t permutation)
int8_t get_canonical_subdart (const SimplexDart &sd, PrimitiveType pt, int8_t permutation)
template<typename IntLike , size_t D, size_t d>
std::array< int8_t, D > get_canonical_subdart_permutation_indices (const std::array< IntLike, D > &S, const std::array< IntLike, d > &s)
template<typename IntLike , size_t D, size_t d>
int8_t get_canonical_subdart_permutation (const std::array< IntLike, D > &S, const std::array< IntLike, d > &s)
int8_t get_canonical_supdart (const SimplexDart &sd, PrimitiveType pt, int8_t permutation)
std::vector< int8_t > get_faces (const PrimitiveType mesh_pt, const PrimitiveType target_pt, int8_t permutation, const PrimitiveType face_pt)
std::vector< int8_t > get_faces_ids (const PrimitiveType mesh_pt, const PrimitiveType target_pt, int8_t permutation, const PrimitiveType face_pt)
std::vector< int8_t > get_face_ids (const PrimitiveType mesh_pt, const PrimitiveType target_pt, int8_t permutation, const PrimitiveType face_pt)
VectorX< int8_t >::ConstMapType get_local_vertex_permutation (PrimitiveType pt, int8_t permutation_index)
template<size_t D>
std::array< int8_t, D+1 > get_local_vertex_permutation (int8_t permutation_index)
template std::array< int8_t, 1 > get_local_vertex_permutation< 0 > (int8_t permutation_index)
template std::array< int8_t, 2 > get_local_vertex_permutation< 1 > (int8_t permutation_index)
template std::array< int8_t, 3 > get_local_vertex_permutation< 2 > (int8_t permutation_index)
template std::array< int8_t, 4 > get_local_vertex_permutation< 3 > (int8_t permutation_index)
template<size_t SimplexDimension>
std::array< int8_t, SimplexDimension+1 > get_local_vertex_permutation (int8_t permutation_index)
template<typename IntLike , size_t N>
int8_t get_permutation (const std::array< IntLike, N > &from, const std::array< IntLike, N > &to)
template<int8_t Dim>
auto get_simplex_dart ()
template<PrimitiveType PT>
auto get_simplex_dart_from_primitive_type ()
const dart::SimplexDart & get_simplex_dart (PrimitiveType pt)
const dart::SimplexDart & get_simplex_dart (int8_t dim)
std::array< int64_t, 2 > get_vertex_indices (const EdgeMesh &m, PrimitiveType pt, const dart::Dart &d)
std::array< int64_t, 3 > get_vertex_indices (const TriMesh &m, PrimitiveType pt, const dart::Dart &d)
std::array< int64_t, 4 > get_vertex_indices (const TetMesh &m, PrimitiveType pt, const dart::Dart &d)
int8_t get_simplex_involution_upward (PrimitiveType opt, int8_t a, PrimitiveType pt, int8_t b)
int8_t get_simplex_involution (PrimitiveType pt, const int8_t &a, PrimitiveType opt, const int8_t &b)
std::pair< int8_t, int8_t > get_simplex_involution_pair (PrimitiveType pt, const int8_t &a, PrimitiveType opt, const int8_t &b)
wmtk::dart::Dart get_simplex_involution (PrimitiveType pt, const dart::Dart &a, PrimitiveType opt, const dart::Dart &b)
std::pair< wmtk::dart::Dart, wmtk::dart::Dart > get_simplex_involution_pair (PrimitiveType pt, const dart::Dart &a, PrimitiveType opt, const dart::Dart &b)
template<int SimplexDim, int Dim, typename MeshType >
RowVectors< int64_t, internal::nCr(Dim+1, SimplexDim+1)> indexed_topology_initialization (const DartTopologyAccessor< Dim, MeshType > &acc)
auto largest_shared_subdart_size (PrimitiveType mesh_type, int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index) -> int8_t
int8_t largest_shared_subdart_size (PrimitiveType mesh_type, int8_t dart_index, PrimitiveType primitive_type, int8_t simplex_index)
std::pair< int8_t, int8_t > local_simplex_decomposition (const SimplexDart &sd, PrimitiveType pt, int8_t permutation)
int8_t opposite_action (int8_t simplex_dimension)
int8_t opposite (const SimplexDart &sd, int8_t permutation_index)
dart::Dart opposite (const SimplexDart &sd, const dart::Dart &dart)
int8_t permutation_index_from_tuple (PrimitiveType mesh_type, const Tuple &t)
int8_t permutation_index_to_simplex_index (PrimitiveType mesh_type, int8_t current_orientation, PrimitiveType target_type)
template<size_t N>
std::array< int64_t, N > permute (const std::array< int64_t, N > &from, int8_t permutation)
template<typename Derived >
VectorXl permute (const Eigen::MatrixBase< Derived > &from, int8_t permutation)
int8_t relative_face_index (const SimplexDart &sd, int8_t current_permutation, PrimitiveType target_type, int8_t target_index)
: Returns the relative local index of a simplex with respect to an permutation When we switch a dart to lie on a specific simplex we need to find some action that maps to that simplex.
bool share_simplex (PrimitiveType mesh_type, PrimitiveType simplex_type, int8_t a, int8_t b)
auto simplex_index_from_permutation_index (const PrimitiveType mesh_type, int8_t permutation_index, wmtk::PrimitiveType type) -> int8_t
auto subdart_maximal_action_to_face (PrimitiveType mesh_type, int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index) -> std::array< int8_t, 2 >
auto subdart_maximal_action_to_face_action (PrimitiveType mesh_type, int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index) -> int8_t
auto subdart_maximal_action_to_face_size (PrimitiveType mesh_type, int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index) -> int8_t
int8_t subdart_maximal_action_to_face_action (PrimitiveType mesh_type, int8_t dart_index, PrimitiveType primitive_type, int8_t simplex_index)
int8_t subdart_maximal_action_to_face_size (PrimitiveType mesh_type, int8_t dart_index, PrimitiveType primitive_type, int8_t simplex_index)
std::array< int8_t, 2 > subdart_maximal_action_to_face (PrimitiveType mesh_type, int8_t dart_index, PrimitiveType primitive_type, int8_t simplex_index)
Tuple tuple_from_permutation_index (PrimitiveType mesh_type, const int64_t global_cid, int8_t valid_tuple_index)
Function Documentation
apply_simplex_involution() [1/2]
wmtk::dart::Dart wmtk::dart::utils::apply_simplex_involution (PrimitiveType pt, PrimitiveType opt, const dart::Dart & action, const dart::Dart & source)
Definition at line 78 of file apply_simplex_involution.cpp.
References apply_simplex_involution(), wmtk::dart::_Dart< IndexType, OrientType >::global_id(), and wmtk::dart::_Dart< IndexType, OrientType >::permutation().
apply_simplex_involution() [2/2]
int8_t wmtk::dart::utils::apply_simplex_involution (PrimitiveType pt, PrimitiveType opt, int8_t action, int8_t source)
Definition at line 56 of file apply_simplex_involution.cpp.
References apply_simplex_involution_directed(), wmtk::dart::SimplexDart::get_singleton(), and wmtk::dart::SimplexDart::product().
Referenced by wmtk::dart::Involution::apply(), apply_simplex_involution(), wmtk::dart::Involution::invert(), wmtk::operations::internal::CollapseAlternateFacetOptionData::map_permutation_to_alt(), wmtk::multimesh::MultiMeshManager::map_tuple_between_meshes(), wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_facet(), and wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_facet().
apply_simplex_involution_directed()
int8_t wmtk::dart::utils::apply_simplex_involution_directed (PrimitiveType pt, PrimitiveType opt, int8_t action, int8_t source, bool upward)
Definition at line 14 of file apply_simplex_involution.cpp.
References wmtk::dart::SimplexDart::convert(), wmtk::dart::SimplexDart::get_singleton(), wmtk::dart::SimplexDart::identity(), wmtk::dart::SimplexDart::inverse(), local_simplex_decomposition(), wmtk::dart::SimplexDart::product(), and wmtk::Vertex.
Referenced by apply_simplex_involution().
edge_mirror() [1/4]
dart::Dart wmtk::dart::utils::edge_mirror (const SimplexDart & sd, const dart::Dart & dart)
Definition at line 52 of file edge_mirror.cpp.
References edge_mirror(), wmtk::dart::_Dart< IndexType, OrientType >::global_id(), and wmtk::dart::_Dart< IndexType, OrientType >::permutation().
Referenced by edge_mirror(), edge_mirror(), wmtk::operations::internal::CollapseAlternateFacetOptionData::map_permutation_to_alt(), and wmtk::operations::internal::CollapseAlternateFacetOptionData::map_permutation_to_alt().
edge_mirror() [2/4]
dart::Dart wmtk::dart::utils::edge_mirror (const SimplexDart & sd, const dart::Dart & edge_dart, const dart::Dart & dart)
Definition at line 69 of file edge_mirror.cpp.
References edge_mirror(), wmtk::dart::_Dart< IndexType, OrientType >::global_id(), and wmtk::dart::_Dart< IndexType, OrientType >::permutation().
edge_mirror() [3/4]
int8_t wmtk::dart::utils::edge_mirror (const SimplexDart & sd, int8_t edge_permutation_index, int8_t permutation_index)
Definition at line 61 of file edge_mirror.cpp.
References edge_mirror_left_action(), wmtk::dart::SimplexDart::primitive_as_index(), wmtk::dart::SimplexDart::product(), and wmtk::Vertex.
edge_mirror() [4/4]
int8_t wmtk::dart::utils::edge_mirror (const SimplexDart & sd, int8_t pi)
Definition at line 56 of file edge_mirror.cpp.
References edge_mirror_left_action(), wmtk::dart::SimplexDart::identity(), and wmtk::dart::SimplexDart::product().
edge_mirror_left_action()
int8_t wmtk::dart::utils::edge_mirror_left_action (const SimplexDart & sd, int8_t edge_permutation_index)
Definition at line 43 of file edge_mirror.cpp.
References wmtk::dart::SimplexDart::inverse(), wmtk::dart::SimplexDart::primitive_as_index(), wmtk::dart::SimplexDart::product(), and wmtk::Vertex.
Referenced by edge_mirror(), and edge_mirror().
from_local_vertex_permutation() [1/3]
template<size_t N> int8_t wmtk::dart::utils::from_local_vertex_permutation (const std::array< int8_t, N > & indices)
Definition at line 159 of file from_local_vertex_permutation.cpp.
from_local_vertex_permutation() [2/3]
int8_t wmtk::dart::utils::from_local_vertex_permutation (Eigen::Ref< const VectorX< int8_t > > permutation)
Definition at line 105 of file from_local_vertex_permutation.cpp.
References wmtk::Edge, from_local_vertex_permutation< 2 >(), from_local_vertex_permutation< 3 >(), from_local_vertex_permutation< 4 >(), wmtk::get_primitive_type_from_id(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by from_local_vertex_permutation(), from_vertex_permutation(), from_vertex_permutation(), and get_canonical_subdart_permutation().
from_local_vertex_permutation() [3/3]
int8_t wmtk::dart::utils::from_local_vertex_permutation (PrimitiveType pt, Eigen::Ref< const VectorX< int8_t > > permutation)
Definition at line 117 of file from_local_vertex_permutation.cpp.
References from_local_vertex_permutation(), and wmtk::get_primitive_type_from_id().
from_local_vertex_permutation< 1 >()
template<> int8_t wmtk::dart::utils::from_local_vertex_permutation< 1 > (const std::array< int8_t, 1 > & indices)
Definition at line 172 of file from_local_vertex_permutation.cpp.
from_local_vertex_permutation< 2 >()
template int8_t wmtk::dart::utils::from_local_vertex_permutation< 2 > (const std::array< int8_t, 2 > & indices)
Referenced by from_local_vertex_permutation().
from_local_vertex_permutation< 3 >()
template int8_t wmtk::dart::utils::from_local_vertex_permutation< 3 > (const std::array< int8_t, 3 > & indices)
Referenced by from_local_vertex_permutation().
from_local_vertex_permutation< 4 >()
template int8_t wmtk::dart::utils::from_local_vertex_permutation< 4 > (const std::array< int8_t, 4 > & indices)
Referenced by from_local_vertex_permutation().
from_vertex_permutation() [1/3]
template<typename IntLike , size_t N> int8_t wmtk::dart::utils::from_vertex_permutation (const std::array< IntLike, N > & indices)
Definition at line 32 of file from_local_vertex_permutation.hpp.
References from_local_vertex_permutation(), wmtk::get_primitive_type_from_id(), wmtk::dart::utils::detail::get_relative_indices(), and wmtk::dart::SimplexDart::get_singleton().
from_vertex_permutation() [2/3]
int8_t wmtk::dart::utils::from_vertex_permutation (Eigen::Ref< const VectorX< int64_t > > indices)
Definition at line 125 of file from_local_vertex_permutation.cpp.
References from_local_vertex_permutation(), wmtk::get_primitive_type_from_id(), and wmtk::dart::SimplexDart::get_singleton().
Referenced by from_vertex_permutation(), wmtk::utils::internal::IndexSimplexMapper::get_internal_dart(), wmtk::utils::internal::IndexSimplexMapper::get_mesh_dart(), get_permutation(), wmtk::utils::internal::IndexSimplexMapper::make_map(), permute(), and permute().
from_vertex_permutation() [3/3]
int8_t wmtk::dart::utils::from_vertex_permutation (PrimitiveType pt, Eigen::Ref< const VectorX< int64_t > > permutation)
Definition at line 152 of file from_local_vertex_permutation.cpp.
References from_vertex_permutation(), and wmtk::get_primitive_type_from_id().
get_canonical_cofaces()
std::vector< std::vector< int8_t > > wmtk::dart::utils::get_canonical_cofaces (const SimplexDart & sd, PrimitiveType pt, PrimitiveType coface_pt)
Definition at line 7 of file get_canonical_cofaces.cpp.
References get_canonical_faces(), get_faces(), and wmtk::dart::SimplexDart::simplex_type().
get_canonical_faces()
std::span< const int8_t > wmtk::dart::utils::get_canonical_faces (const SimplexDart & sd, PrimitiveType pt)
Definition at line 9 of file get_canonical_faces.cpp.
References wmtk::autogen::edge_mesh::canonical_simplex, wmtk::autogen::tri_mesh::canonical_simplex, wmtk::autogen::tet_mesh::canonical_simplex, wmtk::Edge, wmtk::get_primitive_type_id(), wmtk::dart::SimplexDart::simplex_type(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by get_canonical_cofaces(), and get_faces().
get_canonical_simplex()
int8_t wmtk::dart::utils::get_canonical_simplex (const SimplexDart & sd, PrimitiveType pt, int8_t simplex_index) inline
Definition at line 9 of file get_canonical_simplex.hpp.
References wmtk::autogen::edge_mesh::canonical_simplex, wmtk::autogen::tri_mesh::canonical_simplex, wmtk::autogen::tet_mesh::canonical_simplex, wmtk::Edge, wmtk::get_primitive_type_id(), wmtk::dart::SimplexDart::identity(), wmtk::dart::SimplexDart::simplex_type(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
get_canonical_simplex_orientation()
int8_t wmtk::dart::utils::get_canonical_simplex_orientation (const SimplexDart & sd, PrimitiveType pt, int8_t permutation) inline
Definition at line 8 of file get_canonical_simplex_orientation.hpp.
References get_canonical_supdart(), wmtk::dart::SimplexDart::inverse(), and wmtk::dart::SimplexDart::product().
get_canonical_subdart()
int8_t wmtk::dart::utils::get_canonical_subdart (const SimplexDart & sd, PrimitiveType pt, int8_t permutation) inline
Definition at line 12 of file get_canonical_subdart.hpp.
References wmtk::autogen::edge_mesh::canonical_subdart, wmtk::autogen::tri_mesh::canonical_subdart, wmtk::autogen::tet_mesh::canonical_subdart, wmtk::Edge, wmtk::get_primitive_type_id(), wmtk::dart::SimplexDart::identity(), wmtk::dart::SimplexDart::simplex_type(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
get_canonical_subdart_permutation()
template<typename IntLike , size_t D, size_t d> int8_t wmtk::dart::utils::get_canonical_subdart_permutation (const std::array< IntLike, D > & S, const std::array< IntLike, d > & s)
Definition at line 41 of file get_canonical_subdart_permutation.hpp.
References from_local_vertex_permutation(), and get_canonical_subdart_permutation_indices().
Referenced by wmtk::utils::internal::cofacets().
get_canonical_subdart_permutation_indices()
template<typename IntLike , size_t D, size_t d> std::array< int8_t, D > wmtk::dart::utils::get_canonical_subdart_permutation_indices (const std::array< IntLike, D > & S, const std::array< IntLike, d > & s)
Definition at line 11 of file get_canonical_subdart_permutation.hpp.
References get_permutation(), and wmtk::dart::utils::detail::local_index_map().
Referenced by get_canonical_subdart_permutation().
get_canonical_supdart()
int8_t wmtk::dart::utils::get_canonical_supdart (const SimplexDart & sd, PrimitiveType pt, int8_t permutation) inline
Definition at line 13 of file get_canonical_supdart.hpp.
References wmtk::autogen::edge_mesh::canonical_supdart, wmtk::autogen::tri_mesh::canonical_supdart, wmtk::autogen::tet_mesh::canonical_supdart, wmtk::Edge, wmtk::get_primitive_type_id(), wmtk::dart::SimplexDart::identity(), wmtk::dart::SimplexDart::simplex_type(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by get_canonical_simplex_orientation(), and local_simplex_decomposition().
get_face_ids()
std::vector< int8_t > wmtk::dart::utils::get_face_ids (const PrimitiveType mesh_pt, const PrimitiveType target_pt, int8_t permutation, const PrimitiveType face_pt)
get_faces()
std::vector< int8_t > wmtk::dart::utils::get_faces (const PrimitiveType mesh_pt, const PrimitiveType target_pt, int8_t permutation, const PrimitiveType face_pt)
Definition at line 7 of file get_faces.cpp.
References get_canonical_faces(), wmtk::get_primitive_type_id(), and wmtk::dart::SimplexDart::get_singleton().
Referenced by get_canonical_cofaces(), and get_faces_ids().
get_faces_ids()
std::vector< int8_t > wmtk::dart::utils::get_faces_ids (const PrimitiveType mesh_pt, const PrimitiveType target_pt, int8_t permutation, const PrimitiveType face_pt)
Definition at line 32 of file get_faces.cpp.
References get_faces(), and wmtk::dart::SimplexDart::get_singleton().
get_local_vertex_permutation() [1/3]
template<size_t D> std::array< int8_t, D+1 > wmtk::dart::utils::get_local_vertex_permutation (int8_t permutation_index)
Definition at line 24 of file get_local_vertex_permutation.cpp.
References get_local_vertex_permutation(), and wmtk::get_primitive_type_from_id().
get_local_vertex_permutation() [2/3]
template<size_t SimplexDimension> std::array< int8_t, SimplexDimension+1 > wmtk::dart::utils::get_local_vertex_permutation (int8_t permutation_index)
Definition at line 24 of file get_local_vertex_permutation.cpp.
References get_local_vertex_permutation(), and wmtk::get_primitive_type_from_id().
get_local_vertex_permutation() [3/3]
VectorX< int8_t >::ConstMapType wmtk::dart::utils::get_local_vertex_permutation (PrimitiveType pt, int8_t permutation_index)
Definition at line 7 of file get_local_vertex_permutation.cpp.
References wmtk::Edge, wmtk::autogen::tet_mesh::permutations, wmtk::autogen::edge_mesh::permutations, wmtk::autogen::tri_mesh::permutations, wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by get_local_vertex_permutation(), permute(), and permute().
get_local_vertex_permutation< 0 >()
template std::array< int8_t, 1 > wmtk::dart::utils::get_local_vertex_permutation< 0 > (int8_t permutation_index)
get_local_vertex_permutation< 1 >()
template std::array< int8_t, 2 > wmtk::dart::utils::get_local_vertex_permutation< 1 > (int8_t permutation_index)
get_local_vertex_permutation< 2 >()
template std::array< int8_t, 3 > wmtk::dart::utils::get_local_vertex_permutation< 2 > (int8_t permutation_index)
get_local_vertex_permutation< 3 >()
template std::array< int8_t, 4 > wmtk::dart::utils::get_local_vertex_permutation< 3 > (int8_t permutation_index)
get_permutation()
template<typename IntLike , size_t N> int8_t wmtk::dart::utils::get_permutation (const std::array< IntLike, N > & from, const std::array< IntLike, N > & to)
Definition at line 13 of file get_permutation.hpp.
References from_vertex_permutation(), wmtk::get_primitive_type_from_id(), and wmtk::dart::SimplexDart::get_singleton().
Referenced by get_canonical_subdart_permutation_indices().
get_simplex_dart() [1/3]
template<int8_t Dim> auto wmtk::dart::utils::get_simplex_dart ()
Definition at line 22 of file get_simplex_dart.hpp.
Referenced by get_simplex_dart().
get_simplex_dart() [2/3]
const dart::SimplexDart & wmtk::dart::utils::get_simplex_dart (int8_t dim) inline
Definition at line 34 of file get_simplex_dart.hpp.
References wmtk::get_primitive_type_from_id(), and get_simplex_dart().
get_simplex_dart() [3/3]
const dart::SimplexDart & wmtk::dart::utils::get_simplex_dart (PrimitiveType pt) inline
Definition at line 30 of file get_simplex_dart.hpp.
References wmtk::dart::SimplexDart::get_singleton().
get_simplex_dart_from_primitive_type()
template<PrimitiveType PT> auto wmtk::dart::utils::get_simplex_dart_from_primitive_type ()
Definition at line 26 of file get_simplex_dart.hpp.
get_simplex_involution() [1/2]
wmtk::dart::Dart wmtk::dart::utils::get_simplex_involution (PrimitiveType pt, const dart::Dart & a, PrimitiveType opt, const dart::Dart & b)
Definition at line 159 of file get_simplex_involution.cpp.
References get_simplex_involution(), wmtk::dart::_Dart< IndexType, OrientType >::global_id(), and wmtk::dart::_Dart< IndexType, OrientType >::permutation().
get_simplex_involution() [2/2]
int8_t wmtk::dart::utils::get_simplex_involution (PrimitiveType pt, const int8_t & a, PrimitiveType opt, const int8_t & b)
Definition at line 126 of file get_simplex_involution.cpp.
References get_simplex_involution_upward().
Referenced by wmtk::dart::DartTopologyAccessor< Dim, MeshType >::fuse(), wmtk::operations::internal::CollapseAlternateFacetOptionData::get_neighbor_action(), get_simplex_involution(), get_simplex_involution_pair(), and get_simplex_involution_pair().
get_simplex_involution_pair() [1/2]
std::pair< wmtk::dart::Dart, wmtk::dart::Dart > wmtk::dart::utils::get_simplex_involution_pair (PrimitiveType pt, const dart::Dart & a, PrimitiveType opt, const dart::Dart & b)
Definition at line 171 of file get_simplex_involution.cpp.
References get_simplex_involution().
get_simplex_involution_pair() [2/2]
std::pair< int8_t, int8_t > wmtk::dart::utils::get_simplex_involution_pair (PrimitiveType pt, const int8_t & a, PrimitiveType opt, const int8_t & b)
Definition at line 147 of file get_simplex_involution.cpp.
References get_simplex_involution().
Referenced by wmtk::dart::DartTopologyAccessor< Dim, MeshType >::fuse().
get_simplex_involution_upward()
int8_t wmtk::dart::utils::get_simplex_involution_upward (PrimitiveType opt, int8_t a, PrimitiveType pt, int8_t b)
Definition at line 22 of file get_simplex_involution.cpp.
References wmtk::autogen::subgroup::can_convert(), wmtk::dart::SimplexDart::convert(), wmtk::dart::find_local_dart_left_action(), wmtk::dart::SimplexDart::get_singleton(), local_simplex_decomposition(), wmtk::dart::SimplexDart::product(), and wmtk::Vertex.
Referenced by get_simplex_involution().
get_vertex_indices() [1/3]
std::array< int64_t, 2 > wmtk::dart::utils::get_vertex_indices (const EdgeMesh & m, PrimitiveType pt, const dart::Dart & d)
Definition at line 11 of file get_simplex_indices.cpp.
get_vertex_indices() [2/3]
std::array< int64_t, 4 > wmtk::dart::utils::get_vertex_indices (const TetMesh & m, PrimitiveType pt, const dart::Dart & d)
Definition at line 19 of file get_simplex_indices.cpp.
get_vertex_indices() [3/3]
std::array< int64_t, 3 > wmtk::dart::utils::get_vertex_indices (const TriMesh & m, PrimitiveType pt, const dart::Dart & d)
Definition at line 15 of file get_simplex_indices.cpp.
indexed_topology_initialization()
template<int SimplexDim, int Dim, typename MeshType > RowVectors< int64_t, internal::nCr(Dim+1, SimplexDim+1)> wmtk::dart::utils::indexed_topology_initialization (const DartTopologyAccessor< Dim, MeshType > & acc)
Definition at line 26 of file indexed_topology_initialization.hpp.
References wmtk::get_primitive_type_from_id(), wmtk::utils::DisjointSet::get_root(), wmtk::dart::SimplexDart::get_singleton(), wmtk::dart::_Dart< IndexType, OrientType >::global_id(), wmtk::dart::_Dart< IndexType, OrientType >::is_null(), wmtk::utils::DisjointSet::merge(), wmtk::dart::utils::internal::nCr(), wmtk::primitive_type_name(), wmtk::utils::DisjointSet::roots(), wmtk::dart::DartAccessor< Dim, MeshType >::size(), wmtk::utils::DisjointSet::size(), and wmtk::dart::DartTopologyAccessor< Dim, MeshType >::switch_dart().
largest_shared_subdart_size() [1/2]
int8_t wmtk::dart::utils::largest_shared_subdart_size (PrimitiveType mesh_type, int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index) -> int8_t
Definition at line 9 of file largest_shared_subdart_size.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::subdart_maximal_action_to_face_size(), wmtk::autogen::tet_mesh::subdart_maximal_action_to_face_size(), wmtk::autogen::tri_mesh::subdart_maximal_action_to_face_size(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by largest_shared_subdart_size(), wmtk::operations::internal::CollapseAlternateFacetOptionData::largest_subdart(), and wmtk::operations::internal::SplitAlternateFacetOptionData::new_gid().
largest_shared_subdart_size() [2/2]
int8_t wmtk::dart::utils::largest_shared_subdart_size (PrimitiveType mesh_type, int8_t dart_index, PrimitiveType primitive_type, int8_t simplex_index)
Definition at line 37 of file largest_shared_subdart_size.cpp.
References wmtk::get_primitive_type_id(), and largest_shared_subdart_size().
local_simplex_decomposition()
std::pair< int8_t, int8_t > wmtk::dart::utils::local_simplex_decomposition (const SimplexDart & sd, PrimitiveType pt, int8_t permutation)
Definition at line 18 of file local_simplex_decomposition.cpp.
References wmtk::dart::SimplexDart::convert(), wmtk::dart::find_local_dart_action(), get_canonical_supdart(), wmtk::dart::SimplexDart::get_singleton(), wmtk::dart::SimplexDart::identity(), and wmtk::dart::SimplexDart::simplex_type().
Referenced by apply_simplex_involution_directed(), and get_simplex_involution_upward().
opposite() [1/2]
dart::Dart wmtk::dart::utils::opposite (const SimplexDart & sd, const dart::Dart & dart)
Definition at line 35 of file opposite.cpp.
References wmtk::dart::_Dart< IndexType, OrientType >::global_id(), opposite(), and wmtk::dart::_Dart< IndexType, OrientType >::permutation().
opposite() [2/2]
int8_t wmtk::dart::utils::opposite (const SimplexDart & sd, int8_t permutation_index)
Definition at line 31 of file opposite.cpp.
References wmtk::dart::SimplexDart::act(), wmtk::get_primitive_type_id(), opposite_action(), and wmtk::dart::SimplexDart::simplex_type().
Referenced by wmtk::operations::internal::CollapseAlternateFacetOptionData::local_boundary_index(), and opposite().
opposite_action()
int8_t wmtk::dart::utils::opposite_action (int8_t simplex_dimension)
Definition at line 25 of file opposite.cpp.
Referenced by opposite().
permutation_index_from_tuple()
int8_t wmtk::dart::utils::permutation_index_from_tuple (PrimitiveType mesh_type, const Tuple & t)
Definition at line 9 of file permutation_index_from_tuple.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::permutation_index_from_tuple(), wmtk::autogen::tet_mesh::permutation_index_from_tuple(), wmtk::autogen::tri_mesh::permutation_index_from_tuple(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::dart::SimplexDart::dart_from_tuple(), and wmtk::dart::SimplexDart::permutation_index_from_tuple().
permutation_index_to_simplex_index()
int8_t wmtk::dart::utils::permutation_index_to_simplex_index (PrimitiveType mesh_type, int8_t current_orientation, PrimitiveType target_type)
Definition at line 8 of file permutation_index_to_simplex_index.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::simplex_index_from_permutation_index(), wmtk::autogen::tet_mesh::simplex_index_from_permutation_index(), wmtk::autogen::tri_mesh::simplex_index_from_permutation_index(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
permute() [1/2]
template<typename Derived > VectorXl wmtk::dart::utils::permute (const Eigen::MatrixBase< Derived > & from, int8_t permutation)
Definition at line 33 of file permute.hpp.
References from_vertex_permutation(), get_local_vertex_permutation(), wmtk::get_primitive_type_from_id(), and wmtk::dart::SimplexDart::get_singleton().
permute() [2/2]
template<size_t N> std::array< int64_t, N > wmtk::dart::utils::permute (const std::array< int64_t, N > & from, int8_t permutation)
Definition at line 15 of file permute.hpp.
References from_vertex_permutation(), get_local_vertex_permutation(), wmtk::get_primitive_type_from_id(), and wmtk::dart::SimplexDart::get_singleton().
Referenced by wmtk::multimesh::utils::extract_child_simplices_and_map_from_tag(), and wmtk::utils::internal::ManifoldDecomposition< Dim >::face_matrix().
relative_face_index()
int8_t wmtk::dart::utils::relative_face_index (const SimplexDart & sd, int8_t current_permutation, PrimitiveType target_type, int8_t target_index)
: Returns the relative local index of a simplex with respect to an permutation When we switch a dart to lie on a specific simplex we need to find some action that maps to that simplex.
We typically encode these target simplices in terms of indices used in the identity permutation, so this function rewrites an index with repsect to the identity permutation to the given input permutation
Parameters
sd the context for the type of simplex we are in
current_permutation the permutation we want to get the relative ilocal index of
target_type the type of simplex we are trying to get the relative index of
the global index of a simplex with respect to the identity dart
Definition at line 9 of file relative_face_index.cpp.
References wmtk::dart::SimplexDart::inverse(), and wmtk::dart::SimplexDart::simplex_index().
share_simplex()
bool wmtk::dart::utils::share_simplex (PrimitiveType mesh_type, PrimitiveType simplex_type, int8_t a, int8_t b)
Definition at line 6 of file share_simplex.cpp.
References wmtk::dart::SimplexDart::get_singleton(), and wmtk::dart::SimplexDart::simplex_index().
simplex_index_from_permutation_index()
auto wmtk::dart::utils::simplex_index_from_permutation_index (const PrimitiveType mesh_type, int8_t permutation_index, wmtk::PrimitiveType type) -> int8_t
Definition at line 8 of file simplex_index_from_permutation_index.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::simplex_index_from_permutation_index(), wmtk::autogen::tet_mesh::simplex_index_from_permutation_index(), wmtk::autogen::tri_mesh::simplex_index_from_permutation_index(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::dart::SimplexDart::simplex_index().
subdart_maximal_action_to_face() [1/2]
std::array< int8_t, 2 > wmtk::dart::utils::subdart_maximal_action_to_face (PrimitiveType mesh_type, int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index) -> std::array< int8_t, 2 >
Definition at line 9 of file subdart_maximal_action_to_face.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::subdart_maximal_action_to_face(), wmtk::autogen::tet_mesh::subdart_maximal_action_to_face(), wmtk::autogen::tri_mesh::subdart_maximal_action_to_face(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by subdart_maximal_action_to_face().
subdart_maximal_action_to_face() [2/2]
std::array< int8_t, 2 > wmtk::dart::utils::subdart_maximal_action_to_face (PrimitiveType mesh_type, int8_t dart_index, PrimitiveType primitive_type, int8_t simplex_index)
Definition at line 110 of file subdart_maximal_action_to_face.cpp.
References wmtk::get_primitive_type_id(), and subdart_maximal_action_to_face().
subdart_maximal_action_to_face_action() [1/2]
int8_t wmtk::dart::utils::subdart_maximal_action_to_face_action (PrimitiveType mesh_type, int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index) -> int8_t
Definition at line 37 of file subdart_maximal_action_to_face.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::subdart_maximal_action_to_face_action(), wmtk::autogen::tet_mesh::subdart_maximal_action_to_face_action(), wmtk::autogen::tri_mesh::subdart_maximal_action_to_face_action(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::operations::internal::CollapseAlternateFacetOptionData::map_permutation_to_alt(), and subdart_maximal_action_to_face_action().
subdart_maximal_action_to_face_action() [2/2]
int8_t wmtk::dart::utils::subdart_maximal_action_to_face_action (PrimitiveType mesh_type, int8_t dart_index, PrimitiveType primitive_type, int8_t simplex_index)
Definition at line 92 of file subdart_maximal_action_to_face.cpp.
References wmtk::get_primitive_type_id(), and subdart_maximal_action_to_face_action().
subdart_maximal_action_to_face_size() [1/2]
auto wmtk::dart::utils::subdart_maximal_action_to_face_size (PrimitiveType mesh_type, int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index) -> int8_t
Definition at line 64 of file subdart_maximal_action_to_face.cpp.
References wmtk::Edge, wmtk::autogen::edge_mesh::subdart_maximal_action_to_face_size(), wmtk::autogen::tet_mesh::subdart_maximal_action_to_face_size(), wmtk::autogen::tri_mesh::subdart_maximal_action_to_face_size(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by subdart_maximal_action_to_face_size().
subdart_maximal_action_to_face_size() [2/2]
int8_t wmtk::dart::utils::subdart_maximal_action_to_face_size (PrimitiveType mesh_type, int8_t dart_index, PrimitiveType primitive_type, int8_t simplex_index)
Definition at line 101 of file subdart_maximal_action_to_face.cpp.
References wmtk::get_primitive_type_id(), and subdart_maximal_action_to_face_size().
tuple_from_permutation_index()
Tuple wmtk::dart::utils::tuple_from_permutation_index (PrimitiveType mesh_type, const int64_t global_cid, int8_t valid_tuple_index)
Definition at line 9 of file tuple_from_permutation_index.cpp.
References wmtk::Edge, wmtk::Tetrahedron, wmtk::Triangle, wmtk::autogen::edge_mesh::tuple_from_permutation_index(), wmtk::autogen::tet_mesh::tuple_from_permutation_index(), wmtk::autogen::tri_mesh::tuple_from_permutation_index(), and wmtk::Vertex.
Referenced by wmtk::dart::SimplexDart::tuple_from_permutation_index(), and wmtk::dart::SimplexDart::update_tuple_from_permutation_index().