Wildmeshing Toolkit: wmtk::autogen::point_mesh Namespace Reference
wmtk::autogen::point_mesh Namespace Reference
Namespaces
namespace constants
Classes
class SimplexDart
Functions
int8_t product (int8_t a, int8_t b)
int8_t inverse (int8_t a)
int8_t permutation_index_from_primitive_switch (wmtk::PrimitiveType)
int8_t identity ()
int8_t opposite ()
int8_t simplex_index (int8_t permutation_index, wmtk::PrimitiveType type)
constexpr size_t size ()
auto permutation_indices ()
auto permutation_indices_dynamic ()
Function Documentation
identity()
int8_t wmtk::autogen::point_mesh::identity () inline
Definition at line 32 of file SimplexDart.hpp.
Referenced by wmtk::autogen::point_mesh::SimplexDart::identity().
inverse()
int8_t wmtk::autogen::point_mesh::inverse (int8_t a) inline
Definition at line 24 of file SimplexDart.hpp.
Referenced by wmtk::autogen::point_mesh::SimplexDart::inverse().
opposite()
int8_t wmtk::autogen::point_mesh::opposite () inline
Definition at line 36 of file SimplexDart.hpp.
Referenced by wmtk::autogen::point_mesh::SimplexDart::opposite().
permutation_index_from_primitive_switch()
int8_t wmtk::autogen::point_mesh::permutation_index_from_primitive_switch (wmtk::PrimitiveType) inline
Definition at line 28 of file SimplexDart.hpp.
Referenced by wmtk::autogen::point_mesh::SimplexDart::permutation_index_from_primitive_switch().
permutation_indices()
auto wmtk::autogen::point_mesh::permutation_indices () inline
Definition at line 49 of file SimplexDart.hpp.
References wmtk::autogen::point_mesh::constants::_indices.
permutation_indices_dynamic()
auto wmtk::autogen::point_mesh::permutation_indices_dynamic () inline
Definition at line 53 of file SimplexDart.hpp.
References wmtk::autogen::point_mesh::constants::_indices, and size().
Referenced by wmtk::autogen::point_mesh::SimplexDart::permutation_indices().
product()
int8_t wmtk::autogen::point_mesh::product (int8_t a, int8_t b) inline
Definition at line 19 of file SimplexDart.hpp.
Referenced by wmtk::autogen::point_mesh::SimplexDart::product().
simplex_index()
int8_t wmtk::autogen::point_mesh::simplex_index (int8_t permutation_index, wmtk::PrimitiveType type) inline
Definition at line 40 of file SimplexDart.hpp.
Referenced by wmtk::autogen::point_mesh::SimplexDart::simplex_index().
size()
constexpr size_t wmtk::autogen::point_mesh::size () inline constexpr
Definition at line 44 of file SimplexDart.hpp.
Referenced by permutation_indices_dynamic(), and wmtk::autogen::point_mesh::SimplexDart::size().