Wildmeshing Toolkit: wmtk::components::isotropic_remeshing::internal Namespace Reference
wmtk::components::isotropic_remeshing::internal Namespace Reference
Functions
std::shared_ptr< wmtk::invariants::InvariantCollection > collapse_core_invariants (Mesh &m, const IsotropicRemeshingOptions &options)
std::shared_ptr< wmtk::invariants::InvariantCollection > collapse_invariants (Mesh &m, const IsotropicRemeshingOptions &options)
void configure_collapse (operations::EdgeCollapse &ec, Mesh &m, const IsotropicRemeshingOptions &options)
std::shared_ptr< invariants::InvariantCollection > split_invariants (Mesh &m, const IsotropicRemeshingOptions &options)
void configure_split (operations::EdgeSplit &es, Mesh &m, const IsotropicRemeshingOptions &options)
std::shared_ptr< wmtk::operations::Operation > tet_swap (TetMesh &mesh, const IsotropicRemeshingOptions &options)
void configure_swap_transfer (operations::composite::EdgeSwap &swap, const attribute::MeshAttributeHandle &handle)
void finalize_swap (operations::composite::EdgeSwap &op, const IsotropicRemeshingOptions &options)
std::shared_ptr< wmtk::operations::Operation > configure_swap (Mesh &m, const IsotropicRemeshingOptions &opts)
std::shared_ptr< wmtk::operations::Operation > tet_swap56 (TetMesh &mesh, const IsotropicRemeshingOptions &options)
std::shared_ptr< wmtk::operations::Operation > tet_swap44 (TetMesh &mesh, const IsotropicRemeshingOptions &options)
std::shared_ptr< wmtk::operations::SingleAttributeTransferStrategy< double, double > > (amips_handle, position_handle, compute_amips)
Function Documentation
collapse_core_invariants()
std::shared_ptr< wmtk::invariants::InvariantCollection > wmtk::components::isotropic_remeshing::internal::collapse_core_invariants (Mesh & m, const IsotropicRemeshingOptions & options)
Definition at line 20 of file configure_collapse.cpp.
References wmtk::Mesh::get_multi_mesh_root(), and wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::separate_substructures.
Referenced by collapse_invariants(), and wmtk::components::isotropic_remeshing::IsotropicRemeshing::configure_swap().
collapse_invariants()
std::shared_ptr< wmtk::invariants::InvariantCollection > wmtk::components::isotropic_remeshing::internal::collapse_invariants (Mesh & m, const IsotropicRemeshingOptions & options)
Definition at line 40 of file configure_collapse.cpp.
References wmtk::attribute::MeshAttributeHandle::as(), collapse_core_invariants(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::get_absolute_length(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::inversion_position_attribute, wmtk::attribute::MeshAttributeHandle::mesh(), and wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::position_attribute.
Referenced by configure_collapse().
configure_collapse()
void wmtk::components::isotropic_remeshing::internal::configure_collapse (operations::EdgeCollapse & ec, Mesh & m, const IsotropicRemeshingOptions & options)
Definition at line 87 of file configure_collapse.cpp.
References wmtk::operations::Operation::add_invariant(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::all_positions(), wmtk::Mesh::can_map(), collapse_invariants(), wmtk::Edge, wmtk::Mesh::get_all_child_meshes(), wmtk::components::multimesh::MeshCollection::get_mesh(), wmtk::Mesh::get_multi_mesh_root(), wmtk::operations::EdgeCollapse::get_new_attribute_strategy(), wmtk::operations::IsInterior, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::lock_boundary, wmtk::operations::Mean, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::mesh_collection, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::pass_through_attributes, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::position_attribute, wmtk::operations::EdgeCollapse::set_new_attribute_strategy(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::static_meshes, wmtk::Tetrahedron, wmtk::Triangle, wmtk::simplex::Simplex::tuple(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::use_for_periodic, and wmtk::Vertex.
Referenced by wmtk::components::isotropic_remeshing::IsotropicRemeshing::configure_collapse().
configure_split()
void wmtk::components::isotropic_remeshing::internal::configure_split (operations::EdgeSplit & es, Mesh & m, const IsotropicRemeshingOptions & options)
Definition at line 28 of file configure_split.cpp.
References wmtk::operations::Operation::add_invariant(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::all_positions(), wmtk::operations::Mean, wmtk::operations::None, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::pass_through_attributes, wmtk::operations::EdgeSplit::set_new_attribute_strategy(), and split_invariants().
Referenced by wmtk::components::isotropic_remeshing::IsotropicRemeshing::configure_split().
configure_swap()
std::shared_ptr< wmtk::operations::Operation > wmtk::components::isotropic_remeshing::internal::configure_swap (Mesh & m, const IsotropicRemeshingOptions & opts)
configure_swap_transfer()
void wmtk::components::isotropic_remeshing::internal::configure_swap_transfer (operations::composite::EdgeSwap & swap, const attribute::MeshAttributeHandle & handle)
Definition at line 152 of file configure_swap.cpp.
References wmtk::operations::composite::EdgeSwap::collapse(), wmtk::operations::CopyOther, wmtk::Edge, wmtk::attribute::MeshAttributeHandle::primitive_type(), wmtk::operations::EdgeCollapse::set_new_attribute_strategy(), wmtk::operations::EdgeSplit::set_new_attribute_strategy(), wmtk::operations::composite::EdgeSwap::split(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::components::isotropic_remeshing::IsotropicRemeshing::configure_swap().
finalize_swap()
void wmtk::components::isotropic_remeshing::internal::finalize_swap (operations::composite::EdgeSwap & op, const IsotropicRemeshingOptions & options)
Referenced by tet_swap56().
split_invariants()
std::shared_ptr< invariants::InvariantCollection > wmtk::components::isotropic_remeshing::internal::split_invariants (Mesh & m, const IsotropicRemeshingOptions & options)
Definition at line 14 of file configure_split.cpp.
References wmtk::attribute::MeshAttributeHandle::as(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::get_absolute_length(), wmtk::attribute::MeshAttributeHandle::mesh(), and wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::position_attribute.
Referenced by configure_split().
std::shared_ptr< wmtk::operations::SingleAttributeTransferStrategy< double, double > >()
wmtk::components::isotropic_remeshing::internal::std::shared_ptr< wmtk::operations::SingleAttributeTransferStrategy< double, double > > (amips_handle , position_handle , compute_amips)
tet_swap()
std::shared_ptr< wmtk::operations::Operation > wmtk::components::isotropic_remeshing::internal::tet_swap (TetMesh & mesh, const IsotropicRemeshingOptions & options)
Definition at line 310 of file configure_swap_tetmesh.cpp.
References wmtk::attribute::MeshAttributeHandle::create_accessor(), wmtk::Edge, wmtk::attribute::MeshAttributeHandle::mesh(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::position_attribute, wmtk::Mesh::register_attribute(), tet_swap44(), tet_swap56(), and wmtk::Vertex.
tet_swap44()
std::shared_ptr< wmtk::operations::Operation > wmtk::components::isotropic_remeshing::internal::tet_swap44 (TetMesh & mesh, const IsotropicRemeshingOptions & options)
Definition at line 142 of file configure_swap_tetmesh.cpp.
References wmtk::attribute::MeshAttributeHandle::as(), wmtk::MeshCRTP< Derived >::create_const_accessor(), wmtk::Edge, wmtk::attribute::MeshAttributeHandle::holds(), wmtk::PE, PF, wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::position_attribute, PT, wmtk::PV, wmtk::TetMesh::switch_tuple(), wmtk::MeshCRTP< Derived >::switch_tuples(), wmtk::function::utils::Tet_AMIPS_energy(), wmtk::Tetrahedron, wmtk::Triangle, wmtk::Vertex, and wmtk::utils::wmtk_orient3d().
Referenced by tet_swap().
tet_swap56()
std::shared_ptr< wmtk::operations::Operation > wmtk::components::isotropic_remeshing::internal::tet_swap56 (TetMesh & mesh, const IsotropicRemeshingOptions & options)
Definition at line 111 of file configure_swap_tetmesh.cpp.
References wmtk::attribute::MeshAttributeHandle::as(), finalize_swap(), wmtk::attribute::MeshAttributeHandle::holds(), and wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::position_attribute.
Referenced by tet_swap().