Wildmeshing Toolkit: wmtk::dart::utils::detail Namespace Reference
wmtk::dart::utils::detail Namespace Reference
Classes
struct simplex_dart_type_from_dimension
struct simplex_dart_type_from_dimension< 0 >
struct simplex_dart_type_from_dimension< 1 >
struct simplex_dart_type_from_dimension< 2 >
struct simplex_dart_type_from_dimension< 3 >
Typedefs
template<int8_t Dim>
using simplex_dart_type_from_dimension_t = typename simplex_dart_type_from_dimension< Dim >::type
Functions
template<typename IntLike , size_t D>
std::map< IntLike, int8_t > local_index_map (const std::array< IntLike, D > &S)
template<typename IntLike , size_t D, size_t d>
std::array< int8_t, D > get_relative_indices (const std::array< IntLike, D > &S, const std::array< IntLike, d > &s)
Typedef Documentation
simplex_dart_type_from_dimension_t
template<int8_t Dim> using wmtk::dart::utils::detail::simplex_dart_type_from_dimension_t = typedef typename simplex_dart_type_from_dimension<Dim>::type
Definition at line 17 of file get_simplex_dart.hpp.
Function Documentation
get_relative_indices()
template<typename IntLike , size_t D, size_t d> std::array< int8_t, D > wmtk::dart::utils::detail::get_relative_indices (const std::array< IntLike, D > & S, const std::array< IntLike, d > & s)
Definition at line 23 of file get_relative_indices.hpp.
References local_index_map().
Referenced by wmtk::dart::utils::from_vertex_permutation().
local_index_map()
template<typename IntLike , size_t D> std::map< IntLike, int8_t > wmtk::dart::utils::detail::local_index_map (const std::array< IntLike, D > & S)
Definition at line 10 of file get_relative_indices.hpp.
Referenced by wmtk::dart::utils::get_canonical_subdart_permutation_indices(), and get_relative_indices().