Wildmeshing Toolkit: wmtk::components::multimesh::utils Namespace Reference
wmtk::components::multimesh::utils Namespace Reference
Namespaces
namespace detail
Classes
struct AttributeDescription
Functions
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (AttributeDescription)
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (AttributeDescription)
std::vector< std::array< Tuple, 2 > > concatenate (std::span< const std::vector< std::array< Tuple, 2 > > > container)
MatrixXl concatenate (std::span< const MatrixXl > container)
wmtk::attribute::MeshAttributeHandle create_attribute (NamedMultiMesh &mesh, const AttributeDescription &description)
wmtk::attribute::MeshAttributeHandle create_attribute (MeshCollection &mesh, const AttributeDescription &description)
wmtk::attribute::MeshAttributeHandle create_attribute (Mesh &mesh, const AttributeDescription &description)
auto decompose_attribute_path (std::string_view attribute_path)
auto decompose_attribute_path (const AttributeDescription &description)
auto get_mesh_path_from_attribute_path (auto &&attribute)
auto get_attribute_name_from_attribute_path (auto &&attribute)
wmtk::attribute::MeshAttributeHandle get_attribute (const NamedMultiMesh &mesh, const AttributeDescription &description)
wmtk::attribute::MeshAttributeHandle get_attribute (const MeshCollection &mesh, const AttributeDescription &description)
wmtk::attribute::MeshAttributeHandle get_attribute (const Mesh &mesh, const AttributeDescription &description)
std::vector< wmtk::attribute::MeshAttributeHandle > get_attributes (const NamedMultiMesh &mesh, const AttributeDescription &description)
std::vector< wmtk::attribute::MeshAttributeHandle > get_attributes (const MeshCollection &mesh, const AttributeDescription &description)
std::vector< wmtk::attribute::MeshAttributeHandle > get_attributes (const Mesh &mesh, const AttributeDescription &description)
AttributeDescription get_attribute_handle (const MeshCollection &collection, const wmtk::attribute::MeshAttributeHandle &handle)
AttributeDescription get_attribute_handle (const NamedMultiMesh &nmm, const wmtk::attribute::MeshAttributeHandle &handle)
Function Documentation
concatenate() [1/2]
MatrixXl wmtk::components::multimesh::utils::concatenate (std::span< const MatrixXl > container)
Definition at line 32 of file concatenate.cpp.
concatenate() [2/2]
std::vector< std::array< Tuple, 2 > > wmtk::components::multimesh::utils::concatenate (std::span< const std::vector< std::array< Tuple, 2 > > > container)
Definition at line 4 of file concatenate.cpp.
Referenced by TEST_CASE(), and TEST_CASE().
create_attribute() [1/3]
wmtk::attribute::MeshAttributeHandle wmtk::components::multimesh::utils::create_attribute (Mesh & mesh, const AttributeDescription & description)
Definition at line 82 of file create_attribute.cpp.
References wmtk::components::multimesh::utils::detail::create_attribute(), decompose_attribute_path(), wmtk::components::multimesh::utils::AttributeDescription::dimension, wmtk::components::multimesh::utils::AttributeDescription::fully_specified(), wmtk::components::multimesh::utils::AttributeDescription::primitive_type(), and wmtk::components::multimesh::utils::AttributeDescription::type.
create_attribute() [2/3]
wmtk::attribute::MeshAttributeHandle wmtk::components::multimesh::utils::create_attribute (MeshCollection & mesh, const AttributeDescription & description)
Definition at line 66 of file create_attribute.cpp.
References wmtk::components::multimesh::utils::detail::create_attribute(), decompose_attribute_path(), wmtk::components::multimesh::utils::AttributeDescription::dimension, wmtk::components::multimesh::utils::AttributeDescription::fully_specified(), wmtk::components::multimesh::MeshCollection::get_mesh(), wmtk::components::multimesh::utils::AttributeDescription::primitive_type(), and wmtk::components::multimesh::utils::AttributeDescription::type.
create_attribute() [3/3]
wmtk::attribute::MeshAttributeHandle wmtk::components::multimesh::utils::create_attribute (NamedMultiMesh & mesh, const AttributeDescription & description)
Definition at line 53 of file create_attribute.cpp.
References wmtk::components::multimesh::utils::detail::create_attribute(), decompose_attribute_path(), wmtk::components::multimesh::utils::AttributeDescription::dimension, wmtk::components::multimesh::utils::AttributeDescription::fully_specified(), wmtk::components::multimesh::NamedMultiMesh::get_mesh(), wmtk::components::multimesh::utils::AttributeDescription::primitive_type(), and wmtk::components::multimesh::utils::AttributeDescription::type.
Referenced by wmtk::components::mesh_info::transfer::SingleAttributeTransferStrategyFactory< Functor >::create_transfer(), and wmtk::components::isotropic_remeshing::IsotropicRemeshing::load_transfers().
decompose_attribute_path() [1/2]
auto wmtk::components::multimesh::utils::decompose_attribute_path (const AttributeDescription & description) inline
Definition at line 25 of file decompose_attribute_path.hpp.
References decompose_attribute_path(), and wmtk::components::multimesh::utils::AttributeDescription::path.
decompose_attribute_path() [2/2]
auto wmtk::components::multimesh::utils::decompose_attribute_path (std::string_view attribute_path) inline
Definition at line 8 of file decompose_attribute_path.hpp.
Referenced by create_attribute(), create_attribute(), create_attribute(), decompose_attribute_path(), get_attribute(), get_attribute(), get_attribute(), get_attribute_name_from_attribute_path(), get_attributes(), get_attributes(), get_attributes(), get_mesh_path_from_attribute_path(), and wmtk::components::multimesh::MultimeshAxisAlignedFusionOptions::run().
get_attribute() [1/3]
wmtk::attribute::MeshAttributeHandle wmtk::components::multimesh::utils::get_attribute (const Mesh & mesh, const AttributeDescription & description)
Definition at line 268 of file get_attribute.cpp.
References decompose_attribute_path(), wmtk::components::multimesh::utils::AttributeDescription::dimension, wmtk::components::multimesh::utils::detail::get_attribute(), wmtk::components::multimesh::utils::AttributeDescription::primitive_type(), and wmtk::components::multimesh::utils::AttributeDescription::type.
get_attribute() [2/3]
wmtk::attribute::MeshAttributeHandle wmtk::components::multimesh::utils::get_attribute (const MeshCollection & mesh, const AttributeDescription & description)
Definition at line 253 of file get_attribute.cpp.
References decompose_attribute_path(), wmtk::components::multimesh::utils::AttributeDescription::dimension, wmtk::components::multimesh::utils::detail::get_attribute(), wmtk::components::multimesh::MeshCollection::get_mesh(), wmtk::components::multimesh::utils::AttributeDescription::primitive_type(), and wmtk::components::multimesh::utils::AttributeDescription::type.
get_attribute() [3/3]
wmtk::attribute::MeshAttributeHandle wmtk::components::multimesh::utils::get_attribute (const NamedMultiMesh & mesh, const AttributeDescription & description)
Definition at line 241 of file get_attribute.cpp.
References decompose_attribute_path(), wmtk::components::multimesh::utils::AttributeDescription::dimension, wmtk::components::multimesh::utils::detail::get_attribute(), wmtk::components::multimesh::NamedMultiMesh::get_mesh(), wmtk::components::multimesh::utils::AttributeDescription::primitive_type(), and wmtk::components::multimesh::utils::AttributeDescription::type.
Referenced by wmtk::components::isotropic_remeshing::PriorityOptions::assign_to(), wmtk::components::mesh_info::transfer::SingleAttributeTransferStrategyFactory< Functor >::create_transfer(), wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::get_absolute_length(), wmtk::components::isotropic_remeshing::IsotropicRemeshing::get_attribute(), wmtk::components::mesh_info::transfer::SingleAttributeTransferStrategyFactory< Functor >::get_output_attribute_description(), wmtk::components::mesh_info::transfer::TransferStrategyFactory::get_output_attribute_handle(), wmtk::components::output::output(), wmtk::components::multimesh::MultimeshAxisAlignedFusionOptions::run(), wmtk::components::multimesh::MultimeshTagOptions::run(), TEST_CASE(), TEST_CASE(), and wmtk::components::multimesh::MultimeshTagOptions::toTagOptions().
get_attribute_handle() [1/2]
AttributeDescription wmtk::components::multimesh::utils::get_attribute_handle (const MeshCollection & collection, const wmtk::attribute::MeshAttributeHandle & handle)
Definition at line 8 of file get_attribute_description.cpp.
get_attribute_handle() [2/2]
AttributeDescription wmtk::components::multimesh::utils::get_attribute_handle (const NamedMultiMesh & nmm, const wmtk::attribute::MeshAttributeHandle & handle)
Definition at line 14 of file get_attribute_description.cpp.
References wmtk::components::multimesh::NamedMultiMesh::get_name(), and wmtk::attribute::MeshAttributeHandle::mesh().
get_attribute_name_from_attribute_path()
auto wmtk::components::multimesh::utils::get_attribute_name_from_attribute_path (auto && attribute) inline
Definition at line 33 of file decompose_attribute_path.hpp.
References decompose_attribute_path().
get_attributes() [1/3]
std::vector< wmtk::attribute::MeshAttributeHandle > wmtk::components::multimesh::utils::get_attributes (const Mesh & mesh, const AttributeDescription & description)
Definition at line 308 of file get_attribute.cpp.
References decompose_attribute_path(), wmtk::components::multimesh::utils::AttributeDescription::dimension, wmtk::components::multimesh::utils::detail::get_attributes(), wmtk::components::multimesh::utils::AttributeDescription::primitive_type(), and wmtk::components::multimesh::utils::AttributeDescription::type.
get_attributes() [2/3]
std::vector< wmtk::attribute::MeshAttributeHandle > wmtk::components::multimesh::utils::get_attributes (const MeshCollection & mesh, const AttributeDescription & description)
Definition at line 293 of file get_attribute.cpp.
References decompose_attribute_path(), wmtk::components::multimesh::utils::AttributeDescription::dimension, wmtk::components::multimesh::utils::detail::get_attributes(), wmtk::components::multimesh::MeshCollection::get_mesh(), wmtk::components::multimesh::utils::AttributeDescription::primitive_type(), and wmtk::components::multimesh::utils::AttributeDescription::type.
get_attributes() [3/3]
std::vector< wmtk::attribute::MeshAttributeHandle > wmtk::components::multimesh::utils::get_attributes (const NamedMultiMesh & mesh, const AttributeDescription & description)
Definition at line 281 of file get_attribute.cpp.
References decompose_attribute_path(), wmtk::components::multimesh::utils::AttributeDescription::dimension, wmtk::components::multimesh::utils::detail::get_attributes(), wmtk::components::multimesh::NamedMultiMesh::get_mesh(), wmtk::components::multimesh::utils::AttributeDescription::primitive_type(), and wmtk::components::multimesh::utils::AttributeDescription::type.
get_mesh_path_from_attribute_path()
auto wmtk::components::multimesh::utils::get_mesh_path_from_attribute_path (auto && attribute) inline
Definition at line 29 of file decompose_attribute_path.hpp.
References decompose_attribute_path().
Referenced by wmtk::components::multimesh::MeshCollection::get_named_multimesh(), and wmtk::components::multimesh::MeshCollection::get_named_multimesh().
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE()
wmtk::components::multimesh::utils::WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (AttributeDescription)
Definition at line 49 of file AttributeDescription.cpp.
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE()
wmtk::components::multimesh::utils::WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (AttributeDescription)
Definition at line 36 of file AttributeDescription.cpp.
References WMTK_NLOHMANN_ASSIGN_TYPE_TO_JSON.