Wildmeshing Toolkit: wmtk::utils::internal Namespace Reference
wmtk::utils::internal Namespace Reference
Namespaces
namespace detail
Classes
class IndexSimplexMapper
struct ManifoldDecomposition
Functions
template<int8_t SimplexDim, int8_t FaceDim>
std::map< int64_t, std::set< dart::Dart > > cofacets (const IndexSimplexMapper &ism)
template<int8_t Dim>
std::map< int64_t, std::set< dart::Dart > > coboundary (const IndexSimplexMapper &ism)
std::map< int64_t, std::set< dart::Dart > > coboundary (const IndexSimplexMapper &ism, int8_t dim)
template std::map< int64_t, std::set< dart::Dart > > cofacets< 1, 0 > (const IndexSimplexMapper &ism)
template std::map< int64_t, std::set< dart::Dart > > cofacets< 2, 1 > (const IndexSimplexMapper &ism)
template std::map< int64_t, std::set< dart::Dart > > cofacets< 2, 0 > (const IndexSimplexMapper &ism)
template std::map< int64_t, std::set< dart::Dart > > cofacets< 3, 0 > (const IndexSimplexMapper &ism)
template std::map< int64_t, std::set< dart::Dart > > cofacets< 3, 1 > (const IndexSimplexMapper &ism)
template std::map< int64_t, std::set< dart::Dart > > cofacets< 3, 2 > (const IndexSimplexMapper &ism)
template std::map< int64_t, std::set< dart::Dart > > coboundary< 1 > (const IndexSimplexMapper &ism)
template std::map< int64_t, std::set< dart::Dart > > coboundary< 2 > (const IndexSimplexMapper &ism)
template std::map< int64_t, std::set< dart::Dart > > coboundary< 3 > (const IndexSimplexMapper &ism)
template<typename Derived >
auto compactify_eigen_indices (const Eigen::MatrixBase< Derived > &M)
Tuple identity_tuple (PrimitiveType pt, int64_t gid)
template<int Dim>
auto get_input_index (Eigen::Ref< const RowVector< int64_t, Dim > > s, const std::map< std::array< int64_t, Dim >, dart::Dart > &mp) -> const dart::Dart &
bool is_manifold (const Mesh &m)
template<int Dim>
ManifoldDecomposition< Dim > boundary_manifold_decomposition (Eigen::Ref< const RowVectors< int64_t, Dim > > S)
template<int Dim>
RowVectors< int64_t, Dim > manifold_decomposition (Eigen::Ref< const RowVectors< int64_t, Dim > > S)
Function Documentation
boundary_manifold_decomposition()
template<int Dim> ManifoldDecomposition< Dim > wmtk::utils::internal::boundary_manifold_decomposition (Eigen::Ref< const RowVectors< int64_t, Dim > > S)
Definition at line 51 of file manifold_decomposition.hpp.
References coboundary(), wmtk::utils::internal::ManifoldDecomposition< Dim >::face_map, wmtk::get_primitive_type_from_id(), wmtk::utils::DisjointSet::get_root(), wmtk::dart::SimplexDart::get_singleton(), wmtk::utils::internal::ManifoldDecomposition< Dim >::manifold_decomposition, wmtk::utils::DisjointSet::merge(), wmtk::utils::DisjointSet::roots(), and wmtk::utils::internal::IndexSimplexMapper::simplices().
Referenced by wmtk::components::multimesh::NonManifoldCascade::init().
coboundary() [1/2]
template<int8_t Dim> std::map< int64_t, std::set< dart::Dart > > wmtk::utils::internal::coboundary (const IndexSimplexMapper & ism)
Definition at line 127 of file cofacets.cpp.
References cofacets().
Referenced by boundary_manifold_decomposition(), and cofacets().
coboundary() [2/2]
std::map< int64_t, std::set< dart::Dart > > wmtk::utils::internal::coboundary (const IndexSimplexMapper & ism, int8_t dim)
Definition at line 166 of file cofacets.cpp.
References coboundary< 1 >(), coboundary< 2 >(), and coboundary< 3 >().
coboundary< 1 >()
template std::map< int64_t, std::set< dart::Dart > > wmtk::utils::internal::coboundary< 1 > (const IndexSimplexMapper & ism)
Referenced by coboundary().
coboundary< 2 >()
template std::map< int64_t, std::set< dart::Dart > > wmtk::utils::internal::coboundary< 2 > (const IndexSimplexMapper & ism)
Referenced by coboundary().
coboundary< 3 >()
template std::map< int64_t, std::set< dart::Dart > > wmtk::utils::internal::coboundary< 3 > (const IndexSimplexMapper & ism)
Referenced by coboundary().
cofacets()
template<int8_t SimplexDim, int8_t FaceDim> std::map< int64_t, std::set< dart::Dart > > wmtk::utils::internal::cofacets (const IndexSimplexMapper & ism)
Definition at line 93 of file cofacets.cpp.
References coboundary(), wmtk::dart::utils::get_canonical_subdart_permutation(), and wmtk::utils::internal::IndexSimplexMapper::get_index().
Referenced by coboundary().
cofacets< 1, 0 >()
template std::map< int64_t, std::set< dart::Dart > > wmtk::utils::internal::cofacets< 1, 0 > (const IndexSimplexMapper & ism)
cofacets< 2, 0 >()
template std::map< int64_t, std::set< dart::Dart > > wmtk::utils::internal::cofacets< 2, 0 > (const IndexSimplexMapper & ism)
cofacets< 2, 1 >()
template std::map< int64_t, std::set< dart::Dart > > wmtk::utils::internal::cofacets< 2, 1 > (const IndexSimplexMapper & ism)
cofacets< 3, 0 >()
template std::map< int64_t, std::set< dart::Dart > > wmtk::utils::internal::cofacets< 3, 0 > (const IndexSimplexMapper & ism)
cofacets< 3, 1 >()
template std::map< int64_t, std::set< dart::Dart > > wmtk::utils::internal::cofacets< 3, 1 > (const IndexSimplexMapper & ism)
cofacets< 3, 2 >()
template std::map< int64_t, std::set< dart::Dart > > wmtk::utils::internal::cofacets< 3, 2 > (const IndexSimplexMapper & ism)
compactify_eigen_indices()
template<typename Derived > auto wmtk::utils::internal::compactify_eigen_indices (const Eigen::MatrixBase< Derived > & M)
Definition at line 8 of file compactify_eigen_indices.hpp.
Referenced by wmtk::multimesh::utils::extract_child_simplices_and_map_from_tag(), wmtk::utils::internal::ManifoldDecomposition< Dim >::face_matrix(), and wmtk::components::multimesh::from_manifold_decomposition().
get_input_index()
template<int Dim> auto wmtk::utils::internal::get_input_index (Eigen::Ref< const RowVector< int64_t, Dim > > s, const std::map< std::array< int64_t, Dim >, dart::Dart > & mp) -> const dart::Dart&
Definition at line 395 of file IndexSimplexMapper.cpp.
identity_tuple()
Tuple wmtk::utils::internal::identity_tuple (PrimitiveType pt, int64_t gid)
Definition at line 5 of file identity_tuple.cpp.
References wmtk::dart::SimplexDart::get_singleton().
Referenced by wmtk::multimesh::from_facet_orientations(), and wmtk::TetMesh::tet_tuple_from_id().
is_manifold()
bool wmtk::utils::internal::is_manifold (const Mesh & m)
Definition at line 103 of file is_manifold.cpp.
References wmtk::Edge, wmtk::Mesh::get_all(), wmtk::Tetrahedron, wmtk::Mesh::top_simplex_type(), wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::multimesh::utils::internal::TupleTag::extract_and_register_child_mesh_from_tag_handle().
manifold_decomposition()
template<int Dim> RowVectors< int64_t, Dim > wmtk::utils::internal::manifold_decomposition (Eigen::Ref< const RowVectors< int64_t, Dim > > S)
Definition at line 197 of file manifold_decomposition.hpp.
References wmtk::logger().
Referenced by wmtk::utils::internal::ManifoldDecomposition< Dim >::face_matrix().