Wildmeshing Toolkit: wmtk::components::mesh_info::transfer Namespace Reference
wmtk::components::mesh_info::transfer Namespace Reference
Classes
struct CoeffWiseTransfer
struct EdgeAngleFunctor
struct EdgeLengthFunctor
struct FilteredNeighborCountFunctor
struct MaxNeighborFunctor
struct MeanNeighborFunctor
struct MeanRatioMeasureFunctor
struct MinNeighborFunctor
struct NegateFunctor
struct NeighborCountFunctor
struct NeighborSumFunctor
struct NormalFunctor
struct SingleAttributeTransferStrategyFactory
struct SingleAttributeTransferStrategyFactoryBase
struct ThresholdFunctor
struct TransferFunctorTraits
struct TransferStrategyFactory
class TransferStrategyFactoryRegistry
struct VolumeFunctor
Typedefs
using EdgeAngle = SingleAttributeTransferStrategyFactory< EdgeAngleFunctor >
using EdgeLength = SingleAttributeTransferStrategyFactory< EdgeLengthFunctor >
using FilteredNeighborCount = SingleAttributeTransferStrategyFactory< FilteredNeighborCountFunctor >
using MaxNeighbor = SingleAttributeTransferStrategyFactory< MaxNeighborFunctor >
using MeanNeighbor = SingleAttributeTransferStrategyFactory< MeanNeighborFunctor >
using MeanRatioMeasure = SingleAttributeTransferStrategyFactory< MeanRatioMeasureFunctor >
using MinNeighbor = SingleAttributeTransferStrategyFactory< MinNeighborFunctor >
using Negate = SingleAttributeTransferStrategyFactory< NegateFunctor >
using NeighborCount = SingleAttributeTransferStrategyFactory< NeighborCountFunctor >
using NeighborSum = SingleAttributeTransferStrategyFactory< NeighborSumFunctor >
using Normal = SingleAttributeTransferStrategyFactory< NormalFunctor >
using Threshold = SingleAttributeTransferStrategyFactory< ThresholdFunctor >
using TransferStrategyFactoryCollection = std::vector< std::shared_ptr< mesh_info::transfer::TransferStrategyFactory > >
using Volume = SingleAttributeTransferStrategyFactory< VolumeFunctor >
Functions
TransferStrategyFactoryRegistry create_registry ()
void init ()
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (TransferStrategyFactory)
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (TransferStrategyFactory)
void to_json (nlohmann::json &, const TransferStrategyFactory &)
void from_json (const nlohmann::json &, TransferStrategyFactory &)
void to_json (nlohmann::json &j, const TransferStrategyFactoryCollection &value)
void from_json (const nlohmann::json &j, TransferStrategyFactoryCollection &value)
Typedef Documentation
EdgeAngle
using wmtk::components::mesh_info::transfer::EdgeAngle = typedef SingleAttributeTransferStrategyFactory<EdgeAngleFunctor>
Definition at line 80 of file edge_angle.hpp.
EdgeLength
using wmtk::components::mesh_info::transfer::EdgeLength = typedef SingleAttributeTransferStrategyFactory<EdgeLengthFunctor>
Definition at line 43 of file edge_length.hpp.
FilteredNeighborCount
using wmtk::components::mesh_info::transfer::FilteredNeighborCount = typedef SingleAttributeTransferStrategyFactory<FilteredNeighborCountFunctor>
Definition at line 60 of file filtered_neighbor_count.hpp.
MaxNeighbor
using wmtk::components::mesh_info::transfer::MaxNeighbor = typedef SingleAttributeTransferStrategyFactory<MaxNeighborFunctor>
Definition at line 31 of file max_neighbor.hpp.
MeanNeighbor
using wmtk::components::mesh_info::transfer::MeanNeighbor = typedef SingleAttributeTransferStrategyFactory<MeanNeighborFunctor>
Definition at line 32 of file mean_neighbor.hpp.
MeanRatioMeasure
using wmtk::components::mesh_info::transfer::MeanRatioMeasure = typedef SingleAttributeTransferStrategyFactory<MeanRatioMeasureFunctor>
Definition at line 80 of file mean_ratio_measure.hpp.
MinNeighbor
using wmtk::components::mesh_info::transfer::MinNeighbor = typedef SingleAttributeTransferStrategyFactory<MinNeighborFunctor>
Definition at line 33 of file min_neighbor.hpp.
Negate
using wmtk::components::mesh_info::transfer::Negate = typedef SingleAttributeTransferStrategyFactory<NegateFunctor>
Definition at line 55 of file negate.hpp.
NeighborCount
using wmtk::components::mesh_info::transfer::NeighborCount = typedef SingleAttributeTransferStrategyFactory<NeighborCountFunctor>
Definition at line 57 of file neighbor_count.hpp.
NeighborSum
using wmtk::components::mesh_info::transfer::NeighborSum = typedef SingleAttributeTransferStrategyFactory<NeighborSumFunctor>
Definition at line 31 of file neighbor_sum.hpp.
Normal
using wmtk::components::mesh_info::transfer::Normal = typedef SingleAttributeTransferStrategyFactory<NormalFunctor>
Definition at line 67 of file normal.hpp.
Threshold
using wmtk::components::mesh_info::transfer::Threshold = typedef SingleAttributeTransferStrategyFactory<ThresholdFunctor>
Definition at line 76 of file threshold.hpp.
TransferStrategyFactoryCollection
using wmtk::components::mesh_info::transfer::TransferStrategyFactoryCollection = typedef std::vector<std::shared_ptr<mesh_info::transfer::TransferStrategyFactory> >
Definition at line 8 of file TransferStrategyFactoryCollection.hpp.
Volume
using wmtk::components::mesh_info::transfer::Volume = typedef SingleAttributeTransferStrategyFactory<VolumeFunctor>
Definition at line 60 of file volume.hpp.
Function Documentation
create_registry()
TransferStrategyFactoryRegistry wmtk::components::mesh_info::transfer::create_registry ()
Definition at line 14 of file init.cpp.
References wmtk::components::mesh_info::transfer::TransferStrategyFactoryRegistry::register_transfer().
from_json() [1/2]
void wmtk::components::mesh_info::transfer::from_json (const nlohmann::json & , TransferStrategyFactory &)
from_json() [2/2]
void wmtk::components::mesh_info::transfer::from_json (const nlohmann::json & j, TransferStrategyFactoryCollection & value)
Definition at line 17 of file TransferStrategyFactoryCollection.cpp.
References wmtk::components::mesh_info::transfer::TransferStrategyFactory::transfer_registry().
init()
void wmtk::components::mesh_info::transfer::init ()
Definition at line 32 of file init.cpp.
Referenced by wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::IsotropicRemeshingOptions().
to_json() [1/2]
void wmtk::components::mesh_info::transfer::to_json (nlohmann::json & , const TransferStrategyFactory &)
to_json() [2/2]
void wmtk::components::mesh_info::transfer::to_json (nlohmann::json & j, const TransferStrategyFactoryCollection & value)
Definition at line 5 of file TransferStrategyFactoryCollection.cpp.
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE()
wmtk::components::mesh_info::transfer::WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (TransferStrategyFactory)
Definition at line 44 of file TransferStrategyFactory.cpp.
References WMTK_NLOHMANN_ASSIGN_TYPE_FROM_JSON.
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE()
wmtk::components::mesh_info::transfer::WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (TransferStrategyFactory)
Definition at line 38 of file TransferStrategyFactory.cpp.
References WMTK_NLOHMANN_ASSIGN_TYPE_TO_JSON.