Wildmeshing Toolkit: wmtk::autogen::tri_mesh Namespace Reference
wmtk::autogen::tri_mesh Namespace Reference
Namespaces
namespace constants
namespace internal
Classes
class SimplexDart
Functions
Tuple get_tuple_from_simplex_local_vertex_id (int8_t local_id, int64_t global_id)
Tuple get_tuple_from_simplex_local_edge_id (int8_t local_id, int64_t global_id)
Tuple get_tuple_from_simplex_local_id (PrimitiveType pt, int8_t local_id, int64_t global_fid)
bool is_ccw (const Tuple &t)
bool tuple_is_valid_for_ccw (const Tuple &t)
int64_t local_id_table_offset (const Tuple &t)
std::array< int64_t, 2 > lvid_leid_from_table_offset (int64_t table_offset)
Tuple local_switch_tuple (const Tuple &t, PrimitiveType pt)
Tuple local_switch_tuple (const Tuple &t, int8_t index)
int8_t permutation_index_from_tuple (const Tuple &t)
int8_t simplex_index_from_permutation_index (int8_t permutation_index, wmtk::PrimitiveType type)
int8_t product (int8_t a, int8_t b)
int8_t inverse (int8_t a)
int8_t permutation_index_from_primitive_switch (wmtk::PrimitiveType pt)
int8_t identity ()
int8_t opposite ()
constexpr size_t size ()
auto permutation_indices ()
auto permutation_indices_dynamic ()
int8_t simplex_index (int8_t permutation_index, wmtk::PrimitiveType type)
int8_t subdart_maximal_action_to_face_action (int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index)
int8_t subdart_maximal_action_to_face_size (int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index)
std::array< int8_t, 2 > subdart_maximal_action_to_face (int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index)
Returns a dart action that maximizes the number of sub-darts preserved.
Tuple tuple_from_permutation_index (int64_t global_cid, int8_t valid_tuple_index)
Variables
const int64_t auto_2d_edges [3][2] = {{1, 2}, {0, 2}, {0, 1}}
const int64_t auto_2d_table_vertex [9][2]
const int64_t auto_2d_table_edge [9][2]
const int64_t auto_2d_table_ccw [9] = {-1, 0, 1, 1, -1, 0, 0, 1, -1}
const int64_t auto_2d_table_complete_vertex [3][2] = {{0, 2}, {1, 0}, {2, 1}}
const int64_t auto_2d_table_complete_edge [3][2] = {{1, 0}, {2, 1}, {0, 2}}
const int8_t auto_valid_tuples [6][2] = {{0, 1}, {0, 2}, {1, 0}, {1, 2}, {2, 0}, {2, 1}}
const int8_t auto_valid_tuple_indices [6] = {1, 2, 3, 5, 6, 7}
const int8_t auto_all_to_valid_tuple_indices [9] = {-1, 0, 1, 2, -1, 3, 4, 5, -1}
const int8_t auto_valid_switch_table [6][2] = {{5, 1}, {3, 0}, {4, 3}, {1, 2}, {2, 5}, {0, 4}}
const int8_t auto_valid_switch_product_table [6][6]
const int8_t auto_valid_switch_inverse_table [6] = {0, 1, 5, 3, 4, 2}
const int8_t auto_valid_tuple_switch_indices [4] = {3, 0, 1, 4}
const int8_t auto_valid_switch_edge_mirror_indices [6] = {2, 3, 0, 1, 5, 4}
const int8_t subdart_preserving_action_1 [6][3]
const int8_t max_subdart_preservation_dimension_1 [6][3]
const int8_t canonical_faces_0 [3] = {1, 3, 5}
const int8_t canonical_cofaces_0 [3] = {5, 3, 1}
const int8_t canonical_faces_1 [3] = {2, 0, 1}
const int8_t canonical_cofaces_1 [3] = {1, 0, 2}
const int8_t permutations [6][3]
const int8_t canonical_subdart [2][6] = {{1, 1, 3, 3, 5, 5}, {0, 1, 2, 3, 4, 5}}
const int8_t canonical_supdart [2][6] = {{0, 1, 2, 3, 4, 5}, {0, 1, 2, 1, 2, 0}}
const int8_t canonical_simplex [2][6] = {{1, 1, 3, 3, 5, 5}, {0, 1, 2, 1, 2, 0}}
Function Documentation
get_tuple_from_simplex_local_edge_id()
Tuple wmtk::autogen::tri_mesh::get_tuple_from_simplex_local_edge_id (int8_t local_id, int64_t global_id) inline
Definition at line 20 of file get_tuple_from_simplex_local_id.hpp.
References auto_2d_table_complete_edge.
Referenced by wmtk::TriMesh::edge_tuple_from_id(), and get_tuple_from_simplex_local_id().
get_tuple_from_simplex_local_id()
Tuple wmtk::autogen::tri_mesh::get_tuple_from_simplex_local_id (PrimitiveType pt, int8_t local_id, int64_t global_fid) inline
Definition at line 29 of file get_tuple_from_simplex_local_id.hpp.
References wmtk::Edge, get_tuple_from_simplex_local_edge_id(), get_tuple_from_simplex_local_vertex_id(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
get_tuple_from_simplex_local_vertex_id()
Tuple wmtk::autogen::tri_mesh::get_tuple_from_simplex_local_vertex_id (int8_t local_id, int64_t global_id) inline
Definition at line 10 of file get_tuple_from_simplex_local_id.hpp.
References auto_2d_table_complete_vertex.
Referenced by get_tuple_from_simplex_local_id(), and wmtk::TriMesh::vertex_tuple_from_id().
identity()
int8_t wmtk::autogen::tri_mesh::identity () inline
Definition at line 28 of file SimplexDart.hpp.
References auto_valid_tuple_switch_indices, and wmtk::autogen::tri_mesh::constants::simplex_dimension.
Referenced by wmtk::autogen::tri_mesh::SimplexDart::identity(), subdart_maximal_action_to_face(), and subdart_maximal_action_to_face_action().
inverse()
int8_t wmtk::autogen::tri_mesh::inverse (int8_t a) inline
Definition at line 20 of file SimplexDart.hpp.
References auto_valid_switch_inverse_table.
Referenced by wmtk::autogen::tri_mesh::SimplexDart::inverse().
is_ccw()
bool wmtk::autogen::tri_mesh::is_ccw (const Tuple & t) inline
Definition at line 9 of file is_ccw.hxx.
References auto_2d_table_ccw, local_id_table_offset(), and tuple_is_valid_for_ccw().
Referenced by wmtk::TriMesh::is_ccw(), and wmtk::autogen::is_ccw().
local_id_table_offset()
int64_t wmtk::autogen::tri_mesh::local_id_table_offset (const Tuple & t) inline
Definition at line 6 of file local_id_table_offset.hxx.
References wmtk::Tuple::local_eid(), and wmtk::Tuple::local_vid().
Referenced by is_ccw(), wmtk::autogen::utils::local_id_table_offset(), local_switch_tuple(), permutation_index_from_tuple(), and tuple_is_valid_for_ccw().
local_switch_tuple() [1/2]
Tuple wmtk::autogen::tri_mesh::local_switch_tuple (const Tuple & t, int8_t index) inline
Definition at line 35 of file local_switch_tuple.hxx.
References auto_valid_switch_product_table, wmtk::Tuple::global_cid(), permutation_index_from_tuple(), and tuple_from_permutation_index().
local_switch_tuple() [2/2]
Tuple wmtk::autogen::tri_mesh::local_switch_tuple (const Tuple & t, PrimitiveType pt) inline
Definition at line 11 of file local_switch_tuple.hxx.
References auto_2d_table_edge, auto_2d_table_vertex, wmtk::Edge, wmtk::Tuple::global_cid(), wmtk::Tuple::local_fid(), local_id_table_offset(), wmtk::Tetrahedron, wmtk::Triangle, and wmtk::Vertex.
Referenced by wmtk::multimesh::utils::local_switch_tuple(), wmtk::autogen::local_switch_tuple(), wmtk::autogen::local_switch_tuple(), and wmtk::TriMesh::switch_tuple().
lvid_leid_from_table_offset()
std::array< int64_t, 2 > wmtk::autogen::tri_mesh::lvid_leid_from_table_offset (int64_t table_offset) inline
Definition at line 11 of file local_id_table_offset.hxx.
opposite()
int8_t wmtk::autogen::tri_mesh::opposite () inline
Definition at line 32 of file SimplexDart.hpp.
References auto_valid_tuple_switch_indices, and wmtk::autogen::tri_mesh::constants::simplex_dimension.
Referenced by wmtk::autogen::tri_mesh::SimplexDart::opposite().
permutation_index_from_primitive_switch()
int8_t wmtk::autogen::tri_mesh::permutation_index_from_primitive_switch (wmtk::PrimitiveType pt) inline
Definition at line 24 of file SimplexDart.hpp.
References auto_valid_tuple_switch_indices, and wmtk::get_primitive_type_id().
Referenced by wmtk::autogen::tri_mesh::SimplexDart::permutation_index_from_primitive_switch().
permutation_index_from_tuple()
int8_t wmtk::autogen::tri_mesh::permutation_index_from_tuple (const Tuple & t) inline
Definition at line 7 of file permutation_index_from_tuple.hxx.
References auto_all_to_valid_tuple_indices, and local_id_table_offset().
Referenced by local_switch_tuple(), and wmtk::dart::utils::permutation_index_from_tuple().
permutation_indices()
auto wmtk::autogen::tri_mesh::permutation_indices () inline
Definition at line 41 of file SimplexDart.hpp.
References wmtk::utils::array_to_map(), and auto_valid_tuple_indices.
permutation_indices_dynamic()
auto wmtk::autogen::tri_mesh::permutation_indices_dynamic () inline
Definition at line 45 of file SimplexDart.hpp.
References auto_valid_tuple_indices, and size().
Referenced by wmtk::autogen::tri_mesh::SimplexDart::permutation_indices().
product()
int8_t wmtk::autogen::tri_mesh::product (int8_t a, int8_t b) inline
Definition at line 16 of file SimplexDart.hpp.
References auto_valid_switch_product_table.
Referenced by wmtk::autogen::tri_mesh::SimplexDart::product().
simplex_index()
int8_t wmtk::autogen::tri_mesh::simplex_index (int8_t permutation_index, wmtk::PrimitiveType type) inline
Definition at line 50 of file SimplexDart.hpp.
References auto_valid_tuples, and wmtk::get_primitive_type_id().
Referenced by wmtk::autogen::tri_mesh::SimplexDart::simplex_index(), subdart_maximal_action_to_face(), subdart_maximal_action_to_face_action(), and subdart_maximal_action_to_face_size().
simplex_index_from_permutation_index()
int8_t wmtk::autogen::tri_mesh::simplex_index_from_permutation_index (int8_t permutation_index, wmtk::PrimitiveType type) inline
Definition at line 7 of file simplex_index_from_permutation_index.hxx.
References auto_valid_tuples, and wmtk::get_primitive_type_id().
Referenced by wmtk::TriMesh::id(), wmtk::dart::utils::permutation_index_to_simplex_index(), and wmtk::dart::utils::simplex_index_from_permutation_index().
size()
constexpr size_t wmtk::autogen::tri_mesh::size () constexpr
Definition at line 36 of file SimplexDart.hpp.
References auto_valid_tuple_indices.
Referenced by permutation_indices_dynamic(), and wmtk::autogen::tri_mesh::SimplexDart::size().
subdart_maximal_action_to_face()
std::array< int8_t, 2 > wmtk::autogen::tri_mesh::subdart_maximal_action_to_face (int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index)
Returns a dart action that maximizes the number of sub-darts preserved.
Definition at line 39 of file subdart_maximal_action_to_face.cpp.
References identity(), max_subdart_preservation_dimension_1, simplex_index(), and subdart_preserving_action_1.
Referenced by wmtk::dart::utils::subdart_maximal_action_to_face().
subdart_maximal_action_to_face_action()
int8_t wmtk::autogen::tri_mesh::subdart_maximal_action_to_face_action (int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index)
Definition at line 7 of file subdart_maximal_action_to_face.cpp.
References identity(), simplex_index(), and subdart_preserving_action_1.
Referenced by wmtk::dart::utils::subdart_maximal_action_to_face_action().
subdart_maximal_action_to_face_size()
int8_t wmtk::autogen::tri_mesh::subdart_maximal_action_to_face_size (int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index)
Definition at line 23 of file subdart_maximal_action_to_face.cpp.
References max_subdart_preservation_dimension_1, permutations, and simplex_index().
Referenced by wmtk::dart::utils::largest_shared_subdart_size(), and wmtk::dart::utils::subdart_maximal_action_to_face_size().
tuple_from_permutation_index()
Tuple wmtk::autogen::tri_mesh::tuple_from_permutation_index (int64_t global_cid, int8_t valid_tuple_index) inline
Definition at line 7 of file tuple_from_permutation_index.hxx.
References auto_valid_tuples.
Referenced by local_switch_tuple(), and wmtk::dart::utils::tuple_from_permutation_index().
tuple_is_valid_for_ccw()
bool wmtk::autogen::tri_mesh::tuple_is_valid_for_ccw (const Tuple & t) inline
Definition at line 15 of file is_ccw.hxx.
References auto_2d_table_ccw, wmtk::Tuple::is_null(), and local_id_table_offset().
Referenced by is_ccw(), wmtk::TriMesh::is_valid(), and wmtk::autogen::tuple_is_valid_for_ccw().
Variable Documentation
auto_2d_edges
const int64_t wmtk::autogen::tri_mesh::auto_2d_edges = {{1, 2}, {0, 2}, {0, 1}}
Definition at line 6 of file autogenerated_tables.cpp.
Referenced by wmtk::trimesh_topology_initialization().
auto_2d_table_ccw
const int64_t wmtk::autogen::tri_mesh::auto_2d_table_ccw = {-1, 0, 1, 1, -1, 0, 0, 1, -1}
Definition at line 14 of file autogenerated_tables.cpp.
Referenced by is_ccw(), and tuple_is_valid_for_ccw().
auto_2d_table_complete_edge
const int64_t wmtk::autogen::tri_mesh::auto_2d_table_complete_edge = {{1, 0}, {2, 1}, {0, 2}}
Definition at line 18 of file autogenerated_tables.cpp.
Referenced by get_tuple_from_simplex_local_edge_id().
auto_2d_table_complete_vertex
const int64_t wmtk::autogen::tri_mesh::auto_2d_table_complete_vertex = {{0, 2}, {1, 0}, {2, 1}}
Definition at line 16 of file autogenerated_tables.cpp.
Referenced by wmtk::TriMesh::face_tuple_from_id(), and get_tuple_from_simplex_local_vertex_id().
auto_2d_table_edge
const int64_t wmtk::autogen::tri_mesh::auto_2d_table_edge
Initial value:
=
    {{-1, -1}, {0, 2}, {0, 1}, {1, 2}, {-1, -1}, {1, 0}, {2, 1}, {2, 0}, {-1, -1}}
Definition at line 11 of file autogenerated_tables.cpp.
Referenced by local_switch_tuple().
auto_2d_table_vertex
const int64_t wmtk::autogen::tri_mesh::auto_2d_table_vertex
Initial value:
=
    {{-1, -1}, {2, 1}, {1, 2}, {2, 0}, {-1, -1}, {0, 2}, {1, 0}, {0, 1}, {-1, -1}}
Definition at line 8 of file autogenerated_tables.cpp.
Referenced by local_switch_tuple().
auto_all_to_valid_tuple_indices
const int8_t wmtk::autogen::tri_mesh::auto_all_to_valid_tuple_indices = {-1, 0, 1, 2, -1, 3, 4, 5, -1}
Definition at line 24 of file autogenerated_tables.cpp.
Referenced by permutation_index_from_tuple().
auto_valid_switch_edge_mirror_indices
const int8_t wmtk::autogen::tri_mesh::auto_valid_switch_edge_mirror_indices = {2, 3, 0, 1, 5, 4}
Definition at line 40 of file autogenerated_tables.cpp.
auto_valid_switch_inverse_table
const int8_t wmtk::autogen::tri_mesh::auto_valid_switch_inverse_table = {0, 1, 5, 3, 4, 2}
Definition at line 36 of file autogenerated_tables.cpp.
Referenced by inverse().
auto_valid_switch_product_table
const int8_t wmtk::autogen::tri_mesh::auto_valid_switch_product_table
Initial value:
= {
    {1, 0, 4, 5, 2, 3},
    {0, 1, 2, 3, 4, 5},
    {3, 2, 5, 4, 0, 1},
    {2, 3, 0, 1, 5, 4},
    {5, 4, 3, 2, 1, 0},
    {4, 5, 1, 0, 3, 2}}
Definition at line 28 of file autogenerated_tables.cpp.
Referenced by local_switch_tuple(), and product().
auto_valid_switch_table
const int8_t wmtk::autogen::tri_mesh::auto_valid_switch_table = {{5, 1}, {3, 0}, {4, 3}, {1, 2}, {2, 5}, {0, 4}}
Definition at line 26 of file autogenerated_tables.cpp.
auto_valid_tuple_indices
const int8_t wmtk::autogen::tri_mesh::auto_valid_tuple_indices = {1, 2, 3, 5, 6, 7}
Definition at line 22 of file autogenerated_tables.cpp.
Referenced by permutation_indices(), permutation_indices_dynamic(), and size().
auto_valid_tuple_switch_indices
const int8_t wmtk::autogen::tri_mesh::auto_valid_tuple_switch_indices = {3, 0, 1, 4}
Definition at line 38 of file autogenerated_tables.cpp.
Referenced by identity(), opposite(), permutation_index_from_primitive_switch(), and wmtk::autogen::tri_mesh::internal::switch_primitive_to_valid_tuple_index().
auto_valid_tuples
const int8_t wmtk::autogen::tri_mesh::auto_valid_tuples = {{0, 1}, {0, 2}, {1, 0}, {1, 2}, {2, 0}, {2, 1}}
Definition at line 20 of file autogenerated_tables.cpp.
Referenced by simplex_index(), simplex_index_from_permutation_index(), and tuple_from_permutation_index().
canonical_cofaces_0
const int8_t wmtk::autogen::tri_mesh::canonical_cofaces_0 = {5, 3, 1}
Definition at line 50 of file autogenerated_tables.cpp.
canonical_cofaces_1
const int8_t wmtk::autogen::tri_mesh::canonical_cofaces_1 = {1, 0, 2}
Definition at line 54 of file autogenerated_tables.cpp.
canonical_faces_0
const int8_t wmtk::autogen::tri_mesh::canonical_faces_0 = {1, 3, 5}
Definition at line 48 of file autogenerated_tables.cpp.
Referenced by wmtk::dart::utils::get_canonical_faces().
canonical_faces_1
const int8_t wmtk::autogen::tri_mesh::canonical_faces_1 = {2, 0, 1}
Definition at line 52 of file autogenerated_tables.cpp.
Referenced by wmtk::dart::utils::get_canonical_faces().
canonical_simplex
const int8_t wmtk::autogen::tri_mesh::canonical_simplex = {{1, 1, 3, 3, 5, 5}, {0, 1, 2, 1, 2, 0}}
Definition at line 63 of file autogenerated_tables.cpp.
Referenced by wmtk::dart::utils::get_canonical_simplex().
canonical_subdart
const int8_t wmtk::autogen::tri_mesh::canonical_subdart = {{1, 1, 3, 3, 5, 5}, {0, 1, 2, 3, 4, 5}}
Definition at line 59 of file autogenerated_tables.cpp.
Referenced by wmtk::dart::utils::get_canonical_subdart().
canonical_supdart
const int8_t wmtk::autogen::tri_mesh::canonical_supdart = {{0, 1, 2, 3, 4, 5}, {0, 1, 2, 1, 2, 0}}
Definition at line 61 of file autogenerated_tables.cpp.
Referenced by wmtk::dart::utils::get_canonical_supdart().
max_subdart_preservation_dimension_1
const int8_t wmtk::autogen::tri_mesh::max_subdart_preservation_dimension_1
Initial value:
=
    {{0, 2, 1}, {0, 1, 2}, {2, 0, 1}, {1, 0, 2}, {2, 1, 0}, {1, 2, 0}}
Definition at line 45 of file autogenerated_tables.cpp.
Referenced by subdart_maximal_action_to_face(), and subdart_maximal_action_to_face_size().
permutations
const int8_t wmtk::autogen::tri_mesh::permutations
Initial value:
=
    {{0, 2, 1}, {0, 1, 2}, {1, 2, 0}, {1, 0, 2}, {2, 1, 0}, {2, 0, 1}}
Definition at line 56 of file autogenerated_tables.cpp.
Referenced by wmtk::dart::utils::get_local_vertex_permutation(), and subdart_maximal_action_to_face_size().
subdart_preserving_action_1
const int8_t wmtk::autogen::tri_mesh::subdart_preserving_action_1
Initial value:
=
    {{4, 1, 0}, {4, 0, 1}, {1, 4, 0}, {0, 4, 1}, {1, 0, 4}, {0, 1, 4}}
Definition at line 42 of file autogenerated_tables.cpp.
Referenced by subdart_maximal_action_to_face(), and subdart_maximal_action_to_face_action().