Wildmeshing Toolkit: wmtk::components::configurator::transfer Namespace Reference
wmtk::components::configurator::transfer Namespace Reference
Classes
struct AMIPSFunctor
struct CoeffWiseTransfer
struct EdgeAngleFunctor
struct EdgeLengthFunctor
struct FilteredNeighborCountFunctor
struct MaxNeighborFunctor
struct MeanNeighborFunctor
struct MeanRatioMeasureFunctor
struct MinNeighborFunctor
struct NegateFunctor
struct NeighborCountFunctor
struct NeighborSumFunctor
struct NormalFunctor
struct SingleAttributeTransferStrategyFactory
struct SingleAttributeTransferStrategyFactoryBase
struct ThresholdFunctor
struct TransferFunctorTraits
struct TransferStrategyFactory
class TransferStrategyFactoryCollection
class TransferStrategyFactoryRegistry
struct VolumeFunctor
Typedefs
using AMIPS = SingleAttributeTransferStrategyFactory< AMIPSFunctor >
using EdgeAngle = SingleAttributeTransferStrategyFactory< EdgeAngleFunctor >
using EdgeLength = SingleAttributeTransferStrategyFactory< EdgeLengthFunctor >
using FilteredNeighborCount = SingleAttributeTransferStrategyFactory< FilteredNeighborCountFunctor >
using MaxNeighbor = SingleAttributeTransferStrategyFactory< MaxNeighborFunctor >
using MeanNeighbor = SingleAttributeTransferStrategyFactory< MeanNeighborFunctor >
using MeanRatioMeasure = SingleAttributeTransferStrategyFactory< MeanRatioMeasureFunctor >
using MinNeighbor = SingleAttributeTransferStrategyFactory< MinNeighborFunctor >
using Negate = SingleAttributeTransferStrategyFactory< NegateFunctor >
using NeighborCount = SingleAttributeTransferStrategyFactory< NeighborCountFunctor >
using NeighborSum = SingleAttributeTransferStrategyFactory< NeighborSumFunctor >
using Normal = SingleAttributeTransferStrategyFactory< NormalFunctor >
using Threshold = SingleAttributeTransferStrategyFactory< ThresholdFunctor >
using Volume = SingleAttributeTransferStrategyFactory< VolumeFunctor >
Functions
TransferStrategyFactoryRegistry create_registry ()
void init ()
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (TransferStrategyFactory)
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (TransferStrategyFactory)
void to_json (nlohmann::json &, const TransferStrategyFactory &)
void from_json (const nlohmann::json &, TransferStrategyFactory &)
void to_json (nlohmann::json &j, const TransferStrategyFactoryCollection &value)
void from_json (const nlohmann::json &j, TransferStrategyFactoryCollection &value)
Typedef Documentation
AMIPS
using wmtk::components::configurator::transfer::AMIPS = typedef SingleAttributeTransferStrategyFactory<AMIPSFunctor>
Definition at line 68 of file amips.hpp.
EdgeAngle
using wmtk::components::configurator::transfer::EdgeAngle = typedef SingleAttributeTransferStrategyFactory<EdgeAngleFunctor>
Definition at line 80 of file edge_angle.hpp.
EdgeLength
using wmtk::components::configurator::transfer::EdgeLength = typedef SingleAttributeTransferStrategyFactory<EdgeLengthFunctor>
Definition at line 43 of file edge_length.hpp.
FilteredNeighborCount
using wmtk::components::configurator::transfer::FilteredNeighborCount = typedef SingleAttributeTransferStrategyFactory<FilteredNeighborCountFunctor>
Definition at line 60 of file filtered_neighbor_count.hpp.
MaxNeighbor
using wmtk::components::configurator::transfer::MaxNeighbor = typedef SingleAttributeTransferStrategyFactory<MaxNeighborFunctor>
Definition at line 31 of file max_neighbor.hpp.
MeanNeighbor
using wmtk::components::configurator::transfer::MeanNeighbor = typedef SingleAttributeTransferStrategyFactory<MeanNeighborFunctor>
Definition at line 32 of file mean_neighbor.hpp.
MeanRatioMeasure
using wmtk::components::configurator::transfer::MeanRatioMeasure = typedef SingleAttributeTransferStrategyFactory<MeanRatioMeasureFunctor>
Definition at line 80 of file mean_ratio_measure.hpp.
MinNeighbor
using wmtk::components::configurator::transfer::MinNeighbor = typedef SingleAttributeTransferStrategyFactory<MinNeighborFunctor>
Definition at line 33 of file min_neighbor.hpp.
Negate
using wmtk::components::configurator::transfer::Negate = typedef SingleAttributeTransferStrategyFactory<NegateFunctor>
Definition at line 55 of file negate.hpp.
NeighborCount
using wmtk::components::configurator::transfer::NeighborCount = typedef SingleAttributeTransferStrategyFactory<NeighborCountFunctor>
Definition at line 57 of file neighbor_count.hpp.
NeighborSum
using wmtk::components::configurator::transfer::NeighborSum = typedef SingleAttributeTransferStrategyFactory<NeighborSumFunctor>
Definition at line 31 of file neighbor_sum.hpp.
Normal
using wmtk::components::configurator::transfer::Normal = typedef SingleAttributeTransferStrategyFactory<NormalFunctor>
Definition at line 67 of file normal.hpp.
Threshold
using wmtk::components::configurator::transfer::Threshold = typedef SingleAttributeTransferStrategyFactory<ThresholdFunctor>
Definition at line 76 of file threshold.hpp.
Volume
using wmtk::components::configurator::transfer::Volume = typedef SingleAttributeTransferStrategyFactory<VolumeFunctor>
Definition at line 62 of file volume.hpp.
Function Documentation
create_registry()
TransferStrategyFactoryRegistry wmtk::components::configurator::transfer::create_registry ()
Definition at line 15 of file init.cpp.
References wmtk::components::configurator::transfer::TransferStrategyFactoryRegistry::register_transfer().
from_json() [1/2]
void wmtk::components::configurator::transfer::from_json (const nlohmann::json & , TransferStrategyFactory &)
from_json() [2/2]
void wmtk::components::configurator::transfer::from_json (const nlohmann::json & j, TransferStrategyFactoryCollection & value)
Definition at line 17 of file TransferStrategyFactoryCollection.cpp.
References wmtk::components::configurator::transfer::TransferStrategyFactory::transfer_registry().
init()
void wmtk::components::configurator::transfer::init ()
Definition at line 34 of file init.cpp.
Referenced by wmtk::components::isotropic_remeshing::IsotropicRemeshingOptions::IsotropicRemeshingOptions().
to_json() [1/2]
void wmtk::components::configurator::transfer::to_json (nlohmann::json & , const TransferStrategyFactory &)
to_json() [2/2]
void wmtk::components::configurator::transfer::to_json (nlohmann::json & j, const TransferStrategyFactoryCollection & value)
Definition at line 5 of file TransferStrategyFactoryCollection.cpp.
WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE()
wmtk::components::configurator::transfer::WMTK_NLOHMANN_JSON_FRIEND_FROM_JSON_PROTOTYPE (TransferStrategyFactory)
Definition at line 60 of file TransferStrategyFactory.cpp.
References WMTK_NLOHMANN_ASSIGN_TYPE_FROM_JSON.
WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE()
wmtk::components::configurator::transfer::WMTK_NLOHMANN_JSON_FRIEND_TO_JSON_PROTOTYPE (TransferStrategyFactory)
Definition at line 54 of file TransferStrategyFactory.cpp.
References WMTK_NLOHMANN_ASSIGN_TYPE_TO_JSON.