Wildmeshing Toolkit: wmtk::components::multimesh::MultimeshBijectionOptions Struct Reference
wmtk::components::multimesh::MultimeshBijectionOptions Struct Reference
#include <from_facet_bijection.hpp>
Public Member Functions
void run (MeshCollection &mc) const final
void to_json (nlohmann::json &j) const final
void from_json (const nlohmann::json &) final
Public Member Functions inherited from wmtk::components::multimesh::MultimeshRunnableOptions
MultimeshRunnableOptions ()
bool operator<=> (const MultimeshRunnableOptions &) const =default
virtual ~MultimeshRunnableOptions ()
Public Attributes
std::string parent_path
std::string child_path
Detailed Description
Definition at line 14 of file from_facet_bijection.hpp.
Member Function Documentation
from_json()
void wmtk::components::multimesh::MultimeshBijectionOptions::from_json (const nlohmann::json & j) final virtual
Implements wmtk::components::multimesh::MultimeshRunnableOptions.
Definition at line 21 of file from_facet_bijection.cpp.
run()
void wmtk::components::multimesh::MultimeshBijectionOptions::run (MeshCollection & mc) const final virtual
Implements wmtk::components::multimesh::MultimeshRunnableOptions.
Definition at line 32 of file from_facet_bijection.cpp.
References child_path, wmtk::components::multimesh::from_facet_bijection(), wmtk::components::multimesh::MeshCollection::get_mesh(), wmtk::components::multimesh::MeshCollection::get_named_multimesh(), and parent_path.
to_json()
void wmtk::components::multimesh::MultimeshBijectionOptions::to_json (nlohmann::json & j) const final virtual
Implements wmtk::components::multimesh::MultimeshRunnableOptions.
Definition at line 17 of file from_facet_bijection.cpp.
Member Data Documentation
child_path
std::string wmtk::components::multimesh::MultimeshBijectionOptions::child_path
Definition at line 17 of file from_facet_bijection.hpp.
Referenced by run().
parent_path
std::string wmtk::components::multimesh::MultimeshBijectionOptions::parent_path
Definition at line 16 of file from_facet_bijection.hpp.
Referenced by run().
The documentation for this struct was generated from the following files:
components/multimesh/src/wmtk/components/multimesh/from_facet_bijection.hpp
components/multimesh/src/wmtk/components/multimesh/from_facet_bijection.cpp