Wildmeshing Toolkit: wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim > Struct Template Reference
wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim > Struct Template Reference
#include <neighbor_count.hpp>
Public Member Functions
NeighborCountFunctor (const nlohmann::json &js)
auto operator() (Eigen::Ref< const ColVectors< InT, InDim > > M) const -> Vector< OutT, OutDim >
Static Public Member Functions
static constexpr bool validInDim ()
static constexpr bool validOutDim ()
static constexpr bool validType ()
static constexpr bool valid ()
Private Attributes
const std::optional< InT > m_over
const std::optional< InT > m_under
Detailed Description
template<typename InT, int InDim, typename OutT, int OutDim>
struct wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim >
Definition at line 11 of file neighbor_count.hpp.
Constructor & Destructor Documentation
NeighborCountFunctor()
template<typename InT , int InDim, typename OutT , int OutDim> wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim >::NeighborCountFunctor (const nlohmann::json & js) inline
Definition at line 14 of file neighbor_count.hpp.
Member Function Documentation
operator()()
template<typename InT , int InDim, typename OutT , int OutDim> auto wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim >::operator() (Eigen::Ref< const ColVectors< InT, InDim > > M) const -> Vector<OutT, OutDim> inline
Definition at line 25 of file neighbor_count.hpp.
valid()
template<typename InT , int InDim, typename OutT , int OutDim> static constexpr bool wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim >::valid () inline static constexpr
Definition at line 23 of file neighbor_count.hpp.
References wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim >::validInDim(), wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim >::validOutDim(), and wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim >::validType().
validInDim()
template<typename InT , int InDim, typename OutT , int OutDim> static constexpr bool wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim >::validInDim () inline static constexpr
Definition at line 17 of file neighbor_count.hpp.
Referenced by wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim >::valid().
validOutDim()
template<typename InT , int InDim, typename OutT , int OutDim> static constexpr bool wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim >::validOutDim () inline static constexpr
Definition at line 18 of file neighbor_count.hpp.
Referenced by wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim >::valid().
validType()
template<typename InT , int InDim, typename OutT , int OutDim> static constexpr bool wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim >::validType () inline static constexpr
Definition at line 19 of file neighbor_count.hpp.
Referenced by wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim >::valid().
Member Data Documentation
m_over
template<typename InT , int InDim, typename OutT , int OutDim> const std::optional<InT> wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim >::m_over private
Definition at line 31 of file neighbor_count.hpp.
m_under
template<typename InT , int InDim, typename OutT , int OutDim> const std::optional<InT> wmtk::components::mesh_info::transfer::NeighborCountFunctor< InT, InDim, OutT, OutDim >::m_under private
Definition at line 32 of file neighbor_count.hpp.
The documentation for this struct was generated from the following file:
components/mesh_info/src/wmtk/components/mesh_info/transfer/neighbor_count.hpp