Wildmeshing Toolkit: wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim > Struct Template Reference
wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim > Struct Template Reference
#include <edge_length.hpp>
Public Member Functions
EdgeLengthFunctor (const nlohmann::json &js)
auto operator() (Eigen::Ref< const ColVectors< InT, InDim > > M) const -> Vector< OutT, OutDim >
Static Public Member Functions
static constexpr bool validInDim ()
static constexpr bool validOutDim ()
static constexpr bool validType ()
static constexpr bool valid ()
static auto execute (Eigen::Ref< const Eigen::Matrix< InT, InDim, 2 > > M) -> Vector< OutT, OutDim >
Detailed Description
template<typename InT, int InDim, typename OutT, int OutDim>
struct wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim >
Definition at line 10 of file edge_length.hpp.
Constructor & Destructor Documentation
EdgeLengthFunctor()
template<typename InT , int InDim, typename OutT , int OutDim> wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim >::EdgeLengthFunctor (const nlohmann::json & js) inline
Definition at line 12 of file edge_length.hpp.
Member Function Documentation
execute()
template<typename InT , int InDim, typename OutT , int OutDim> static auto wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim >::execute (Eigen::Ref< const Eigen::Matrix< InT, InDim, 2 > > M) -> Vector<OutT, OutDim> inline static
Definition at line 20 of file edge_length.hpp.
Referenced by wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim >::operator()().
operator()()
template<typename InT , int InDim, typename OutT , int OutDim> auto wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim >::operator() (Eigen::Ref< const ColVectors< InT, InDim > > M) const -> Vector<OutT, OutDim> inline
Definition at line 24 of file edge_length.hpp.
References wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim >::execute().
valid()
template<typename InT , int InDim, typename OutT , int OutDim> static constexpr bool wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim >::valid () inline static constexpr
Definition at line 19 of file edge_length.hpp.
References wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim >::validInDim(), wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim >::validOutDim(), and wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim >::validType().
validInDim()
template<typename InT , int InDim, typename OutT , int OutDim> static constexpr bool wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim >::validInDim () inline static constexpr
Definition at line 13 of file edge_length.hpp.
Referenced by wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim >::valid().
validOutDim()
template<typename InT , int InDim, typename OutT , int OutDim> static constexpr bool wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim >::validOutDim () inline static constexpr
Definition at line 14 of file edge_length.hpp.
Referenced by wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim >::valid().
validType()
template<typename InT , int InDim, typename OutT , int OutDim> static constexpr bool wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim >::validType () inline static constexpr
Definition at line 15 of file edge_length.hpp.
Referenced by wmtk::components::configurator::transfer::EdgeLengthFunctor< InT, InDim, OutT, OutDim >::valid().
The documentation for this struct was generated from the following file:
components/configurator/src/wmtk/components/configurator/transfer/edge_length.hpp