Wildmeshing Toolkit: wmtk::components::configurator::transfer::TransferFunctorTraits< Functor > Struct Template Reference
wmtk::components::configurator::transfer::TransferFunctorTraits< Functor > Struct Template Reference
#include <TransferFunctorTraits.hpp>
Public Member Functions
int output_dimension (const attribute::MeshAttributeHandle &mah)
int simplex_dimension (const attribute::MeshAttributeHandle &mah, const nlohmann::json &js)
int output_dimension (const attribute::MeshAttributeHandle &mah)
int simplex_dimension (const attribute::MeshAttributeHandle &mah, const nlohmann::json &js)
int output_dimension (const attribute::MeshAttributeHandle &mah)
int simplex_dimension (const attribute::MeshAttributeHandle &mah, const nlohmann::json &js)
int output_dimension (const attribute::MeshAttributeHandle &mah)
auto output_type (const attribute::MeshAttributeHandle &mah, const nlohmann::json &js) -> attribute::AttributeType
int simplex_dimension (const attribute::MeshAttributeHandle &mah, const nlohmann::json &js)
int output_dimension (const attribute::MeshAttributeHandle &mah)
int simplex_dimension (const attribute::MeshAttributeHandle &mah, const nlohmann::json &js)
int output_dimension (const attribute::MeshAttributeHandle &mah)
auto output_type (const attribute::MeshAttributeHandle &mah, const nlohmann::json &js) -> attribute::AttributeType
int simplex_dimension (const attribute::MeshAttributeHandle &mah, const nlohmann::json &js)
int output_dimension (const attribute::MeshAttributeHandle &mah)
auto output_type (const attribute::MeshAttributeHandle &mah, const nlohmann::json &js) -> attribute::AttributeType
int simplex_dimension (const attribute::MeshAttributeHandle &mah, const nlohmann::json &js)
int simplex_dimension (const attribute::MeshAttributeHandle &mah, const nlohmann::json &js)
int output_dimension (const attribute::MeshAttributeHandle &mah)
auto output_type (const attribute::MeshAttributeHandle &mah, const nlohmann::json &js) -> attribute::AttributeType
int simplex_dimension (const attribute::MeshAttributeHandle &mah, const nlohmann::json &js)
int output_dimension (const attribute::MeshAttributeHandle &mah)
int simplex_dimension (const attribute::MeshAttributeHandle &mah, const nlohmann::json &js)
Static Public Member Functions
static int output_dimension (const attribute::MeshAttributeHandle &mah)
static attribute::AttributeType output_type (const attribute::MeshAttributeHandle &mah, const nlohmann::json &js={})
static int simplex_dimension (const attribute::MeshAttributeHandle &mah, const nlohmann::json &js={})
Detailed Description
template<template< typename, int, typename, int > typename Functor>
struct wmtk::components::configurator::transfer::TransferFunctorTraits< Functor >
Definition at line 8 of file TransferFunctorTraits.hpp.
Member Function Documentation
output_dimension() [1/10]
int wmtk::components::configurator::transfer::TransferFunctorTraits< AMIPSFunctor >::output_dimension (const attribute::MeshAttributeHandle & mah) inline
Definition at line 56 of file amips.hpp.
output_dimension() [2/10]
int wmtk::components::configurator::transfer::TransferFunctorTraits< EdgeAngleFunctor >::output_dimension (const attribute::MeshAttributeHandle & mah) inline
Definition at line 67 of file edge_angle.hpp.
output_dimension() [3/10]
int wmtk::components::configurator::transfer::TransferFunctorTraits< EdgeLengthFunctor >::output_dimension (const attribute::MeshAttributeHandle & mah) inline
Definition at line 31 of file edge_length.hpp.
output_dimension() [4/10]
int wmtk::components::configurator::transfer::TransferFunctorTraits< FilteredNeighborCountFunctor >::output_dimension (const attribute::MeshAttributeHandle & mah) inline
Definition at line 38 of file filtered_neighbor_count.hpp.
References wmtk::attribute::MeshAttributeHandle::dimension().
output_dimension() [5/10]
int wmtk::components::configurator::transfer::TransferFunctorTraits< MeanRatioMeasureFunctor >::output_dimension (const attribute::MeshAttributeHandle & mah) inline
Definition at line 67 of file mean_ratio_measure.hpp.
output_dimension() [6/10]
int wmtk::components::configurator::transfer::TransferFunctorTraits< NegateFunctor >::output_dimension (const attribute::MeshAttributeHandle & mah) inline
Definition at line 34 of file negate.hpp.
References wmtk::attribute::MeshAttributeHandle::dimension().
output_dimension() [7/10]
int wmtk::components::configurator::transfer::TransferFunctorTraits< NeighborCountFunctor >::output_dimension (const attribute::MeshAttributeHandle & mah) inline
Definition at line 35 of file neighbor_count.hpp.
output_dimension() [8/10]
int wmtk::components::configurator::transfer::TransferFunctorTraits< ThresholdFunctor >::output_dimension (const attribute::MeshAttributeHandle & mah) inline
Definition at line 55 of file threshold.hpp.
References wmtk::attribute::MeshAttributeHandle::dimension().
output_dimension() [9/10]
template<template< typename, int, typename, int > typename Functor> int wmtk::components::configurator::transfer::TransferFunctorTraits< Functor >::output_dimension (const attribute::MeshAttributeHandle & mah) static
Definition at line 20 of file TransferFunctorTraits.hpp.
References wmtk::attribute::MeshAttributeHandle::dimension().
output_dimension() [10/10]
int wmtk::components::configurator::transfer::TransferFunctorTraits< VolumeFunctor >::output_dimension (const attribute::MeshAttributeHandle & mah) inline
Definition at line 44 of file volume.hpp.
output_type() [1/5]
auto wmtk::components::configurator::transfer::TransferFunctorTraits< FilteredNeighborCountFunctor >::output_type (const attribute::MeshAttributeHandle & mah, const nlohmann::json & js) -> attribute::AttributeType inline
Definition at line 44 of file filtered_neighbor_count.hpp.
References wmtk::attribute::Char.
output_type() [2/5]
auto wmtk::components::configurator::transfer::TransferFunctorTraits< NegateFunctor >::output_type (const attribute::MeshAttributeHandle & mah, const nlohmann::json & js) -> attribute::AttributeType inline
Definition at line 40 of file negate.hpp.
References wmtk::attribute::Char.
output_type() [3/5]
auto wmtk::components::configurator::transfer::TransferFunctorTraits< NeighborCountFunctor >::output_type (const attribute::MeshAttributeHandle & mah, const nlohmann::json & js) -> attribute::AttributeType inline
Definition at line 41 of file neighbor_count.hpp.
References wmtk::attribute::Int64.
output_type() [4/5]
auto wmtk::components::configurator::transfer::TransferFunctorTraits< ThresholdFunctor >::output_type (const attribute::MeshAttributeHandle & mah, const nlohmann::json & js) -> attribute::AttributeType inline
Definition at line 61 of file threshold.hpp.
References wmtk::attribute::Char.
output_type() [5/5]
template<template< typename, int, typename, int > typename Functor> attribute::AttributeType wmtk::components::configurator::transfer::TransferFunctorTraits< Functor >::output_type (const attribute::MeshAttributeHandle & mah, const nlohmann::json & js = {}) static
Definition at line 25 of file TransferFunctorTraits.hpp.
References wmtk::attribute::MeshAttributeHandle::held_type().
simplex_dimension() [1/11]
int wmtk::components::configurator::transfer::TransferFunctorTraits< AMIPSFunctor >::simplex_dimension (const attribute::MeshAttributeHandle & mah, const nlohmann::json & js) inline
Definition at line 62 of file amips.hpp.
References wmtk::attribute::MeshAttributeHandle::mesh(), and wmtk::Mesh::top_cell_dimension().
simplex_dimension() [2/11]
int wmtk::components::configurator::transfer::TransferFunctorTraits< EdgeAngleFunctor >::simplex_dimension (const attribute::MeshAttributeHandle & mah, const nlohmann::json & js) inline
Definition at line 73 of file edge_angle.hpp.
References wmtk::attribute::MeshAttributeHandle::mesh(), and wmtk::Mesh::top_cell_dimension().
simplex_dimension() [3/11]
int wmtk::components::configurator::transfer::TransferFunctorTraits< EdgeLengthFunctor >::simplex_dimension (const attribute::MeshAttributeHandle & mah, const nlohmann::json & js) inline
Definition at line 37 of file edge_length.hpp.
simplex_dimension() [4/11]
int wmtk::components::configurator::transfer::TransferFunctorTraits< FilteredNeighborCountFunctor >::simplex_dimension (const attribute::MeshAttributeHandle & mah, const nlohmann::json & js) inline
Definition at line 51 of file filtered_neighbor_count.hpp.
simplex_dimension() [5/11]
int wmtk::components::configurator::transfer::TransferFunctorTraits< MeanRatioMeasureFunctor >::simplex_dimension (const attribute::MeshAttributeHandle & mah, const nlohmann::json & js) inline
Definition at line 73 of file mean_ratio_measure.hpp.
References wmtk::attribute::MeshAttributeHandle::mesh(), and wmtk::Mesh::top_cell_dimension().
simplex_dimension() [6/11]
int wmtk::components::configurator::transfer::TransferFunctorTraits< NegateFunctor >::simplex_dimension (const attribute::MeshAttributeHandle & mah, const nlohmann::json & js) inline
Definition at line 47 of file negate.hpp.
References wmtk::get_primitive_type_id(), and wmtk::attribute::MeshAttributeHandle::primitive_type().
simplex_dimension() [7/11]
int wmtk::components::configurator::transfer::TransferFunctorTraits< NeighborCountFunctor >::simplex_dimension (const attribute::MeshAttributeHandle & mah, const nlohmann::json & js) inline
Definition at line 48 of file neighbor_count.hpp.
simplex_dimension() [8/11]
int wmtk::components::configurator::transfer::TransferFunctorTraits< NormalFunctor >::simplex_dimension (const attribute::MeshAttributeHandle & mah, const nlohmann::json & js) inline
Definition at line 60 of file normal.hpp.
References wmtk::attribute::MeshAttributeHandle::mesh(), and wmtk::Mesh::top_cell_dimension().
simplex_dimension() [9/11]
int wmtk::components::configurator::transfer::TransferFunctorTraits< ThresholdFunctor >::simplex_dimension (const attribute::MeshAttributeHandle & mah, const nlohmann::json & js) inline
Definition at line 68 of file threshold.hpp.
References wmtk::get_primitive_type_id(), and wmtk::attribute::MeshAttributeHandle::primitive_type().
simplex_dimension() [10/11]
int wmtk::components::configurator::transfer::TransferFunctorTraits< VolumeFunctor >::simplex_dimension (const attribute::MeshAttributeHandle & mah, const nlohmann::json & js) inline
Definition at line 50 of file volume.hpp.
References wmtk::get_primitive_type_id(), wmtk::attribute::MeshAttributeHandle::mesh(), and wmtk::Mesh::top_simplex_type().
simplex_dimension() [11/11]
template<template< typename, int, typename, int > typename Functor> int wmtk::components::configurator::transfer::TransferFunctorTraits< Functor >::simplex_dimension (const attribute::MeshAttributeHandle & mah, const nlohmann::json & js = {}) static
Definition at line 33 of file TransferFunctorTraits.hpp.
References wmtk::get_primitive_type_id(), and wmtk::attribute::MeshAttributeHandle::primitive_type().
The documentation for this struct was generated from the following file:
components/configurator/src/wmtk/components/configurator/transfer/TransferFunctorTraits.hpp