Wildmeshing Toolkit: wmtk::components::multimesh::MultimeshBoundaryOptions Struct Reference
wmtk::components::multimesh::MultimeshBoundaryOptions Struct Reference
#include <from_boundary.hpp>
Public Member Functions
void run (MeshCollection &) const final
void to_json (nlohmann::json &j) const final
void from_json (const nlohmann::json &) final
Public Member Functions inherited from wmtk::components::multimesh::MultimeshRunnableOptions
MultimeshRunnableOptions ()
bool operator<=> (const MultimeshRunnableOptions &) const =default
virtual ~MultimeshRunnableOptions ()
Public Attributes
std::string mesh_path
int8_t dimension
std::string output_mesh_name
std::string attribute_name
char attribute_value = 1
Detailed Description
Definition at line 18 of file from_boundary.hpp.
Member Function Documentation
from_json()
void wmtk::components::multimesh::MultimeshBoundaryOptions::from_json (const nlohmann::json & j) final virtual
Implements wmtk::components::multimesh::MultimeshRunnableOptions.
Definition at line 49 of file from_boundary.cpp.
run()
void wmtk::components::multimesh::MultimeshBoundaryOptions::run (MeshCollection & mc) const final virtual
Implements wmtk::components::multimesh::MultimeshRunnableOptions.
Definition at line 65 of file from_boundary.cpp.
References attribute_name, attribute_value, wmtk::components::multimesh::MultimeshTagOptions::delete_tag_attribute, dimension, wmtk::components::multimesh::MeshCollection::get_mesh(), wmtk::components::multimesh::MeshCollection::get_named_multimesh(), wmtk::get_primitive_type_from_id(), mesh_path, output_mesh_name, wmtk::components::multimesh::MultimeshTagOptions::output_mesh_name, wmtk::components::multimesh::MultimeshTagOptions::run(), wmtk::components::multimesh::MultimeshTagOptions::tag_attribute, and wmtk::components::multimesh::MultimeshTagOptions::value.
to_json()
void wmtk::components::multimesh::MultimeshBoundaryOptions::to_json (nlohmann::json & j) const final virtual
Implements wmtk::components::multimesh::MultimeshRunnableOptions.
Definition at line 45 of file from_boundary.cpp.
Member Data Documentation
attribute_name
std::string wmtk::components::multimesh::MultimeshBoundaryOptions::attribute_name
Definition at line 26 of file from_boundary.hpp.
Referenced by run().
attribute_value
char wmtk::components::multimesh::MultimeshBoundaryOptions::attribute_value = 1
Definition at line 27 of file from_boundary.hpp.
Referenced by run().
dimension
int8_t wmtk::components::multimesh::MultimeshBoundaryOptions::dimension
Definition at line 21 of file from_boundary.hpp.
Referenced by run().
mesh_path
std::string wmtk::components::multimesh::MultimeshBoundaryOptions::mesh_path
Definition at line 20 of file from_boundary.hpp.
Referenced by run().
output_mesh_name
std::string wmtk::components::multimesh::MultimeshBoundaryOptions::output_mesh_name
Definition at line 22 of file from_boundary.hpp.
Referenced by run().
The documentation for this struct was generated from the following files:
components/multimesh/src/wmtk/components/multimesh/from_boundary.hpp
components/multimesh/src/wmtk/components/multimesh/from_boundary.cpp