Wildmeshing Toolkit: wmtk::components::multimesh::NonManifoldCascade Struct Reference
wmtk::components::multimesh::NonManifoldCascade Struct Reference
#include <from_manifold_decomposition.hpp>
Public Member Functions
NonManifoldCascade (Eigen::Ref< const MatrixXl > parent_S)
template<size_t D>
NonManifoldCascade (const wmtk::utils::internal::ManifoldDecomposition< D > &parent_md)
template<int D>
void init (Eigen::Ref< const RowVectors< int64_t, D > > parent_S)
template<size_t D>
void init (const wmtk::utils::internal::ManifoldDecomposition< D > &md)
template<size_t D>
void try_make_child (const wmtk::utils::internal::ManifoldDecomposition< D > &md)
bool empty () const
Public Attributes
MatrixXl S
std::vector< std::array< Tuple, 2 > > parent_map
NonManifoldCascade * m_parent = nullptr
std::unique_ptr< NonManifoldCascade > m_child = nullptr
Detailed Description
Definition at line 24 of file from_manifold_decomposition.hpp.
Constructor & Destructor Documentation
NonManifoldCascade() [1/2]
wmtk::components::multimesh::NonManifoldCascade::NonManifoldCascade (Eigen::Ref< const MatrixXl > parent_S)
Definition at line 68 of file from_manifold_decomposition.cpp.
NonManifoldCascade() [2/2]
template<size_t D> wmtk::components::multimesh::NonManifoldCascade::NonManifoldCascade (const wmtk::utils::internal::ManifoldDecomposition< D > & parent_md)
Definition at line 82 of file from_manifold_decomposition.cpp.
Member Function Documentation
empty()
bool wmtk::components::multimesh::NonManifoldCascade::empty () const inline
Definition at line 44 of file from_manifold_decomposition.hpp.
References S.
Referenced by wmtk::components::multimesh::from_manifold_decomposition().
init() [1/2]
template<size_t D> void wmtk::components::multimesh::NonManifoldCascade::init (const wmtk::utils::internal::ManifoldDecomposition< D > & md)
Definition at line 88 of file from_manifold_decomposition.cpp.
References wmtk::utils::internal::boundary_manifold_decomposition(), wmtk::utils::internal::ManifoldDecomposition< Dim >::face_map, wmtk::utils::internal::ManifoldDecomposition< Dim >::face_matrix(), wmtk::utils::internal::ManifoldDecomposition< Dim >::mm_map(), parent_map, S, and try_make_child().
init() [2/2]
template<int D> void wmtk::components::multimesh::NonManifoldCascade::init (Eigen::Ref< const RowVectors< int64_t, D > > parent_S)
Definition at line 103 of file from_manifold_decomposition.cpp.
References S, and try_make_child().
try_make_child()
template<size_t D> void wmtk::components::multimesh::NonManifoldCascade::try_make_child (const wmtk::utils::internal::ManifoldDecomposition< D > & md)
Definition at line 111 of file from_manifold_decomposition.cpp.
References wmtk::utils::internal::ManifoldDecomposition< Dim >::face_map, and m_child.
Referenced by init(), and init().
Member Data Documentation
m_child
std::unique_ptr<NonManifoldCascade> wmtk::components::multimesh::NonManifoldCascade::m_child = nullptr
Definition at line 47 of file from_manifold_decomposition.hpp.
Referenced by try_make_child().
m_parent
NonManifoldCascade* wmtk::components::multimesh::NonManifoldCascade::m_parent = nullptr
Definition at line 46 of file from_manifold_decomposition.hpp.
parent_map
std::vector<std::array<Tuple, 2> > wmtk::components::multimesh::NonManifoldCascade::parent_map
Definition at line 42 of file from_manifold_decomposition.hpp.
Referenced by wmtk::components::multimesh::from_manifold_decomposition(), and init().
S
MatrixXl wmtk::components::multimesh::NonManifoldCascade::S
Definition at line 40 of file from_manifold_decomposition.hpp.
Referenced by empty(), wmtk::components::multimesh::from_manifold_decomposition(), init(), and init().
The documentation for this struct was generated from the following files:
components/multimesh/src/wmtk/components/multimesh/from_manifold_decomposition.hpp
components/multimesh/src/wmtk/components/multimesh/from_manifold_decomposition.cpp