Wildmeshing Toolkit: wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim > Struct Template Reference
wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim > Struct Template Reference
#include <threshold.hpp>
Public Member Functions
ThresholdFunctor (const std::optional< InT > &over, const std::optional< InT > &under)
ThresholdFunctor (const nlohmann::json &js)
auto operator() (Eigen::Ref< const ColVectors< InT, InDim > > M) const -> Vector< OutT, OutDim >
Static Public Member Functions
static constexpr bool validInDim ()
static constexpr bool validOutDim ()
static constexpr bool validType ()
static constexpr bool valid ()
Private Attributes
const std::optional< InT > m_over
const std::optional< InT > m_under
Detailed Description
template<typename InT, int InDim, typename OutT, int OutDim>
struct wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >
Definition at line 11 of file threshold.hpp.
Constructor & Destructor Documentation
ThresholdFunctor() [1/2]
template<typename InT , int InDim, typename OutT , int OutDim> wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::ThresholdFunctor (const std::optional< InT > & over, const std::optional< InT > & under) inline
Definition at line 13 of file threshold.hpp.
References wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::m_over, and wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::m_under.
ThresholdFunctor() [2/2]
template<typename InT , int InDim, typename OutT , int OutDim> wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::ThresholdFunctor (const nlohmann::json & js) inline
Definition at line 19 of file threshold.hpp.
Member Function Documentation
operator()()
template<typename InT , int InDim, typename OutT , int OutDim> auto wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::operator() (Eigen::Ref< const ColVectors< InT, InDim > > M) const -> Vector<OutT, OutDim> inline
Definition at line 32 of file threshold.hpp.
References wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::m_over, and wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::m_under.
valid()
template<typename InT , int InDim, typename OutT , int OutDim> static constexpr bool wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::valid () inline static constexpr
Definition at line 30 of file threshold.hpp.
References wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::validInDim(), wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::validOutDim(), and wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::validType().
validInDim()
template<typename InT , int InDim, typename OutT , int OutDim> static constexpr bool wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::validInDim () inline static constexpr
Definition at line 24 of file threshold.hpp.
Referenced by wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::valid().
validOutDim()
template<typename InT , int InDim, typename OutT , int OutDim> static constexpr bool wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::validOutDim () inline static constexpr
Definition at line 25 of file threshold.hpp.
Referenced by wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::valid().
validType()
template<typename InT , int InDim, typename OutT , int OutDim> static constexpr bool wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::validType () inline static constexpr
Definition at line 26 of file threshold.hpp.
Referenced by wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::valid().
Member Data Documentation
m_over
template<typename InT , int InDim, typename OutT , int OutDim> const std::optional<InT> wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::m_over private
Definition at line 51 of file threshold.hpp.
Referenced by wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::operator()(), and wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::ThresholdFunctor().
m_under
template<typename InT , int InDim, typename OutT , int OutDim> const std::optional<InT> wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::m_under private
Definition at line 52 of file threshold.hpp.
Referenced by wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::operator()(), and wmtk::components::configurator::transfer::ThresholdFunctor< InT, InDim, OutT, OutDim >::ThresholdFunctor().
The documentation for this struct was generated from the following file:
components/configurator/src/wmtk/components/configurator/transfer/threshold.hpp