Wildmeshing Toolkit: wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< Functor > Struct Template Reference
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< Functor > Struct Template Reference
#include <SingleAttributeTransferStrategyFactory.hpp>
Public Types
template<int ToDim, int FromDim, typename ToT , typename FromT >
using FunctorType = Functor< FromT, FromDim, ToT, ToDim >
Public Member Functions
SingleAttributeTransferStrategyFactory ()
~SingleAttributeTransferStrategyFactory ()
components::multimesh::utils::AttributeDescription get_output_attribute_description (const wmtk::components::multimesh::MeshCollection &) const final
template<int ToDim, int FromDim, typename ToT , typename FromT >
std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > create_T (const attribute::MeshAttributeHandle &to, const attribute::MeshAttributeHandle &from) const
std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > create_transfer (wmtk::components::multimesh::MeshCollection &mc) const final
SingleAttributeTransferStrategyFactory ()=default
~SingleAttributeTransferStrategyFactory ()=default
SingleAttributeTransferStrategyFactory ()=default
~SingleAttributeTransferStrategyFactory ()=default
SingleAttributeTransferStrategyFactory ()=default
~SingleAttributeTransferStrategyFactory ()=default
SingleAttributeTransferStrategyFactory ()=default
~SingleAttributeTransferStrategyFactory ()=default
SingleAttributeTransferStrategyFactory ()=default
~SingleAttributeTransferStrategyFactory ()=default
SingleAttributeTransferStrategyFactory ()=default
~SingleAttributeTransferStrategyFactory ()=default
SingleAttributeTransferStrategyFactory ()=default
~SingleAttributeTransferStrategyFactory ()=default
SingleAttributeTransferStrategyFactory ()=default
~SingleAttributeTransferStrategyFactory ()=default
SingleAttributeTransferStrategyFactory ()=default
~SingleAttributeTransferStrategyFactory ()=default
SingleAttributeTransferStrategyFactory ()=default
~SingleAttributeTransferStrategyFactory ()=default
SingleAttributeTransferStrategyFactory ()=default
~SingleAttributeTransferStrategyFactory ()=default
SingleAttributeTransferStrategyFactory ()=default
~SingleAttributeTransferStrategyFactory ()=default
SingleAttributeTransferStrategyFactory ()=default
~SingleAttributeTransferStrategyFactory ()=default
SingleAttributeTransferStrategyFactory ()=default
~SingleAttributeTransferStrategyFactory ()=default
Public Member Functions inherited from wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactoryBase
SingleAttributeTransferStrategyFactoryBase ()
~SingleAttributeTransferStrategyFactoryBase ()
void to_json (nlohmann::json &j) const final
void from_json (const nlohmann::json &j) final
Public Member Functions inherited from wmtk::components::configurator::transfer::TransferStrategyFactory
TransferStrategyFactory ()
virtual ~TransferStrategyFactory ()
TransferStrategyFactory (const TransferStrategyFactory &)
TransferStrategyFactory (TransferStrategyFactory &&)
TransferStrategyFactory & operator= (const TransferStrategyFactory &)
TransferStrategyFactory & operator= (TransferStrategyFactory &&)
virtual std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > create (wmtk::components::multimesh::MeshCollection &mc, bool populate=true) const
wmtk::attribute::MeshAttributeHandle populate_attribute (wmtk::components::multimesh::MeshCollection &) const
wmtk::attribute::MeshAttributeHandle get_output_attribute (wmtk::components::multimesh::MeshCollection &) const
attribute::MeshAttributeHandle get_output_attribute_handle (const wmtk::components::multimesh::MeshCollection &) const
Additional Inherited Members
Static Public Member Functions inherited from wmtk::components::configurator::transfer::TransferStrategyFactory
static const TransferStrategyFactoryRegistry & transfer_registry ()
Public Attributes inherited from wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactoryBase
std::string base_attribute_path
nlohmann::json parameters
Public Attributes inherited from wmtk::components::configurator::transfer::TransferStrategyFactory
std::string attribute_path
std::string type
Static Protected Member Functions inherited from wmtk::components::configurator::transfer::TransferStrategyFactory
template<typename Type >
static void register_transfer (const std::string &name)
Detailed Description
template<template< typename, int, typename, int > typename Functor>
struct wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< Functor >
Definition at line 33 of file SingleAttributeTransferStrategyFactory.hpp.
Member Typedef Documentation
FunctorType
template<template< typename, int, typename, int > typename Functor> template<int ToDim, int FromDim, typename ToT , typename FromT > using wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< Functor >::FunctorType = Functor<FromT, FromDim, ToT, ToDim>
Definition at line 54 of file SingleAttributeTransferStrategyFactory.hpp.
Constructor & Destructor Documentation
SingleAttributeTransferStrategyFactory() [1/15]
template<template< typename, int, typename, int > typename Functor> wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< Functor >::SingleAttributeTransferStrategyFactory ()
~SingleAttributeTransferStrategyFactory() [1/15]
template<template< typename, int, typename, int > typename Functor> wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< Functor >::~SingleAttributeTransferStrategyFactory ()
SingleAttributeTransferStrategyFactory() [2/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< AMIPSFunctor >::SingleAttributeTransferStrategyFactory () default
~SingleAttributeTransferStrategyFactory() [2/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< AMIPSFunctor >::~SingleAttributeTransferStrategyFactory () default
SingleAttributeTransferStrategyFactory() [3/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< EdgeAngleFunctor >::SingleAttributeTransferStrategyFactory () default
~SingleAttributeTransferStrategyFactory() [3/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< EdgeAngleFunctor >::~SingleAttributeTransferStrategyFactory () default
SingleAttributeTransferStrategyFactory() [4/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< EdgeLengthFunctor >::SingleAttributeTransferStrategyFactory () default
~SingleAttributeTransferStrategyFactory() [4/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< EdgeLengthFunctor >::~SingleAttributeTransferStrategyFactory () default
SingleAttributeTransferStrategyFactory() [5/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< FilteredNeighborCountFunctor >::SingleAttributeTransferStrategyFactory () default
~SingleAttributeTransferStrategyFactory() [5/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< FilteredNeighborCountFunctor >::~SingleAttributeTransferStrategyFactory () default
SingleAttributeTransferStrategyFactory() [6/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< MaxNeighborFunctor >::SingleAttributeTransferStrategyFactory () default
~SingleAttributeTransferStrategyFactory() [6/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< MaxNeighborFunctor >::~SingleAttributeTransferStrategyFactory () default
SingleAttributeTransferStrategyFactory() [7/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< MeanNeighborFunctor >::SingleAttributeTransferStrategyFactory () default
~SingleAttributeTransferStrategyFactory() [7/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< MeanNeighborFunctor >::~SingleAttributeTransferStrategyFactory () default
SingleAttributeTransferStrategyFactory() [8/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< MeanRatioMeasureFunctor >::SingleAttributeTransferStrategyFactory () default
~SingleAttributeTransferStrategyFactory() [8/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< MeanRatioMeasureFunctor >::~SingleAttributeTransferStrategyFactory () default
SingleAttributeTransferStrategyFactory() [9/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< MinNeighborFunctor >::SingleAttributeTransferStrategyFactory () default
~SingleAttributeTransferStrategyFactory() [9/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< MinNeighborFunctor >::~SingleAttributeTransferStrategyFactory () default
SingleAttributeTransferStrategyFactory() [10/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< NegateFunctor >::SingleAttributeTransferStrategyFactory () default
~SingleAttributeTransferStrategyFactory() [10/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< NegateFunctor >::~SingleAttributeTransferStrategyFactory () default
SingleAttributeTransferStrategyFactory() [11/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< NeighborCountFunctor >::SingleAttributeTransferStrategyFactory () default
~SingleAttributeTransferStrategyFactory() [11/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< NeighborCountFunctor >::~SingleAttributeTransferStrategyFactory () default
SingleAttributeTransferStrategyFactory() [12/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< NeighborSumFunctor >::SingleAttributeTransferStrategyFactory () default
~SingleAttributeTransferStrategyFactory() [12/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< NeighborSumFunctor >::~SingleAttributeTransferStrategyFactory () default
SingleAttributeTransferStrategyFactory() [13/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< NormalFunctor >::SingleAttributeTransferStrategyFactory () default
~SingleAttributeTransferStrategyFactory() [13/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< NormalFunctor >::~SingleAttributeTransferStrategyFactory () default
SingleAttributeTransferStrategyFactory() [14/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< ThresholdFunctor >::SingleAttributeTransferStrategyFactory () default
~SingleAttributeTransferStrategyFactory() [14/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< ThresholdFunctor >::~SingleAttributeTransferStrategyFactory () default
SingleAttributeTransferStrategyFactory() [15/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< VolumeFunctor >::SingleAttributeTransferStrategyFactory () default
~SingleAttributeTransferStrategyFactory() [15/15]
wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< VolumeFunctor >::~SingleAttributeTransferStrategyFactory () default
Member Function Documentation
create_T()
template<template< typename, int, typename, int > typename Functor> template<int ToDim, int FromDim, typename ToT , typename FromT > std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< Functor >::create_T (const attribute::MeshAttributeHandle & to, const attribute::MeshAttributeHandle & from) const
Definition at line 60 of file SingleAttributeTransferStrategyFactory.hpp.
create_transfer()
template<template< typename, int, typename, int > typename Functor> std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< Functor >::create_transfer (wmtk::components::multimesh::MeshCollection & mc) const final virtual
Implements wmtk::components::configurator::transfer::TransferStrategyFactory.
Definition at line 104 of file SingleAttributeTransferStrategyFactory.hpp.
References wmtk::components::multimesh::utils::create_attribute(), and wmtk::components::multimesh::utils::get_attribute().
get_output_attribute_description()
template<template< typename, int, typename, int > typename Functor> components::multimesh::utils::AttributeDescription wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< Functor >::get_output_attribute_description (const wmtk::components::multimesh::MeshCollection & mc) const final virtual
Implements wmtk::components::configurator::transfer::TransferStrategyFactory.
Definition at line 91 of file SingleAttributeTransferStrategyFactory.hpp.
References wmtk::components::multimesh::utils::get_attribute().
The documentation for this struct was generated from the following file:
components/configurator/src/wmtk/components/configurator/transfer/SingleAttributeTransferStrategyFactory.hpp