Wildmeshing Toolkit: wmtk::components::configurator::transfer::TransferStrategyFactory Struct Reference
wmtk::components::configurator::transfer::TransferStrategyFactory Struct Reference abstract
#include <TransferStrategyFactory.hpp>
Public Member Functions
TransferStrategyFactory ()
virtual ~TransferStrategyFactory ()
TransferStrategyFactory (const TransferStrategyFactory &)
TransferStrategyFactory (TransferStrategyFactory &&)
TransferStrategyFactory & operator= (const TransferStrategyFactory &)
TransferStrategyFactory & operator= (TransferStrategyFactory &&)
virtual std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > create (wmtk::components::multimesh::MeshCollection &mc, bool populate=true) const
wmtk::attribute::MeshAttributeHandle populate_attribute (wmtk::components::multimesh::MeshCollection &) const
wmtk::attribute::MeshAttributeHandle get_output_attribute (wmtk::components::multimesh::MeshCollection &) const
virtual components::multimesh::utils::AttributeDescription get_output_attribute_description (const wmtk::components::multimesh::MeshCollection &) const =0
attribute::MeshAttributeHandle get_output_attribute_handle (const wmtk::components::multimesh::MeshCollection &) const
Static Public Member Functions
static const TransferStrategyFactoryRegistry & transfer_registry ()
Public Attributes
std::string attribute_path
std::string type
Protected Member Functions
virtual std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > create_transfer (wmtk::components::multimesh::MeshCollection &mc) const =0
virtual void to_json (nlohmann::json &) const =0
virtual void from_json (const nlohmann::json &)=0
Static Protected Member Functions
template<typename Type >
static void register_transfer (const std::string &name)
Static Private Attributes
static TransferStrategyFactoryRegistry s_transfer_registry = create_registry()
Friends
struct TransferStrategy
void init ()
Detailed Description
Definition at line 17 of file TransferStrategyFactory.hpp.
Constructor & Destructor Documentation
TransferStrategyFactory() [1/3]
wmtk::components::configurator::transfer::TransferStrategyFactory::TransferStrategyFactory () default
~TransferStrategyFactory()
wmtk::components::configurator::transfer::TransferStrategyFactory::~TransferStrategyFactory () virtual default
TransferStrategyFactory() [2/3]
wmtk::components::configurator::transfer::TransferStrategyFactory::TransferStrategyFactory (const TransferStrategyFactory & o)
Definition at line 14 of file TransferStrategyFactory.cpp.
TransferStrategyFactory() [3/3]
wmtk::components::configurator::transfer::TransferStrategyFactory::TransferStrategyFactory (TransferStrategyFactory &&) default
Member Function Documentation
create()
std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::configurator::transfer::TransferStrategyFactory::create (wmtk::components::multimesh::MeshCollection & mc, bool populate = true) const virtual
Definition at line 27 of file TransferStrategyFactory.cpp.
References create_transfer().
create_transfer()
virtual std::shared_ptr< wmtk::operations::AttributeTransferStrategyBase > wmtk::components::configurator::transfer::TransferStrategyFactory::create_transfer (wmtk::components::multimesh::MeshCollection & mc) const protected pure virtual
Implemented in wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< Functor >.
Referenced by create().
from_json()
virtual void wmtk::components::configurator::transfer::TransferStrategyFactory::from_json (const nlohmann::json &) protected pure virtual
Implemented in wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactoryBase.
get_output_attribute()
wmtk::attribute::MeshAttributeHandle wmtk::components::configurator::transfer::TransferStrategyFactory::get_output_attribute (wmtk::components::multimesh::MeshCollection &) const
get_output_attribute_description()
virtual components::multimesh::utils::AttributeDescription wmtk::components::configurator::transfer::TransferStrategyFactory::get_output_attribute_description (const wmtk::components::multimesh::MeshCollection &) const pure virtual
Implemented in wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactory< Functor >.
get_output_attribute_handle()
auto wmtk::components::configurator::transfer::TransferStrategyFactory::get_output_attribute_handle (const wmtk::components::multimesh::MeshCollection & mc) const
Definition at line 38 of file TransferStrategyFactory.cpp.
References wmtk::components::multimesh::utils::get_attribute().
operator=() [1/2]
TransferStrategyFactory & wmtk::components::configurator::transfer::TransferStrategyFactory::operator= (const TransferStrategyFactory & o)
Definition at line 20 of file TransferStrategyFactory.cpp.
References attribute_path, and type.
operator=() [2/2]
TransferStrategyFactory & wmtk::components::configurator::transfer::TransferStrategyFactory::operator= (TransferStrategyFactory &&) default
populate_attribute()
auto wmtk::components::configurator::transfer::TransferStrategyFactory::populate_attribute (wmtk::components::multimesh::MeshCollection & mc) const
Definition at line 46 of file TransferStrategyFactory.cpp.
register_transfer()
template<typename Type > void wmtk::components::configurator::transfer::TransferStrategyFactory::register_transfer (const std::string & name) static protected
Definition at line 75 of file TransferStrategyFactory.hpp.
References wmtk::components::configurator::transfer::TransferStrategyFactoryRegistry::register_transfer(), and s_transfer_registry.
to_json()
virtual void wmtk::components::configurator::transfer::TransferStrategyFactory::to_json (nlohmann::json &) const protected pure virtual
Implemented in wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactoryBase.
transfer_registry()
static const TransferStrategyFactoryRegistry & wmtk::components::configurator::transfer::TransferStrategyFactory::transfer_registry () inline static
Definition at line 50 of file TransferStrategyFactory.hpp.
References s_transfer_registry.
Referenced by wmtk::components::configurator::transfer::from_json().
Friends And Related Symbol Documentation
init
void init () friend
Definition at line 34 of file init.cpp.
TransferStrategy
friend struct TransferStrategy friend
Definition at line 59 of file TransferStrategyFactory.hpp.
Member Data Documentation
attribute_path
std::string wmtk::components::configurator::transfer::TransferStrategyFactory::attribute_path
Definition at line 25 of file TransferStrategyFactory.hpp.
Referenced by wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactoryBase::from_json(), operator=(), and wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactoryBase::to_json().
s_transfer_registry
TransferStrategyFactoryRegistry wmtk::components::configurator::transfer::TransferStrategyFactory::s_transfer_registry = create_registry() static private
Definition at line 69 of file TransferStrategyFactory.hpp.
Referenced by register_transfer(), and transfer_registry().
type
std::string wmtk::components::configurator::transfer::TransferStrategyFactory::type
Definition at line 26 of file TransferStrategyFactory.hpp.
Referenced by wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactoryBase::from_json(), operator=(), and wmtk::components::configurator::transfer::SingleAttributeTransferStrategyFactoryBase::to_json().
The documentation for this struct was generated from the following files:
components/configurator/src/wmtk/components/configurator/transfer/TransferStrategyFactory.hpp
components/configurator/src/wmtk/components/configurator/transfer/TransferStrategyFactory.cpp