Wildmeshing Toolkit: wmtk::components::multimesh::MultimeshTagOptions Struct Reference
wmtk::components::multimesh::MultimeshTagOptions Struct Reference
#include <from_tag.hpp>
Public Member Functions
MultimeshTagOptions ()
MultimeshTagOptions (MultimeshTagOptions &&)
MultimeshTagOptions & operator= (MultimeshTagOptions &&)
~MultimeshTagOptions () override
FromTagOptions toTagOptions (const MeshCollection &mc) const
void run (MeshCollection &mc) const final
void to_json (nlohmann::json &j) const final
void from_json (const nlohmann::json &) final
bool operator== (const MultimeshTagOptions &) const
Public Member Functions inherited from wmtk::components::multimesh::MultimeshRunnableOptions
MultimeshRunnableOptions ()
bool operator<=> (const MultimeshRunnableOptions &) const =default
virtual ~MultimeshRunnableOptions ()
Public Attributes
utils::AttributeDescription tag_attribute
wmtk::attribute::MeshAttributeHandle::ValueVariant value
std::vector< utils::AttributeDescription > passed_attributes
std::string output_mesh_name
bool delete_tag_attribute = true
bool manifold_decomposition = true
std::unique_ptr< mesh_info::transfer::TransferStrategyFactoryCollection > creation_attributes
Detailed Description
Definition at line 39 of file from_tag.hpp.
Constructor & Destructor Documentation
MultimeshTagOptions() [1/2]
wmtk::components::multimesh::MultimeshTagOptions::MultimeshTagOptions () default
MultimeshTagOptions() [2/2]
wmtk::components::multimesh::MultimeshTagOptions::MultimeshTagOptions (MultimeshTagOptions &&) default
~MultimeshTagOptions()
wmtk::components::multimesh::MultimeshTagOptions::~MultimeshTagOptions () override default
Member Function Documentation
from_json()
void wmtk::components::multimesh::MultimeshTagOptions::from_json (const nlohmann::json & j) final virtual
Implements wmtk::components::multimesh::MultimeshRunnableOptions.
Definition at line 181 of file from_tag.cpp.
operator=()
MultimeshTagOptions & wmtk::components::multimesh::MultimeshTagOptions::operator= (MultimeshTagOptions &&) default
operator==()
bool wmtk::components::multimesh::MultimeshTagOptions::operator== (const MultimeshTagOptions &) const default
run()
void wmtk::components::multimesh::MultimeshTagOptions::run (MeshCollection & mc) const final virtual
Implements wmtk::components::multimesh::MultimeshRunnableOptions.
Definition at line 91 of file from_tag.cpp.
References creation_attributes, delete_tag_attribute, wmtk::components::multimesh::from_tag(), wmtk::components::multimesh::utils::get_attribute(), wmtk::components::multimesh::MeshCollection::get_named_multimesh(), output_mesh_name, wmtk::components::multimesh::utils::AttributeDescription::path, wmtk::components::multimesh::NamedMultiMesh::set_name(), tag_attribute, and toTagOptions().
Referenced by wmtk::components::multimesh::MultimeshBoundaryOptions::run(), and wmtk::components::mesh_info::MultimeshFromAttributeOptions::run().
to_json()
void wmtk::components::multimesh::MultimeshTagOptions::to_json (nlohmann::json & j) const final virtual
Implements wmtk::components::multimesh::MultimeshRunnableOptions.
Definition at line 177 of file from_tag.cpp.
toTagOptions()
FromTagOptions wmtk::components::multimesh::MultimeshTagOptions::toTagOptions (const MeshCollection & mc) const
Definition at line 70 of file from_tag.cpp.
References wmtk::attribute::attribute_type_enum_from_type(), wmtk::components::multimesh::utils::get_attribute(), wmtk::components::multimesh::FromTagOptions::manifold_decomposition, manifold_decomposition, wmtk::components::multimesh::FromTagOptions::mesh, wmtk::components::multimesh::FromTagOptions::passed_attributes, passed_attributes, tag_attribute, wmtk::components::multimesh::utils::AttributeDescription::type, and value.
Referenced by run().
Member Data Documentation
creation_attributes
std::unique_ptr<mesh_info::transfer::TransferStrategyFactoryCollection> wmtk::components::multimesh::MultimeshTagOptions::creation_attributes
Definition at line 56 of file from_tag.hpp.
Referenced by run().
delete_tag_attribute
bool wmtk::components::multimesh::MultimeshTagOptions::delete_tag_attribute = true
Definition at line 49 of file from_tag.hpp.
Referenced by wmtk::components::multimesh::MultimeshBoundaryOptions::run(), and run().
manifold_decomposition
bool wmtk::components::multimesh::MultimeshTagOptions::manifold_decomposition = true
Definition at line 50 of file from_tag.hpp.
Referenced by toTagOptions().
output_mesh_name
std::string wmtk::components::multimesh::MultimeshTagOptions::output_mesh_name
Definition at line 48 of file from_tag.hpp.
Referenced by wmtk::components::multimesh::MultimeshBoundaryOptions::run(), and run().
passed_attributes
std::vector<utils::AttributeDescription> wmtk::components::multimesh::MultimeshTagOptions::passed_attributes
Definition at line 47 of file from_tag.hpp.
Referenced by toTagOptions().
tag_attribute
utils::AttributeDescription wmtk::components::multimesh::MultimeshTagOptions::tag_attribute
Definition at line 45 of file from_tag.hpp.
Referenced by wmtk::components::multimesh::MultimeshBoundaryOptions::run(), run(), and toTagOptions().
value
wmtk::attribute::MeshAttributeHandle::ValueVariant wmtk::components::multimesh::MultimeshTagOptions::value
Definition at line 46 of file from_tag.hpp.
Referenced by wmtk::components::multimesh::MultimeshBoundaryOptions::run(), and toTagOptions().
The documentation for this struct was generated from the following files:
components/multimesh/src/wmtk/components/multimesh/from_tag.hpp
components/multimesh/src/wmtk/components/multimesh/from_tag.cpp