
#pragma once
// DO NOT MODIFY, autogenerated from the /scripts directory
#include <wmtk/Tuple.hpp>

namespace wmtk::autogen::edge_mesh {
int8_t permutation_index_from_tuple(const Tuple& t);

}

#include "permutation_index_from_tuple.hxx"
