// DO NOT MODIFY, autogenerated from the /scripts directory
#include "subdart_maximal_action_to_face.hpp"
#include "SimplexDart.hpp"
#include "autogenerated_tables.hpp"
#include "local_id_table_offset.hpp"
namespace wmtk::autogen::tet_mesh {
int8_t subdart_maximal_action_to_face_action(
    int8_t dart_index,
    int8_t simplex_dimension,
    int8_t simplex_index)
{
    switch (simplex_dimension) {
    case 1: return subdart_preserving_action_1[dart_index][simplex_index];

    case 2: return subdart_preserving_action_2[dart_index][simplex_index];

    case 0:
    case 3: return identity();
    default: break;
    }
    assert(false);
    return 0;
}

int8_t subdart_maximal_action_to_face_size(
    int8_t dart_index,
    int8_t simplex_dimension,
    int8_t simplex_index)
{
    switch (simplex_dimension) {
    case 1: return max_subdart_preservation_dimension_1[dart_index][simplex_index];

    case 2: return max_subdart_preservation_dimension_2[dart_index][simplex_index];

    case 3: return 3;
    case 0: return permutations[dart_index][0] == simplex_index;
    default: break;
    }
    return 0;
}

std::array<int8_t, 2>
subdart_maximal_action_to_face(int8_t dart_index, int8_t simplex_dimension, int8_t simplex_index)
{
    switch (simplex_dimension) {
    case 1:
        return std::array<int8_t, 2>{
            {subdart_preserving_action_1[dart_index][simplex_index],
             max_subdart_preservation_dimension_1[dart_index][simplex_index]}};

    case 2:
        return std::array<int8_t, 2>{
            {subdart_preserving_action_2[dart_index][simplex_index],
             max_subdart_preservation_dimension_2[dart_index][simplex_index]}};

    case 3: return std::array<int8_t, 2>{{identity(), 3}};

    default: break;
    }
    assert(false);
    return {};
}
} // namespace wmtk::autogen::tet_mesh
